### ISSUE TITLE
Persist "Show Remote Branches" across Git Graph view sessions per repository

### ISSUE THREAD

**Issue by postb99** [mhutchie/vscode-git-graph#123]
**Describe the improvement that you'd like**
1. The checkbox "show remote branches" was checked (and is checked back when reopening VS Code today)... should not have been...
2. But this was misleading: when I wanted to switch branch for working, I initially tried to checkout a remote branch. I got a warning but I think that the message (screenshot) should begin with "You're about to checkout a remote branch..."
3. When "show remote branches" is checked, where are my local branches? I don't seem them "at the top".

**Additional context (optional)**
![image](https://user-images.githubusercontent.com/173565/60744131-d4662f00-9f74-11e9-9663-e658b9ede107.png)

After some tries with unchecking "show remote branches", it's not clear to me how this works, sometimes I have a "detached head" warning when checking out a local branch... I initially started to write a bug report but ended up with a request for improvement. OK, I reproduced it... 1. Display only the local branches
2. Checked out a local branch I haven't worked a while on
3. Checked out the local branch I did the last commit on (top of Git Graph's commits list)
4. Got the "detached head" warning...

Thanks for reading

**Comment by mhutchie** [comment]
Currently the "Show Remote Branch" checkbox is only preserved for the current Git Graph view session. I'll implement a change so that the checkbox state is preserved per repository, across Git Graph view sessions.

Local branches are always shown in the Git Graph view. When "Show Remote Branches" is checked, remote branches are also included in the Git Graph view.

Remote branches can be differentiated from local branches as they begin with the remote name they belong to (typically `origin/<branch-name>`). They can also be joined to the right of a local branch if a local branch on the same commit shares the same name as the remote branch (to save space - this can be turned off with [git-graph.commitDetailsViewLocation](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#combine-local-and-remote-branch-labels)). I've highlighted the two possible types of remote branches in the screenshot below. There are two remote branches `origin/master` and `origin/feature`.
![image](https://user-images.githubusercontent.com/5315753/60749125-dc57ba80-9fd8-11e9-81a4-5ef232ea2096.png)
Hopefully this should allow you to easily differentiate local and remote branches.

The screenshot you provided occurs when you right click on a commit and select "Checkout...", this will checkout the commit (not a branch) as stated in the message. When git checks out a commit, a detached HEAD state will occur. In contrast, to checkout a branch (local or remote), you must right click on the branch label, and select the "Checkout Branch..." action from the context menu. When git checks out a branch, the HEAD points to the branch (and is therefore not a detached head). The "Checkout Branch..." action will be available in any branch context menu (unless it is a local branch and is currently checked out).

**Comment by mhutchie** [comment]
I've implemented a change so that the checkbox state is preserved per repository, across Git Graph view sessions. This will be available in v1.11.0.

If you'd like to use it before the next release, you can download [v1.11.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.11.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by postb99** [comment]
Thanks a lot. Indeed I wasn't smart enough for right clicking on the commit hash rather than on the branch label ...
