### ISSUE TITLE
Live Share support

### ISSUE THREAD

**Issue by lostintangent** [mhutchie/vscode-git-graph#124]
This is an amazingly useful extension, and it would be cool if it were enhanced to support [Live Share](https://aka.ms/vsls), such that if the devs collaborating had Git Graph installed, everyone would be able to use it, as if they all had the source code locally. Primarily, it would be great if “guests” were able to navigate the commit history in a read-only fashion. Live Share already makes the Source Control tab collaborative, so everyone can see/diff uncommitted changes, but Git Graph provides a much richer experience for history browsing/comparisons.

As an FYI, Live Share provides an [SDK](https://npmjs.com/vsls) that allows extensions to create their own RPC services, and synchronize arbitrary state and RPC calls between participants (e.g. commit history). You can see a simple sample [here](https://github.com/vsls-contrib/cointer), and examples of other extensions that integrate with Live Share [here](https://aka.ms/vsls-awesome).

**Comment by mhutchie** [comment]
Thank you for the feedback and suggesting Live Share! It would definitely be a valuable enhancement to Git Graph for collaborating developers. Thanks for providing links to the SDK and examples, I've had a read through the main documentation and it looks like the Live Share integration itself should integrate quite easily with how I already pass data requests and responses between the Webview and extension backend. I expect the main focus for Live Share support in Git Graph will be the "developer collaboration" component.

The main implementation tasks I see for Live Share support in Git Graph will be:
1. Extension back-end integration with the Live Share SDK.
2. Passing the existing extension data requests and responses between host and peers.
3. Restricting access to certain actions.
4. Sharing host & peers interactions with the Git Graph view (able to be turned on/off).
5. Configuration of peer access to actions (depending on the hosts preferences).

1 - 3 is the MVP, and then 4 & 5 could be added in subsequent releases.

**Comment by lostintangent** [comment]
Yep, totally agreed! 1-3 was what I primarily had in mind 👍

**Comment by mhutchie** [comment]
This issue has been left open for over eight months for others to express interest in this feature. No other Git Graph users have indicated they would like this functionality in this period.

Although this functionality would definitely be nice to have & useful, because none of the other Git Graph users have indicated they would like this feature, I'll close it for now and move it to the backlog. I simply can't justify the implementation cost (in time) if no users indicate they would use it.

Note to users reading this in the future: If you'd like this functionality, please reply to this thread to express your interest. I'd happily re-open and add this feature if there was any indication it would be used by a decent number of users would like it.

**Comment by jahd2602** [comment]
I'd really like this functionality, even if it is read-only.

**Comment by sangn2911** [comment]
I also hope this functionality implemented with Liveshare. I can check and help my colleagues with git-graph. I can also share my git setup and guide for newcomers to get used to git-graph in my team.

**Comment by thepuzzlemaster** [comment]
I'd also love this functionality in live share sessions.

**Comment by ankostis** [comment]
Me too
