### ISSUE TITLE
Head commit not shown during interactive rebase

### ISSUE THREAD

**Issue by t-gehring** [mhutchie/vscode-git-graph#126]
**Describe the bug**
During an interactive rebase, the graph gives no indication of the current state.

**What does the bug relate to**
- Graph Rendering/Log Contents

**To reproduce**
Steps to reproduce the behaviour:
1. Checkout a branch/commit
2. Begin interactive rebase (via UI, commandline, or another program)
3. Refresh graph view
4. No indication is given of current HEAD location

**Expected behaviour**
At least when the branches setting is "Show All", the graph should show the current HEAD, even when that doesn't lie on any branch.

**Environment**
 - OS: Windows 10
 - Visual Studio Code Version: 1.36.0
 - Extension version: 1.10.0

**Additional context (optional)**
I believe the solution would be to add HEAD to the getGitLog() args, so that it is shown even when it isn't on any visible branch.

If only some branches are visible, I guess the best thing would be to show HEAD if REBASE_HEAD is on a visible branch (i.e. `branches` intersect `git branch --contains REBASE_HEAD` is non-empty), but as long as it's shown in "Show All" mode, at least there's *some* way of viewing HEAD mid-rebase.

**Comment by t-gehring** [comment]
Another thing, more of a feature request than a bug, but it would be great if there was some indication of when you're in the middle of a rebase, like a label in the graph view top-bar

**Comment by mhutchie** [comment]
The current HEAD is shown if the HEAD points to a commit instead of a branch (and the commit visible on the graph):
![image](https://user-images.githubusercontent.com/5315753/60845357-62654280-a21f-11e9-89fd-fef183d728ac.png)

`getGitLog()` always fetches the head ref by calling `getRefs()`.

When you can't see the HEAD on the graph, is the commit hash corresponding to the `HEAD` ref in the output `git show-ref --head` pointing to a commit visible on the graph?
* If the HEAD commit hash points to a commit visible on the graph, it should be indicated by a dot like the above screenshot.
* Otherwise, if the commit isn't on the graph, the HEAD can't be shown (as expected).

It is possible during the rebase operation for the HEAD to not be pointing to a commit on the graph if you are rewriting history, I believe this is what you are observing. I can observe both of the above points, as expected, depending on how history is being rewritten.

**Comment by mhutchie** [comment]
I changed this issue from a bug to an improvement, because the current behaviour is expected.

Running `git branch --contains REBASE_HEAD` would have to be done in before `git log` can be run, meaning that it would increase the load time of the extension by 50% all of the time. This is not something I want to do unless absolutely necessary.

I'll add HEAD to the `getGitLog()` args if "Show All" is specified. I don't think the above command is needed as if the user has manually selected branches, they are saying "show me only these branches" (not the HEAD).

**Comment by mhutchie** [comment]
I've added `HEAD` to the `getGitLog()` args when "Show All" is selected & added some error handling for empty repositories. This will be available in v1.11.0.

If you'd like to use it before the next release, you can download [v1.11.0-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.11.0-beta.3), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

Making this change makes it much more obvious on the graph that a rebase is in progress (you can see it occurring step by step with the automatic background refreshes). Although indicating that a rebase is in progress would be nice to have, considering it is something the user should already know (they initiated the rebase), I can't justify the amount of work required to get it working reliably for the minimal benefit it offers.

**Comment by t-gehring** [comment]
Fantastic, thank you! I figured that the `git branch --contains REBASE_HEAD` might be too costly for the benefit it brings, but I thought I'd suggest it anyway. As long as the `HEAD` is always shown with "Show All", I'm happy.
