### ISSUE TITLE
show git log in reverse order

### ISSUE THREAD

**Issue by Calvin-he** [mhutchie/vscode-git-graph#133]
**Describe the feature that you'd like**
show git log in reserve order by `git log --reverse.`

**Comment by mhutchie** [comment]
Thanks for making this suggestion! Although this functionality would be ideal for completeness, and is useful in certain circumstances, I'm unsure how often it would be used by the majority of Git Graph users.

Although adding the argument itself is trivial, it poses a variety of challenges for the graph rendering algorithm I've implemented (or any other for that matter), and would require substantial modification & testing to this core component of this extension.

I'll leave this as nice to have for now, however if others would regularly use this functionally, please like the first post on this thread. If enough users would like this functionality I'd be happy to re-prioritise this and add it in an upcoming release!

**Comment by mhutchie** [comment]
This issue has been left open for two months for others to express interest in this feature. As no other Git Graph users have indicated they would like this functionality in this period, it seems to confirm my previous sentiment that this feature wouldn't be used by many users.

Although this functionality would definitely be nice to have, and would be useful under certain circumstances, it requires a significant amount a work, and adds additional complexity to the code. Because of this, and that no other users have indicated they would like this feature, I'll close it for now and move it to the backlog.

Note to users reading this in the future: If you'd like this functionality, please reply to this thread to express your interest. I'd happily re-open and add this feature if there was any indication it would be used by a decent number of users would like it.

**Comment by i11010520** [comment]
It'll be very convenient if there's --reverse option supported.
Looking forward to this feature.

**Comment by weihongliang233** [comment]
When I'm reading a Git repository, I prefer to start from the first commit because the author's main ideas are typically contained in the initial version. The initial version is also smaller and easier to comprehend. I think it would be nice to have this feature.
