### ISSUE TITLE
Remove added repository

### ISSUE THREAD

**Issue by AchmadFathoni** [mhutchie/vscode-git-graph#146]
I have a sub module repository inside my main repository. After I add that sub module repository using `git-graph.addGitRepository`, I realized that I choose the wrong folder. I looking for feature to remove that wrong repository from `Repo:` dropdown menu but it seems that feature is not implemented yet.

**Comment by mhutchie** [comment]
Thanks for raising this suggestion, this would definitely be useful to have in the extension for completeness.

The reason deleting repos wasn’t implemented when adding repos was, is because if the user deletes a repository, the extension needs to have a mechanism to remember all of the repos that should be ignored when the workspace is searched for repos on VSCode startup (otherwise it could be added back in). It’s possible to implement this, it just wasn’t worth the extra time when I first implemented adding repos.

**Comment by AchmadFathoni** [comment]
Ok, but can you  tell me where this extension save repo list? I want do some hack and delete it myself.

**Comment by mhutchie** [comment]
The extension stores this information in the Visual Studio Code [Workspace State](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.workspaceState) which is not manually editable by users.

I'm planning on implementing this in the next beta release, which will be available within the next few hours for you to use anyway.

**Comment by mhutchie** [comment]
There is now a new command "Git Graph: Remove Git Repository" that removes a repository from Git Graph. This will be available in v1.13.0.

If you'd like to use it before the next release, you can download [v1.13.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.13.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
