### ISSUE TITLE
File explorer scrollbar issues

### ISSUE THREAD

**Issue by charlesg99** [mhutchie/vscode-git-graph#153]
The following happens on vscode 1.36.1, on all platforms (linux, macos and windows). 

When dragging the scrollbar of the File Explorer, the mouse events have no effect while the mouse is over the Git Graph view. As a result, the scrollbar isn't moving while hovering over the Git Graph view and releasing the mouse button will leave the scrollbar in a "being dragged" state.

In the following gif, please notice on the upper left corner the mouse button's pressed state and its effect on the File Explorer's scrollbar.

![Peek 2019-08-01 18-00](https://user-images.githubusercontent.com/33044886/62330433-ac3ff200-b486-11e9-9fd6-9e359885d7a7.gif)

Thanks!

**Comment by mhutchie** [comment]
Thanks for raising this issue.

This bug is caused by Visual Studio Code itself, and occurs when the mouse is over any [Visual Studio Code Webview](https://code.visualstudio.com/api/extension-guides/webview). Webview's are used by many extensions that have UI, and many built-in Visual Studio Code UI's. Git Graph uses a Visual Studio Code Webview for the main Git Graph View.

For example, the same behaviour occurs when:
* Using the [Edit csv](https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv) extension's Webview
* The mouse is over the detail body of an Extension's Information Page (accessed by clicking on an extension in the VSCode Extension sidebar)

Please raise an issue with [vscode](https://github.com/Microsoft/vscode) to resolve this, as it is a bug with Visual Studio Code, and not Git Graph.

**Comment by charlesg99** [comment]
Sorry about the noise, didn't know the issue isn't specific to this extension.
