### ISSUE TITLE
Improve branch info

### ISSUE THREAD

**Issue by bitout** [mhutchie/vscode-git-graph#156]
I am working on a large project with great number of branches, sometime I get lost tracking which branch I am looking at when scrolling through commit history.
It will be very handy if it is possible to show branch info for each column through tool tips or column info.

**Comment by mhutchie** [comment]
Thanks for this suggestion! This would definitely be nice to have and make it far easier to interpret the graph for large repos.

This would require the extension to analyse the graph itself to determine ancestry information, something that isn't currently done. This analysis is already planned to be implemented as part of #139, so these features probably make sense to be developed with consideration of each other in mind.

**Comment by mhutchie** [comment]
I've implemented tooltips that are activated when the mouse moves over a commit vertex on the graph. The tooltip indicates which branches, tags and stashes include the commit, and whether the commit is included in the HEAD. The lists of branches, tags and stashes are ordered from newest to oldest, so that the most useful appear first. I hope this makes it easier to keep of which branch(es) commits belong to when scrolling through the commit history.

This will be available in v1.16.0.

If you'd like to use it before the next release, you can download [v1.16.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.16.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
