### ISSUE TITLE
Option to change file list view with commit details

### ISSUE THREAD

**Issue by kanlukasz** [mhutchie/vscode-git-graph#157]
Hey,

My suggestion is to add the option to replace the list of change files with the commit details.
It's difficult to explain, so I attach the photo below:
![obraz](https://user-images.githubusercontent.com/30685349/62868162-46b8f480-bd15-11e9-8332-e8abba84a4a6.png)

Expected view:
![obraz](https://user-images.githubusercontent.com/30685349/62868286-95668e80-bd15-11e9-9a00-d279a2a3071f.png)

What do you think?

**Comment by mhutchie** [comment]
Thanks for raising this feature request.

I understand that this may be your personal preference, however I can’t just implement it because it is your preference. Imagine if all of the 85,000+ users wanted a setting to meet there own preference. This is not only impossible to implement from a time perspective, but also inflates the extension and makes it harder for users to find important settings.

At the time of writing this response, I don’t know how this feature request would provide value to many users, as it provides no new functionality, and doesn’t allow the extension to better deal with specific kinds of repositories.

If you can please provide some reasoning to explain why this functionality would be of value to yourself and other Git Graph users, so I can understand the value it would provide, then I’d be happy to implement it.

**Comment by kanlukasz** [comment]
Thank you for the detailed answer.
Of course, I understand and agree with your point of view.

I suggested this because almost every time I expand commit, I want to click on the any file and open it (to diff it).
So I thought maybe it would be more convenient if the files were on the left.

It's detail, i know that. If it's "out of scope" i understand that.

**Comment by mhutchie** [comment]
Thanks for your response.

I'll close this request for now, as I don't have a clear indication that a reasonable proportion of users would use this UI option.

If other users would like this option, please like the original post. I'll keep on eye on this request, so if a few people do so, I'd be more than happy to reopen and implement this request.
