### ISSUE TITLE
Increase the resolution of avatars in the Commit Details View (for High DPI displays)

### ISSUE THREAD

**Issue by krupenja** [mhutchie/vscode-git-graph#164]
**Describe the improvement that you'd like**
At the moment, Github avatars look a bit blurry on HiDPI (e.g. Retina) displays), like in the screenshot below. Have seen this with several repos. Would be great if they were higher resolution.

![image](https://user-images.githubusercontent.com/26354715/63446899-b3ce3780-c443-11e9-8a4e-6a02a8b278ec.png)

**Comment by mhutchie** [comment]
Thanks for raising this improvement!

I’ll increase the resolution of the avatars in an upcoming release, so that the underlying Chromium browser doesn’t upscale the avatars on high DPI displays (which introduces the “blur”).

**Comment by mhutchie** [comment]
This will be available in v1.14.0, and applies to all avatars fetched after this update is installed. I've increased the resolution to be three times larger, please confirm that newly fetched avatars are no longer blurry.

To trigger higher resolution versions of cached avatars to be fetched (instead of waiting until their next automatic background refresh), you can run the command "Git Graph: Clear Avatar Cache" once, and reopen the Git Graph View.

If you'd like to use it before the next release, you can download [v1.14.0-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.14.0-beta.3), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
