### ISSUE TITLE
Improved support for multiple Git executables

### ISSUE THREAD

**Issue by z7z8th** [mhutchie/vscode-git-graph#165]
I have git for windows install at C:\Program Files\Git\bin,  and it's in System PATH,  
and git-graph worked before VSCode upgrade to v1.37.1  
  
but, now git-graph ignores the System PATH and git.path on windows,  
and uses C:/msys64/usr/bin/git.exe, however C:/msys64/usr/bin/ is not in System PATH.  
And git from msys64 can't make git-graph work properly,  
it shows `Unable to load Git Graph`  
Even set git.path to   "C:\\Program Files\\Git\\bin\\git.exe" can't make git-graph work.
  
The log message of git graph:

> [2019-08-22 21:01:13.863] Starting Git Graph ...
> [2019-08-22 21:01:13.957] Using C:/msys64/usr/bin/git.exe (version: 2.22.0)
> [2019-08-22 21:01:13.961] Removed repo: /s/cxx
> [2019-08-22 21:01:13.962] Started Git Graph - Ready to use!
> [2019-08-22 21:01:13.962] Searching workspace for new repos ...
> [2019-08-22 21:01:13.968] > git rev-parse --show-toplevel
> [2019-08-22 21:01:14.086] Added new repo: /s/cxx
> [2019-08-22 21:01:14.086] Completed searching workspace for new repos
> [2019-08-22 21:05:15.497] Created Git Graph View
> [2019-08-22 21:05:16.051] > git branch -a --no-color
> [2019-08-22 21:05:16.052] > git rev-parse --show-toplevel
> [2019-08-22 21:05:16.052] Started watching repo: /s/cxx
> [2019-08-22 21:05:16.056] > git rev-parse --show-toplevel
> [2019-08-22 21:05:16.057] Removed repo: /s/cxx

**Comment by z7z8th** [comment]
After remove `C:/msys64/usr/bin/git.exe` and restart VSCode, git-graph detected `C:\Program Files\Git\bin\git.exe`, even after move back the  `C:/msys64/usr/bin/git.exe`, git-graph uses `C:\Program Files\Git\bin\git.exe` still.  
git-graph seems remembering the auto detect result.  
  
Since I haven't changed the installation of both git for a long time,  
will git-graph trigger the auto detect mechanism after VSCode upgrade or git-graph upgrade?  
so changes the detected path?

**Comment by mhutchie** [comment]
I've created a [wiki page](https://github.com/mhutchie/vscode-git-graph/wiki/Git-Executable-Detection) that explains how Git executables are detected by the extension using both the System PATH, and the Visual Studio Code Setting `git.path`. This should hopefully explain when and why it uses the last known Git executable.

As I explained in my comment on the second issue you raised #166, your situation is uncommon because your computer has multiple Git executables on it (each for different platforms), and the version automatically detected by the extension returned unix style absolute paths for your repositories (because it is from `msys64`). This is incompatible with the extension because of the Windows version of Node.js packaged with your Windows installation of Visual Studio Code.

Unless a significant error occurs during a Visual Studio Code update, or sometimes if you downgrade the extension version (in rare, specific cases), the last known Git executable will always be used if it still exists on your computer. Only when the executable is no longer found will it check the System PATH and `git.path` according to the process outlined on the mentioned wiki.

I've made an improvement that will be available in the next release, so that if the user sets `git.path` to a valid Git executable, the extension will always use it instead of the last known executable (regardless of whether the last known executable still exists).

If you'd like to use this change before the next release, you can download [v1.14.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.14.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation). I'll update the wiki once this is released to reflect this change.

**Comment by z7z8th** [comment]
Thanks, that works after change git.path.
