### ISSUE TITLE
`C:/msys64/usr/bin/git.exe` not working with git-graph on windows

### ISSUE THREAD

**Issue by z7z8th** [mhutchie/vscode-git-graph#166]
Thanks for this nice and clean vscode extension.

`C:/msys64/usr/bin/git.exe` not working with git-graph on windows  
I thinks this is caused by unix style path /s/cxx not accessible in VSCode,  
this path needs to be converted before access.
```shell
msys2$ mount
...
S: on /s type ntfs (binary,noacl,posix=0,user,noumount,auto)
...
msys2$ cygpath -w '/s/cxx'
S:\cxx
```
> [2019-08-22 21:01:13.863] Starting Git Graph ...
> [2019-08-22 21:01:13.957] Using C:/msys64/usr/bin/git.exe (version: 2.22.0)
> [2019-08-22 21:01:13.961] Removed repo: /s/cxx
> [2019-08-22 21:01:13.962] Started Git Graph - Ready to use!
> [2019-08-22 21:01:13.962] Searching workspace for new repos ...
> [2019-08-22 21:01:13.968] > git rev-parse --show-toplevel
> [2019-08-22 21:01:14.086] Added new repo: /s/cxx
> [2019-08-22 21:01:14.086] Completed searching workspace for new repos
> [2019-08-22 21:05:15.497] Created Git Graph View
> [2019-08-22 21:05:16.051] > git branch -a --no-color
> [2019-08-22 21:05:16.052] > git rev-parse --show-toplevel
> [2019-08-22 21:05:16.052] Started watching repo: /s/cxx
> [2019-08-22 21:05:16.056] > git rev-parse --show-toplevel
> [2019-08-22 21:05:16.057] Removed repo: /s/cxx

**Comment by mhutchie** [comment]
Thanks for making me aware of this!

You're correct in saying that the unix style absolute path of your Git repository returned by `C:/msys64/usr/bin/git.exe` is unable to be used by Git Graph because it uses the Windows version of Node.js packaged with your Windows installation of Visual Studio Code.

I think it's reasonable to assume that the Git executable on the users computer returns the absolute file path of the repo (with `git rev-parse --show-toplevel`) according to the same operating system as Visual Studio Code is installed.

I've made an improvement as part of your first issue #165 that will be available in the next release, so that if the user sets git.path to a valid Git executable, the extension will always use it instead of the last known executable (regardless of whether the last known executable still exists). This should make this issue trivial to resolve for others in the future.

I'll close this issue for now (for the above reasons), however if other users have difficulty resolving it with the new improvement, I'll consider writing the additional code to convert the unix file paths to Windows file paths in the extension.
