### ISSUE TITLE
Option to appear in explorer view

### ISSUE THREAD

**Issue by phatmann** [mhutchie/vscode-git-graph#170]
**Describe the improvement that you'd like**
It would be wonderful if Git Graph had the option to appear in the Explorer view.

**Comment by mhutchie** [comment]
What part of Git Graph would you like to appear in the Visual Studio Code Explorer View?

If you’re referring to the entire Git Graph View, this is not possible in Visual Studio Code as extensions can only contribute tree views (and containers of them) to the sidebar. See [here](https://code.visualstudio.com/api/extension-capabilities/extending-workbench) for more information about what is possible in Visual Studio Code.

**Comment by phatmann** [comment]
Blah, you are right! Too bad, I will close the issue.

p.s. I love this extension, wherever It appears.

**Comment by mhutchie** [comment]
Thanks for the feedback @phatmann!

I keep an eye on all of the new Visual Studio Code functionality that is released, so if Microsoft does extend where WebViews can be located, I’ll look into alternative placements of the Git Graph View.

**Comment by niccolomineo** [comment]
Hi @mhutchie, with the newly released 1.49 it looks like one could have WebViews in the sidebar too. Do you think we will soon see an option to have Git Graph appear in the sidebar?

**Comment by mhutchie** [comment]
Hi @niccolomineo,

From what I can see in the Visual Studio Code 1.49 release notes, it is still in the Proposed Extension API stage, and not stably released. Regardless, it’s great to see that this extremely useful capability is now definitely coming soon to Visual Studio Code, and I’m really excited on what possibilities it may enable in Git Graph and many other extensions.

Please be aware that there is also a delay between when a new feature is released in Visual Studio Code, and when I can feasibly use it in the extension. This is because Git Graph users use a wide range of Visual Studio Code versions (not just the latest), and every time I decide to use a newly added VSCode feature, I must increase the minimum version requirement of VSCode for the extension. This prevents any user that no longer meets that requirement from receiving any further extension updates. In the past I’ve found that keeping around 9 months of VSCode backwards compatibility seems to balance leveraging new capabilities, while also not affecting too many users that use an older version of VSCode. I’m not set on always maintaining the same delay (e.g. 9 months), every new capability has different potential, and I just need to work out a suitable balance between the value added to the majority of users with a compatible VSCode version, vs leaving a smaller portion of users behind.

In terms of how I currently intend to leverage Sidebar Webview’s in Git Graph in the future, the Sidebar is a completely different form factor than in the Editor Groups (extremely tall and narrow vs reasonable landscape proportions), so it will likely be an entirely new view that offers a subset of the Git Graph View’s functionality in a more useful location within VSCode. I’ll be putting considerable thought and effort into experimenting with all aspects of this new view over the coming months, so that it’s ready to go once I increase the minimum VSCode version requirement of Git Graph.

**Comment by bvandevliet** [comment]
Will this issue be opened again anywhere soon? I believe the 9 months would have passed ;) Or maybe it's an idea to add a setting one can toggle (if his vscode version is supported) to migrate some functionality (I'm thinking about browsing file diffs) to the sidebar area, perhaps through the [Source Control API](https://code.visualstudio.com/api/extension-guides/scm-provider) if possible? I am still very interested in this feature. (For completeness, also see #438)

**Comment by st0rmblessed** [comment]
@mhutchie Docker, Hashicorp, Claude code, Codex, Copilot all appear in the sidebar so perhaps the capability now exists in VSCode? It'd be great to have this option for Git Graph. 

Bonus: Even better if it can replace the default git graph

<img width="258" height="180" alt="Image" src="https://github.com/user-attachments/assets/c5791c7b-7040-44ce-b990-ec29919b6505" />
