### ISSUE TITLE
Ability to hide one branch

### ISSUE THREAD

**Issue by thmatot** [mhutchie/vscode-git-graph#175]
Select/unselect all branches in dropdown list when clicking on "show all" item. 
This will allow to unselect one branch if all item are selected, and select one branch if all branches are unselected

**Comment by mhutchie** [comment]
Thanks for raising this improvement, it would definitely be useful to be able to “Show All” branches, and then unselect one or more specific branches.

I’ll need to work out the details of exactly how this behaviour should work, as I don’t want to impact the most common use case of the Branches dropdown (switching from “Show All” to a single branch, or vice versa). At the moment this can be done in one step (clicking on the desired branch in the dropdown), however from my understanding of what you’ve suggested, this would now unselect the specific branch from ”Show All”, instead of switching to it.

**Comment by thmatot** [comment]
What I suggest is :
- First click on Show all will have the current behavior (all branches unselected in dropdown, if I then click on one branch this branch is shown)
- Second consecutive click on "show all" (without any click on other branch between) will select all branches in dropdown (Add OK icon on the left of all branches). Then if I click another branch it is unselected and all other branches are selected

**Comment by mhutchie** [comment]
Thanks @thmatot, your suggestion is perfect for allowing both the current behaviour, and the new behaviour of this improvement request to work nicely together (and being quite intuitive for users).

**Comment by mhutchie** [comment]
Thanks again for implementing this functionality! Awesome work!

This will be available in v1.15.0.

If you'd like to use it before the next release, you can download [v1.15.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.15.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
