### ISSUE TITLE
Assigning tags and branches via drag&drop

### ISSUE THREAD

**Issue by Spown** [mhutchie/vscode-git-graph#19]
Very cool that VSC finally getting a proper git log!

Basically I suggest the same thing SmartGit's log does:
![](https://drive.google.com/uc?id=1n7Aa3HWk0sd8PRq6rjYvBgdC2_f-3IN6)

You probably know it anyway, but just in case there is [native D&D support](https://www.html5rocks.com/en/tutorials/dnd/basics/), that VSC<-Electron<-Chromium should be able to use (and probably is already using)  

Thank you.

**Comment by mhutchie** [comment]
Thank you for the feedback!

The drag and drop capability of SmartGit looks amazing!

I’m currently focusing on feature requests that add the most functionality for the most users, but this would definitely be nice to have once I’ve finished the higher prioritised items.

**Comment by mhutchie** [comment]
This issue has been left open for 9 months giving others time express interest in this feature. Although drag & drop functionality would definitely be nice to have, and would be useful under certain circumstances, as only one other user has indicated they would like this functionality in this period, it seems to indicate that this wouldn't be used by many users.

Although the core drag & drop capability does exist in Visual Studio Code, the existing "aligned to graph" branch label option of the [Reference Label Alignment](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#reference-label-alignment) Extension Setting, and another open feature request for reference labels to the left of the graph, both pose challenges for drag & drop functionality when the table is laid out with automatic column widths. Because of this, and the lack of interest indicated by other users for this feature, I'll close it for now and move it to the backlog.

Note to users reading this in the future: If you'd like this functionality, please reply to this thread to express your interest. I'd happily re-open and add this feature if there was any indication it would be used by a decent number of users.

**Comment by JohanWinther** [comment]
I would be very interested in this feature! I also believe this is one of those features that you might not realise you'd want at first, but once you start working with it you couldn't understand how you managed to do without it.
