### ISSUE TITLE
Color and position mapping per branch

### ISSUE THREAD

**Issue by HitLuca** [mhutchie/vscode-git-graph#194]
A neat feature would be to be able to define the color associated with a particular branch, as well as its positioning on the git log.

My feature request arises due to my usage of the git workflow: development is the target branch for all the PRs, but often its color and position is changed. After PR merges development is always on the left and it's colored in blue, but when work is being done it just jumps around and has a different color.

To me, just having a color-mapping alone for each branch would be a great improvement of this project

**Comment by mhutchie** [comment]
Thanks for raising this feature request!

The graph layout and rendering algorithm I developed for Git Graph is extremely complex, in order to efficiently produce a graph that is easy to interpret. It’s by far the most complex piece of logic in the whole extension. I've invested a significant amount of time trying to improve the algorithm, so that it minimises colour and layout changes (essentially the problem this feature request is trying to solve). The graph renderers for each Git GUI face the same core challenges, and are all forced to make trade-offs - some handle certain cases better than others.

I've put considerable work into making the graph render as consistently as possible with previous renders, both with respect to colour and position. It's definitely a goal of mine to incrementally make changes to improve the algorithm to achieve this as best as possible.

Please understand that there are a huge number of complexities and intricacies within the algorithm, that I will try to summarise and explain as best as possible in the text below.

---

Unfortunately this problem boils down to a single issue, there is not enough information in the last `n` commits to produce a truly consistent graph, when `n` is less than the number of commits in the repository. If all commits in the repository were used, it would be trivial to construct a consistent graph. The graph can only know the last `n` commits, as the entire repository history can't be read into memory each time the graph needs to be rendered. As the graph must be based on the last `n` commits, the following constraints are posed by Git:
* Only the parent commit relationships are known, so the algorithm must work from the most recent commit to the oldest commit. Although children relationships can be inferred from the parent relationships between pairs of commits (within the `n` commits), this does not extend past the barrier of the last commit, and therefore cannot be used.
* Git doesn’t enforce branch refs being kept after merges - it's common practice for developers to delete the branch ref once it is merged. This means the algorithm can’t rely on branch refs to determine what is a branch and what isn’t. Therefore, rendering algorithms can only use the parent relationships of each commit, and not the actual git branches. From the algorithms perspective, the ends of branches are commits that haven't already been rendered in the current rendering. See this example where the numbers are the render order: 
```
1 <- end of a branch (HEAD)
|
2  
|
|  4 <- end of another branch
|  |
3  |
|  |
...
```
* Commits may be inserted or deleted at any point in the graph between consecutive renders. Consider: new commits, branches being shown or hidden in the "Branches" Dropdown, new commits fetched from remotes, deleted commits after pruning remotes etc.

Other desirable (and practically required) constraints are:
* Rendering should be performed in linear time to the number of commits. As repos can get large quickly, it needs to be capable of rendering thousands of commits - polynomial time algorithms are not feasible. Because of this, the graph should be laid out in a single linear pass through the commits (my previous example shows such a render order).
* Colours and positions are only used to differentiate different lines of history when absolutely necessary, keeping the graph as small and with as few colours as possible.

From these constraints, the following points can be made:
* During graph rendering, the algorithm only knows for sure the layout and colour of commits that have already been rendered.
* It could be possible for the algorithm to try scanning ahead to find commits that may have been laid out in a previous rendering (only possible in some circumstances). This would introduce: significant complexity to the code, and make it harder for the user to understand why the commits are laid out and coloured as they are.
    * Even if this was implemented, when the code did detect that a commit was previously rendered in a specific position with a certain colour, that may conflict with the already partially rendered graph. A conflict means that a branch appears next to another of the same colour, or a commit exists where another edge already is. I believe this is impossible to resolve in a remotely efficient manner, as the algorithm would have to back-track, and re-layout all of the vertices and edges already completed, making alternative choices that may or may not fix the conflict.

---

I'm closing this issue for now due to the above points meaning that a fixed mapping is not feasible at the current time. However, I'll continue to work on the core part of this request (to make the graph easier to read, and more consistent across consecutive renders). If you, or anyone else reading this in the future has a feasible solution, please reply to this thread as this will always be an ongoing effort for improvement, and input is always appreciated & valued. Before proposing an alternative algorithm or suggestion, please consider the trade-offs of the approach. (Even just constructing this reply has taken as much to write as fully implementing some feature requests)

FYI: The core part of the current algorithm is [here](https://github.com/mhutchie/vscode-git-graph/blob/ac44d35ee65dc9e113c59f88451ee9b241271990/web/graph.ts#L401-L408) & [here](https://github.com/mhutchie/vscode-git-graph/blob/ac44d35ee65dc9e113c59f88451ee9b241271990/web/graph.ts#L545-L613), which leverages the rest of [the file](https://github.com/mhutchie/vscode-git-graph/blob/ac44d35ee65dc9e113c59f88451ee9b241271990/web/graph.ts).
