### ISSUE TITLE
Push button

### ISSUE THREAD

**Issue by peterdickx** [mhutchie/vscode-git-graph#195]
Add a "push" button next to the "fetch" button

**Comment by mhutchie** [comment]
Thank you for raising this feature request!

I considered adding a "push" action when I first added "fetch" to the control bar, however I decided against it as pushing and pulling is already available in the Visual Studio Code Git Extension's Status Bar Item for "Synchronise changes", especially because:
* The VSCode Status Bar Item is always accessible no matter what is open in Visual Studio Code. If it was added to the extension, it would only be available when the Git Graph View is open (far less useful).
* Git Graph already provides "push" and "pull" functionality from the local and remote branch context menus. This is available because if offers additional value to users, i.e. they can "push" and "pull" individual branches (not all branches). The main benefit of the graph (and Git Graph in general) is that it allows actions to easily be performed at a branch / tag / commit / stash level, not just on the whole repo.
* The VSCode Status Bar Item provides additional functionality, remote ahead & behind information, at a glance. Users would likely prefer to have the same information also in the Git Graph control bar, leading to even more duplication.
* No other users (out of the ~140,000 Git Graph users) have requested or indicated they'd like this feature (even after "fetch" was implemented 5 months ago). This tells me that most people are happy using the VSCode Status Bar Item for "push" and "pull", and it may have become habit.
* Git Graph is designed to complement and extend the capabilities of Visual Studio Code, not duplicate it. Even though I agree adding "push" next to "fetch" is good for completeness in the extension, I don't think it is good practice to duplicate the same functionality in a single application ("fetch" is only there because it is not easily accessible in Visual Studio Code).
* There is limited space left in the top control bar for additional buttons (especially in multi-root workspaces). I already intend to use the little space that is left for commit filtering functionality (e.g. by author), which would extend the capabilities available to Visual Studio Code users.

For these reasons I don't intend to add this functionality (at least for now), so I'll close this issue and add it to the backlog.

If other users reading this in the future that would also like this functionality, please like / reply to this thread so I can keep track of community support. If there is significant support for this functionality, I'd be more than happy to implement it - I just need to be confident that support out-weights my objections.
