### ISSUE TITLE
(Option to) Open Git Graph immediately when clicking the Source control tab

### ISSUE THREAD

**Issue by peterdickx** [mhutchie/vscode-git-graph#199]
It would be great to have an option to make Git Graph open immediately when you click the source control tab, instead of having to click the git graph icon at the top.

![image](https://user-images.githubusercontent.com/19954023/66653883-4c5d8880-ec39-11e9-9480-b5f2aa845d04.png)

**Comment by mhutchie** [comment]
Thanks for raising this feature request!

Unfortunately it is not possible in Visual Studio Code for the extension to be triggered when the Source Control tab is opened. When Visual Studio Code or an extension contributes an item to a menu, it assigns a command to be triggered when it is clicked. As Visual Studio Code contributes the Source Control tab item, it will open the Source Control View as specified in their definition. There is no way for the extension to intercept / monitor commands that it doesn't contribute.

Even if it was possible, there would be no way for the extension to know which repo to open for, if their are multiple repos in the workspace. The current Git Graph button in the Source Control View appears once per repo in the view, so that when the user clicks the button Git Graph will open it to the correct repo.
