### ISSUE TITLE
Show fast-forward-mergeable branches as branches, not as an up-continuations of the trunk

### ISSUE THREAD

**Issue by dko-slapdash** [mhutchie/vscode-git-graph#200]
Let me just tell a story about what Facebook Dev Tools team implemented in "arc diff" tool (a graph-view of the repo) a few years ago and what appeared to be **extremely** useful.

Imagine we have the following repo with 2 branches which are fast-forwardable from master:
```
mkdir gr && cd gr
git init
touch init.txt && git add . && git commit -m init
touch init1.txt && git add . && git commit -m init1
git checkout -b b1
touch b1.txt && git add . && git commit -m b1
git checkout -b b2
touch b2.txt && git add . && git commit -m b2
touch uncommitted.txt
```

Currently, git-graph shows it like this:

![image](https://user-images.githubusercontent.com/46383452/66708291-079e2400-ed03-11e9-9d4a-81804dbd9622.png)

Facebook engineers realized that, despite b1 and b2 are fast-forward-mergeable, they're still branches, and branches on a tree in nature never grow upward - they always grow aside.

So for the above repo, the following picture would be WAY more intuitive and useful:

![image](https://user-images.githubusercontent.com/46383452/66708371-631ce180-ed04-11e9-9911-69aba334721e.png)

This representation has a great advantage of being intuitive, and also it still doesn't hide the fact that the branch is fast-forward-mergeable.

And even more, such representation opens an ability to rebase branches by just drag-and-dropping them in the UI (if this feature is to be implemented somewhere in the future).

**Comment by mhutchie** [comment]
Thanks for raising this improvement request, I hadn't seen this approach before! _(thanks for also providing an example illustrating the benefits of this approach)_

I understand the motivation that branches on a tree never grow upward, they always grow to a side. Although I agree that this approach has several advantages (that you've outlined above), that doesn't necessarily mean it is _"WAY more intuitive and useful"_.

For balance, here are several counter-arguments / disadvantages I can think of:
* The feedback I receive frequently from the user community is that they have large repos, and they want the graph to be as narrow as possible while still clearly representing their repo. Implementing this approach would make their graphs (arguably unnecessarily) wider.
* In the example you've provided, arguably no branching has occurred as no commit has two children. The current graph layout algorithm operates on the relationship between commits and their parents (always available), and doesn't rely on branch references as they're only available a relatively small amount of the time compared to all of the branching in a repo (as developers commonly delete them after merging). It made sense when developing the layout algorithm to use mandatory information from commits, not optional branch references.
* In the example you've provided, if the branch reference "b1" is deleted, then the rendered graph would be different. However, deleting the branch reference didn't actually change the repo contents - so why should the graph change. This applies in reverse when adding a new branch "b3" to the existing commit where "b1" was, again the repo contents hasn't changed, but the graph would. The current commit based method means that for every repos contents (derived from the commit history), there is a unique graph describing it. Utilising branch references would mean the same repo contents could be graphed in infinitely many ways. If users saw that the graph changed, I think they would expect the repos contents to have also changed, not because they added/deleted a branch.

I'll leave this request open to gauge interest from the community, and see if they would value this improvement over the existing approach!

**Comment by dko-slapdash** [comment]
Thanks!

I just remember how it was in Facebook. First they implemented a graph view in "arc diff" the same way as it looks like in git-graph (and in "git log --graph" pretty much). It was not too useful, frankly speaking. In a couple months, they caught up and switched to "aside-branched" approach, and I remember my personal (and my colleagues') feeling that it became way way better. Since then, everyone was using this new "arc diff". I think it was a real invention which is hard to explain to people unfortunately.

I'm personally not too worried about "never change the graph picture if a branch is added or deleted" principle. What matters is visual intuitiveness.

Another example:

```
mkdir gr && cd gr
git init
touch init.txt && git add . && git commit -m 'init'
touch init1.txt && git add . && git commit -m 'init1'
touch init2.txt && git add . && git commit -m 'init2'
git checkout -b some_branch
git checkout master
touch init3.txt && git add . && git commit -m 'init3'
touch init4.txt && git add . && git commit -m 'init4'
git checkout some_branch
touch uncommited.txt
```

This is what git-graph shows:

![image](https://user-images.githubusercontent.com/46383452/66709574-00374480-ed1c-11e9-9901-828d3f86e55f.png)

From an intuition point of view, this is a little WAT. I understand that there is no notion of a "main trunk" currently, so to git-graph, master branch is no different than some_branch. That's why the tree's trunk became a branch, and a branch became the tree trunk (I mean a tree in nature, like an oak or birch).

What a "naturalist" (a person who learns the nature and trees) would expect in this case (and what FB tools team did) is following:

![image](https://user-images.githubusercontent.com/46383452/66709708-82c10380-ed1e-11e9-8c97-d802b120f445.png)

Clearly visible: "I'm sitting in some_branch derived from master and have some changes which, when committed, will continue this branch". It's like a new sprout detached from the main tree's trunk.

**Comment by mhutchie** [comment]
This improvement request has been left open for 3 weeks for others to express interest in this functionality. As none of the 165,000+ current Git Graph users have indicated they would like this functionality in this period, it indicates to me that the majority of users are happy with the existing approach, and don't think the benefits of this approach outweigh the negatives.

Although this functionality would definitely be nice to have, and may make the graph more intuitive to some users, as none of the other users have indicated they would like this functionality, I can't justify the significant amount of time to develop this functionality at the present time. I'll close it for now and move it to the backlog.

Note to users reading this in the future: If you'd like this functionality, please reply to this thread to express your interest. I'd happily re-open and add this functionality if there was any indication it would be used by a decent number of users would like it.

**Comment by meanspa** [comment]
Hello! Future user here. For what it's worth, I would find this functionality very useful. A couple small points:

- I could see this being very helpful as an optional layout, though thanks to the helpful explanation of its drawbacks (thanks @mhutchie!) I wouldn't expect it to be the default. 
- With regard to other users not voicing this concern, I can say for myself it took quite a while to find this issue because I didn't know what to search for. I'm relatively new to git (mostly worked with mercurial in the past) and I've run into this frustration several times over the last year or so, and this is the first time I've successfully found a discussion about it. I just mention this in case it helps to take into account why nobody else may have voiced this concern (especially since I'm guessing it's primarily a pain point for new users like myself, who might not even realize it's related to fast-forward commits).

Of course I can't speak to prioritization relative to how much work it would require, but for what it's worth I would find it very helpful. Just adding another vote (2 votes in only 2 years!).

Cheers, and thanks for all of the work on this extremely helpful tool!

**Update**: _I just discovered the ability to use the `--no-ff` flag when doing a merge, and the ability to add this to the repo's settings as well. For my use case I think this is probably the best route rather than a UI change, just mentioning this in case it's helpful for anyone else who stumbles across this issue._
