### ISSUE TITLE
Option to show Git Graph in a panel

### ISSUE THREAD

**Issue by phatmann** [mhutchie/vscode-git-graph#210]
I'd like the option to show Git Graph in the Panel view. This would be especially useful when viewing the changes in a commit, because clicking a file to open it would keep Git Graph in view. It would also allow Git Graph to be hidden and shown more easily.

**Comment by mhutchie** [comment]
Thanks for raising this feature request!

When you mention the _"Panel view"_, are you referring to Section D on the first image [on this page](https://code.visualstudio.com/docs/getstarted/userinterface)? If so, the Git Graph View uses a WebView, which Visual Studio Code unfortunately only supports in the Editor Group area (Section C), where it currently is.

I also can't find any references in the Visual Studio Code documentation that would allow an extension to contribute some custom UI / content in a new panel in Section D. The only way to get any content there is by integrating with one of the existing features (e.g. a logging output channel - like Git Graph already does, or Code Problems).

**Comment by phatmann** [comment]
Ah well. Thanks for looking into it!

**Comment by mhutchie** [comment]
I keep an eye on all of the new Visual Studio Code functionality that is released, so if Microsoft does extend where WebViews can be located, I’ll look into alternative placements of the Git Graph View.

I’ll also keep track of any VSCode API integrations that might allow custom content in Section D, even if it’s not a Webview. There is definitely a lot of potential in being able to utilise this area of the UI in some way.

**Comment by geropan** [comment]
@mhutchie - Apologies for bumping this closed issue, but the technical limitation you mention about not being able to use webview in panel areas might not longer exist according to [this](https://code.visualstudio.com/api/extension-guides/webview):

> Webviews are used in several VS Code APIs:
...
In [Webview views](https://code.visualstudio.com/api/references/vscode-api#WebviewView) that are rendered in the sidebar or panel areas. See the [webview view sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-view-sample) for more details.

Having git graph rendered on a panel instead of an editor tab would be really convenient.

**Comment by phatmann** [comment]
@geropan thanks for heads up, this is great news. 

I recommend opening a new issue, as often maintainers don't see comments on closed issues.
