### ISSUE TITLE
Ctrl + select to squash commit together

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#214]
**Describe the feature that you'd like**
Being able to select multiple commit within the same branch and squash them together.

a: on `ctrl` : 
1. the commit wouldn't open it self anymore.
2. Every branch would fade out (maybe to the gray) and only the branch which we hover would show his colour.

b: on `select`
1. every other branches that aren't selected would not be displayed.
2. we would be able to select the issues we want to squash
  2.2  it is always a from ... to, so, it will auto select every commit in between.

c: on `right click`
1. list with multiple action on this commit (ex. squash commits)

**Additional context**
I saw some Issues about this specific subject (#179, #182) but, being able to squash it like that would be that much easier and faster.

I understand how hard it would be to develop what I describe here, but the `b.2` and `c.1` would already be an amazing feature.

**Comment by mhutchie** [comment]
Thanks for making these suggestions!

As you mentioned, the core functionality of this request is already included in #182, so I'll close this feature request (as multiple issues shouldn't be tracking the implementation of the same core functionality). Because there are several git commands that can operate on multiple commits, I want to make sure the solution I implement will enable all of these commands to be included in Git Graph, and not have different ways of selecting / handling multiple commits depending on the specific git command.

When I implement #182 in an upcoming release, I'll explore the suggestions you've made in this feature request to work out the best way of integrating multi-commit git commands into Git Graph.
