### ISSUE TITLE
Repository Settings Icon

### ISSUE THREAD

**Issue by AnthonyLenglet** [mhutchie/vscode-git-graph#215]
**Describe the improvement that you'd like**
Whenever I am in the graph, I keep hitting the gear icon thinking it'll lead me to the git graph part of the vscode options menu or to a custom option menu, not really the repository configuration info.

I feel like an icon other than a gear would be better for this, maybe the repository octicon ?
![image](https://user-images.githubusercontent.com/36004334/69143159-a9feb380-0ac8-11ea-9458-3422bf2a70dc.png)

**Comment by mhutchie** [comment]
Thanks for raising this improvement request!

The gear icon that is used in Git Graph is quite universally used to indicate "settings" of some form. I can understand that at a first glance it could imply that it may open settings other than the repositories, however as soon as the Settings Widget opens, it clearly states "Repository Settings" to resolve any confusion. Also, **every** UI element within the Git Graph View operates on the open repository, so its fairly reasonable that a settings icon would also refer to the repositories settings, and not the extensions settings.

Using the repository icon like you suggested doesn't give the user any indication that the button would open a settings menu, as its meaning is just a repository. This would mean that the user would likely never even try clicking on it for settings (and consequently not know about or use a decent amount of Git Graph functionality).

When I first implemented the Repository Settings Widget and was choosing an icon, I felt that the gear icon best indicated "settings", and its placement alongside buttons operating on the repository completed the implication of "Repository Settings". I couldn't find any other icons in the Octicon's set (or elsewhere) that combined both "repository" and "settings" any better than my current approach. I also tried to make my own icon as a hybrid of the repository icon you mentioned & the settings icon currently being used, however at such a small size both elements lost their ease of recognition.

This icon has been in use since the Repository Settings Widget introduction four months ago, and none of the other 180,000+ extension users have indicated they find it misleading.

I'd be keen to update the icon if a better icon was available that clearly conveys both "repository" & "settings" (I'm just not sure there is a better option). I'll leave this improvement request open for a while to see if any other users have other icon suggestions that meet these criteria.

**Comment by mhutchie** [comment]
I found a way in Visual Studio Code for extensions to open their Extension Settings. As this was possible, I've added a button on the Repository Settings Widget to "Open Git Graph Extension Settings", which opens the extensions settings in the Visual Studio Code Settings Editor. As your original improvement was focused on the "Settings" icon being misleading, by adding this button it now provides what you mentioned you expected.

This will be available in v1.19.0.

If you'd like to use it before the next release, you can download [v1.19.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.19.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

If anyone is reading this issue in the future, and you have a better icon for the Repository Settings Widget (that clearly conveys both "repository" & "settings"), please respond to this thread. (I'd be happy to include it)
