### ISSUE TITLE
Option to hide tags in graph

### ISSUE THREAD

**Issue by DavideCanton** [mhutchie/vscode-git-graph#216]
Hi, thanks for the great work, your extension is super!

I would like an option to show/hide the tags in the graph, because if a commit has way too many tags, it's uncomfortable to read the graph.

**Comment by willpower232** [comment]
I've got some stray tags on squash-merged branches so this would be a definite improvement

**Comment by mhutchie** [comment]
Thanks for raising this feature request, and the feedback on the extension!

Here are two related Extension Settings:
* [Reference Label Alignment](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#reference-label-alignment) - Allows tags to be moved to the right of the commit message.
* [Show Commits Only Referenced By Tags](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#show-commits-only-referenced-by-tags) - Does what the name suggests.

How are you envisaging that tags would be shown / hidden, as there are multiple ways to implement what you've describe that have vastly different behaviours? Three example approaches I can think of (but there are others) are:
* A new Extension Setting "Show Tags" that shows / hides all tag reference labels. If set to hide tags, it would override "Show Commits Only Referenced By Tags" and hide them as well. Operates at a user or workspace level.
* A new "Show Tags" checkbox in the top control bar like "Show Remote Branches" that shows / hides all tags (operates at a repository level). I'm very cautious about adding anything to the top control bar, as it is already very full in multi-root workspaces, and I'm wanting to use the little space that is left for upcoming filtering functionality. Perhaps "Show Remote Branches" & "Show Tags" could move into the filtering menu / interface when I implement it (I'm not sure how I want to go about it yet).
* Add a "Hide Tag" option in the tag context menu so that individual tags can be hidden. A restoration method would also be available (e.g. in the Repository Settings menu). My issue with this is if the tag has so little meaning to the user for them to hide it, why don't they just delete it.

@DavideCanton I'm not sure of the specifics of your use case, however tags have significant meaning in Git repositories, so I think hiding tags defeats the purpose of having them in the first place. If you have too many tags just on one commit, perhaps you could reduce the number of tags on it.

@willpower232 Perhaps the second Extension Setting I mentioned above might be enough to resolve your situation. If not, please let me know which approach of the above would best meet your needs, or suggest your own?

**Comment by DavideCanton** [comment]
My problem is that we have an existing architecture with a CI adding a tag to a commit whenever a build is triggered, and whenever an artifact is deployed on maven, and the tag names are autogenerated, and pretty long (they overflow in a 1920x1080 monitor), so I would like to hide all the tags when I don't need to have them displayed.

**Comment by mhutchie** [comment]
Thanks for the clarification!

I'll add a "Show Tags" checkbox in the Repository Settings Widget (that operates per repository). I think this is a suitable place for the checkbox as it will be used far less frequently than the "Show Remote Branches" checkbox by far less users, and is still only one click away in the Repository Settings Widget.

I'll also add a "Show Tags" Extension Setting, so that a default can also be set for all of your Visual Studio Code workspaces.

**Comment by mhutchie** [comment]
This will be available in v1.19.0, which will be released in the next day.
