### ISSUE TITLE
GitGraph auto open

### ISSUE THREAD

**Issue by caasihaon** [mhutchie/vscode-git-graph#217]
**Describe the feature that you'd like**
When you open the folder, or switch the project in VSCode it would be nice if GitGraph would auto-open once git repository is detected.

**Comment by mhutchie** [comment]
Thanks for raising this feature request!

If the extension was to have an Extension Setting that enabled auto-opening, would you want it to open in front of the document that is active, or preserve the existing documents focus and open in the background?

Are you also implying that every time you open a workspace in Visual Studio Code, and it contains a Git repository, you want the extensions View to open?

Alternatively, I'm pretty sure there is a way within the Visual Studio Code API to persist the Git Graph View across Visual Studio Code sessions in the same workspace (just like any files that are open in the workspace). Upon re-opening a workspace, its tab position and focus state would restored exactly the same as when you last closed the workspace. This has a similar effect to what you're requesting, but may be less imposing to users. What are your thoughts on this instead? _(I've been meaning to explore this for some time)_

**Comment by caasihaon** [comment]
Thanks for quick reply. I actually think that second approach would be much better, as not everyone will appreciate auto-opening. So if we can remember it as "opened tab" that would be fantastic.

**Comment by mhutchie** [comment]
I've been working on implementing this, and it's reminded me of why I didn't implement it in the first place.

Although the core of this behaviour works perfectly, there are numerous limitations / restrictions to do with the Visual Studio Code API in this area. Although most can be worked through reasonably and resolved, Visual Studio Code's Lazy Loading of Editors can cause a second (duplicate) Webview to be created (if after re-opening the workspace the user opens the Git Graph View, instead of clicking on the previously used tab). For the Git Graph View to maintain its state correctly, it must maintain the condition that only a single Git Graph View is ever open.

Visual Studio Code already has an open issue that would allow the extension to prevent duplicate Webview's from being opened, however it is not yet implemented. I've been extremely impressed with how much better it is to persist the Git Graph View across Visual Studio Code sessions, and think it would be of great value to almost all users. I think it's best to wait for Visual Studio Code to implement the required core capability (hopefully soon), and then I can utilise it with the code I've written today to make it available in Git Graph. Because of this, I'll move this feature request to the backlog, and close it temporarily until Visual Studio Code makes this core capability available. I'll monitor Visual Studio Code's progress, so that as soon as it becomes available I can re-open this feature request and make this functionality available in Git Graph.

Thanks again for raising this feature request, I'm really looking forward to making this available in Git Graph as soon as possible!

**Comment by caasihaon** [comment]
Cheers, I understand the case, thanks for looking into it

**Comment by gotjoshua** [comment]
> making this available in Git Graph as soon as possible!

i would love if git graph view could auto-open and be pinned as the far left tab.

if there is no possibility yet for you to include that (due to missing features in vs code) does anyone know of a way to use a task or some other automation means?

**Comment by Vinorcola** [comment]
Hello @mhutchie,

I join the comment above: It would be great if we could have an option that allow the GitGraph to be opened and pinned at startup. The best would probably be to allow this configuration per project.

I don't know anything about how VSCode settings works for extensions. So do you have any news on VSCode capabilities for this?

Thanks in advance.

**Comment by brendan-simon-indt** [comment]
Bump!  Now February 2023, and I still groan every time I have to re-open my GitGraph window 😭 

Surely there must be some (not too hacky) way to auto load the GitGraph is some pending state, or auto-load it after vscode folder/workspace is opened and reached some stable state, then open GitGraph (just as if the user clicked on the icon to open it manually?)

**Comment by mrcwebdesign** [comment]
You can define a custom autorun task for it. I used the MoveTab extension also (https://marketplace.visualstudio.com/items?itemName=ahgood.movetab) for moving the tab to the very first position. Enjoy! 🥳

.vscode/tasks.json:

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Git Graph autostart",
			"dependsOrder": "sequence",
			"dependsOn": [ "Git Graph open", "Git Graph pin tab", "Git Graph move tab to first" ],
			"runOptions": { "runOn": "folderOpen" },
		},
		{
			"label": "Git Graph open",
			"command": "${command:git-graph.view}",
		},
		{
			"label": "Git Graph pin tab",
			"command": "${command:workbench.action.pinEditor}",
		},
		{
			"label": "Git Graph move tab to first",
			"command": "${command:movetab.moveTabToFirst}",
		}
	],
}
```
