### ISSUE TITLE
Files tree to activity panel and allow open diff view below the graph

### ISSUE THREAD

**Issue by andreiucm** [mhutchie/vscode-git-graph#229]
**Description**
Hi, very nice work this extension.  Thank you very much.
Here is my suggestion: maybe you can consider moving the file tree and the commit description tho the panel and put an option that allows opening the diff view editor below the graph as I show on the screenshot

<img width="1674" alt="Screen Shot 2019-12-06 at 17 12 15" src="https://user-images.githubusercontent.com/19815046/70333833-e5c9a500-184c-11ea-8343-a1135c90f703.png">

In my opinion, this will make the workflow much easier since we will gain space and visually we will be able to see the files properly and the graph if we want to click around and also the diff view.

**Comment by mhutchie** [comment]
Thanks for the feedback!

Unfortunately Visual Studio Code doesn't allow extensions to contribute UI like the Commit Details View to the Side Bar. Any content shown in the Side Bar must be structured like a tree, which is definitely not suited to the Commit Summary included in the Commit Details View. As the Commit Details View contains both a Commit Summary and Files View, they shouldn't be separated across [UI boundaries](https://code.visualstudio.com/docs/getstarted/userinterface) in Visual Studio Code.

The docs [here](https://code.visualstudio.com/api/references/contribution-points#contributes.views) explain what content can be placed in the SideBar. The extension uses a [Webview](https://code.visualstudio.com/api/extension-guides/webview) for the Git Graph View, which can only occur in the Editor Group UI (Section C of the first image on [this page](https://code.visualstudio.com/docs/getstarted/userinterface)).

As this request is not possible due to a Visual Studio Code limitation, I'll close this issue for now. There have been numerous feature requests for moving some portion of Git Graph functionality to the Side Bar, all of which are not currently possible. As there is so much interest, I'm closely monitoring any new core capabilities released in Visual Studio Code. If Visual Studio Code provides the necessary core capabilities in the Side Bar, I'll be reconsidering / re-opening these requests.

FYI: #206 will be providing the option for showing File Diff's within (and/or below) the Git Graph View. Based on the underlying problem your feature request is addressing, #206 might improve / resolve it for you.

**Comment by andreiucm** [comment]
Oh sorry, I didn't fully explain maybe. What I mean is not moving the graph to the activity panel. Let it stay where it is. There is also a nice improvement here https://github.com/mhutchie/vscode-git-graph/issues/88 since I don't think large branches' names will be easy to display on the activity panel even if vscode will allow it. So the graph is ok where it is. Move **only** the file tree to the activity panel. 
Then the commit details can be ignored and showed as a tooltip on **hovering a commit** or even skip it completely since we already see enough info on the table( maybe as an improvement, you can provide an **item on the context menu** (when we click on the left side of the mouse on concrete column) to copy commit-hash/ copy commit-message/ copy commit-date / copy-author... 
What we gain now is once the vscode issue will be resolved https://github.com/microsoft/vscode/issues/84113 you do not need to duplicate the diff editor functionality and depending on what user select( Beside/Below ) you open the diff editor after the click on the commit. 
Hope you can consider it :)

**Comment by mhutchie** [comment]
I didn't think you were referring to moving the graph to the Side Bar at all.

The Commit Details View contains both the Commit Summary (left) and File Tree / List / Code Review (right). The Commit Summary offers far more functionality beyond what is shown in the table (full commit message, parent hashes, committer, full timestamp, large avatars, hyperlinked issue numbers and urls), that shouldn't be lost and cannot simply be placed in a tooltip or right click menu item).

Although the File Tree itself could be moved to the Side Bar (as you're requesting), the Commit Summary cannot because of Visual Studio Code limitations. This would either mean losing the Commit Summary (definitely not something I want to do), or splitting the Commit Summary & File Tree across UI boundaries in Visual Studio Code (not good practice or intuitive to users). Although you might be using the File Tree View, others prefer the File List View alternative (that also wouldn't be feasible in the Side Bar).

Like I said before, if Visual Studio Code extends the available integrations with the Side Bar for extensions, I'll be reviewing the Side Bar related feature requests and look to implement them were appropriate (as they each have clear benefits). However, at the present time with the currently available Visual Studio Code Side Bar integrations I don't think there is any functionality in the Git Graph View that should be moved, or would benefit from being moved to the Side Bar (there always seems to be some major / minor disadvantages or compromises).

**Comment by andreiucm** [comment]
Ok, I see. Thank you anyway!  Hope vscode will improve the Side Bar soon.

**Comment by felixvd** [comment]
An option you didn't mention: keep the Commit Summary text-only when it is in the Side Bar. Just noting for completeness.
