### ISSUE TITLE
[Question] installing this git client to atom

### ISSUE THREAD

**Issue by arnotes** [mhutchie/vscode-git-graph#230]
good morning guys.
is it possible to install this to atom editor?
also, are there any plans to make this a standalone git client?

**Comment by mhutchie** [comment]
This extension is only available for Visual Studio Code, not other IDE’s like Atom. Git Graph is designed to complement Visual Studio Code to provide a seamless development experience. It has many integrations with Visual Studio Code that are simply not transferable to other IDE’s (without spending significant time to create an Atom specific version of the extension). I much rather spending the time to provide new functionality to the current and constantly growing Visual Studio Code and Git Graph user communities. Several of the exciting upcoming features to Git Graph will provide even more integrations with Visual Studio Code, making further improvements to developer’s workflows. 

There’s also no plans to make Git Graph a standalone Git Client for the same reasons, and because there are already many excellent standalone options.
