### ISSUE TITLE
Add a command to resume a specific code review

### ISSUE THREAD

**Issue by cateyes99** [mhutchie/vscode-git-graph#231]
**Git Graph** has a feature called `Code Review`. If there are multiple Code Reviews, it has a command called `End All Code Reviews in Workspace` to clear them. But interestingly there is no command something like `List All Code Reviews in Workspace` to list them, so it's actually hard to find them out. In this situation, such a `List All Code Reviews in Workspace` command will be very helpful.

**Comment by mhutchie** [comment]
Thanks for making this suggestion, this would be great to have in Git Graph!

I think it would be nice to accompany this with a way to open the Code Review directly from the list (or something similar).

**Comment by cateyes99** [comment]
It would be event better 👍

**Comment by mhutchie** [comment]
I've added a new command "Git Graph: Resume a specific Code Review in Workspace...". When run, the user is shown a list of all code reviews so they can choose one to resume (or press escape if they don't want to proceed). I also implemented another command "Git Graph: End a specific Code Review in Workspace..." that behaves equivalently for ending a specific code review.

Visual Studio Code does not provide a suitable UI element for just showing a list of items without them being selectable, so I didn't implement a separate "List All Code Reviews" command. Since there is now resume and end commands, I think most users wouldn't have a need to just view a list of code reviews, without wanting to resume or end one. If the user does just want to check if any code reviews are in progress, they could always just run the resume command to see the list, then press escape to exit the list (and not proceed with resuming). If after the release I get feedback that indicates a list command would also be used, I'd be happy to add it in the following release.

This will be available in v1.22.0.

If you'd like to use it before the next release, you can download [v1.22.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.22.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by cateyes99** [comment]
> I've added a new command "Git Graph: Resume a specific Code Review in Workspace...". When run, the user is shown a list of all code reviews so they can choose one to resume (or press escape if they don't want to proceed). I also implemented another command "Git Graph: End a specific Code Review in Workspace..." that behaves equivalently for ending a specific code review.
> 
> Visual Studio Code does not provide a suitable UI element for just showing a list of items without them being selectable, so I didn't implement a separate "List All Code Reviews" command. Since there is now resume and end commands, I think most users wouldn't have a need to just view a list of code reviews, without wanting to resume or end one. If the user does just want to check if any code reviews are in progress, they could always just run the resume command to see the list, then press escape to exit the list (and not proceed with resuming). If after the release I get feedback that indicates a list command would also be used, I'd be happy to add it in the following release.
> 
> This will be available in v1.22.0.
> 
> If you'd like to use it before the next release, you can download [v1.22.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.22.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

Sweet 👍
