### ISSUE TITLE
Git Graph does not show 1st and 2nd parents of a merge properly

### ISSUE THREAD

**Issue by cateyes99** [mhutchie/vscode-git-graph#235]
Look at the merge commit `9aaa3cd0e8c9d37c7752949033cd15a0510a292d`, its 1st parent is `4475ef291367590414e86f6dd599f318c2e14566`, and its 2nd parent is `6d910bbefabada2adc8def73eb9d159aa2c80505`. But **Git Graph** doesn't show the relationship properly in the graph, as a result `6d910bbefabada2adc8def73eb9d159aa2c80505` is shown in the 1st parent's position, and `4475ef291367590414e86f6dd599f318c2e14566` is shown in the 2nd parent's position.
![image](https://user-images.githubusercontent.com/19678455/71143101-3d6d0500-227e-11ea-8306-2f1f1b878448.png)

The below is the output from `git log`, see how it shows the 1st parent `4475ef29` & 2nd parent `6d910bbe` properly.
> λ git log --graph --date-order --oneline
```
* 55099353 Bug 16401: Sticky header line looks funny
*   44cdb9e4 (origin/master, origin/HEAD, master) Merged PR 12255: Quote Page Quick Wins
|\
| *   9aaa3cd0 Merge branch 'master' into working/cm_15819_quote-page-quick-wins
| |\
| |/
|/|
* | 6d910bbe Merged PR 12329: Fixed all Test Automation!
| *   4475ef29 Merge branch 'master' into working/cm_15819_quote-page-quick-wins
```

**Comment by mhutchie** [comment]
I think this is just a misunderstanding of how the lines is rendered in Git Graph. Every Git UI renders graphs slightly differently, and it appears Git Graph is just rendering the lines slightly differently to what you're expecting from git log. When designing the graph rendering algorithm I carefully considered the benefits and disadvantages of each behaviour, so although in the vast majority of behaviours are very familiar to other Git UI's, there can be some minor differences when considering any single other alternative Git UI.

The line of history (according to the first parent of a merge commit) shares the same colour across the merge commit. In your screenshot, the line of history through the merge commit is orange. It is not based on the left-to-right ordering of the lines extending below the merge commit.

The first parent of 9aaa3cd0 (4475ef29) is shown correctly in your screenshot because the orange line continues from the child of the merge commit, through the merge commit, and then to the first parent of the merge commit. 

The second parent of 9aaa3cd0 (6d910bbe) is also shown correctly in your screenshot, as the line connecting 9aaa3cd0 to the second parent is blue, because the second parent is on the blue line of history. In other words, the blue line of history is merging into 9aaa3cd0.

The reason that I chose to avoid enforcing the left-to-right constraint by leveraging colour, is that it reduces the number of columns required to represent the merge in the majority of cases. By forcing a left-to-right ordering, the line connecting the merge to its second parent in your git log output is forced to temporarily occupy a third column. Making the graph as compact horizontally as possible (while still being easy to interpret) is a significant benefit for reasonable to large sized repositories, and this has been communicated to me time-and-time again by significant volumes of Git Graph users. Based on user feedback, the majority of Git Graph users find the approach I have taken easy to interpret.

_Note: When I say "correctly" in this response, I'm mean that it is functioning as I designed and expect it to._

Please let me know if this response clarifies the current behaviour and the reasoning behind it, or if you have follow up questions.
