### ISSUE TITLE
Ctrl+P does not work on git graph history view

### ISSUE THREAD

**Issue by Zhan-Jie** [mhutchie/vscode-git-graph#238]
**Describe the Bug**
when there is only git graph view opened, I press Ctrl+P and the last closed file will be opened.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Open a project folder
2. Open a file
3. Open the 'Git Graph' view (git commit history) and close other files.
4. Press Ctrl + P. the command palette is not shown and the last closed file is opened

**Expected Behaviour**
The command palette will show up

**Environment**
 - Git Graph Extension Version: 1.20.0
 - Visual Studio Code Version: 1.41.1
 - Operating System: Deepin 15.11

**Screenshots (optional)**
Add any screenshots showing the bug.

**Additional Context (optional)**

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment]
The Command Palette is opened using `Ctrl + Shift + P` in Visual Studio Code by default, while `Ctrl + P` is quick open file.

Unless you have manually remapped these keystrokes, it sounds like you should by using `Ctrl + Shift + P`, instead of `Ctrl + P` to open the Command Palette.

The Git Graph View doesn’t block any of the Visual Studio Code keystrokes as they are processed independently of the extension by Visual Studio Code itself (the extension has absolutely no way of blocking them, and shouldn’t have). All the extension can do is add some new keystrokes that can be captured using front-end JavaScript while the Git Graph View has the focus. The Git Graph View uses a Visual Studio Code Webview, see more information about them [here](https://code.visualstudio.com/api/extension-guides/webview). Occasionally Visual Studio Code has a bug in how they process keystrokes while Webviews are opened, that affect all extensions that use Webviews on a specific operating system (this has happened numerous times before). If what I suggested in the previous paragraph did not apply to you, this is almost certainly what is causing you’re problem as I can’t replicate it on Windows or Mac. If this is the case, the issue you’re observing is not specific to Git Graph, it will be a bug with Visual Studio Code’s handling of keystrokes with Webviews that should be reporting to the vscode repository for them to fix.

I’ll close this for now as it almost certainly has nothing to do with Git Graph, however please let know if you find the contrary.
