### ISSUE TITLE
Ability to rearrange columns

### ISSUE THREAD

**Issue by duckyb** [mhutchie/vscode-git-graph#256]
Please allow the users to rearrange the columns in the preferred order.

After using this extension for a bit I wanted to have the graph centered on the screen and to have the commit messages on the left of it.
Unfortunately I was surprized to find out that it's not possible to rearrange the columns.

Other than that the extension is really awesome, keep up the good work 🍻 

![example](https://i.imgur.com/5eBD2ka.png)
(maybe also add optional right alignment?)

**Comment by mhutchie** [comment]
Thanks for the feedback, and raising this feature request!

Unfortunately, allowing the user to change the column order significantly complicates a lot of the rendering logic in Git Graph, although it is possible.

Additionally, it would have to override the users preference and force the Commit Details View to be “Docked to Bottom”, as if it was inline it would be impossible to arrange the Commit Details View content either side of the graph (which would be in an arbitrary position horizontally). This is definitely not ideal or something I’d want to do, and may confuse the user why the view is suddenly docked to the bottom instead of inline.

Considering that 280,000+ users are happy with the current column ordering, and you’re the first person that wants to re-order the columns, by using the current column ordering the rendering code has been kept much simpler, while still producing a UI that >99.9% of users are happy with.

Currently I don’t think enough users would utilise the ability to reorder the columns to warrant significantly complicating the rendering logic, and forcing the Commit Details View to be “Docked to Bottom”.

I’ll leave this feature request open for a while to see if a decent number of users would use this feature and be willing to accept having the Commit Details View “Docked to Bottom”. If enough interest is shown I would happily reconsider this feature and implement it.

**Comment by duckyb** [comment]
Yeah, of course I agree that the current column order is perfectly fine. It just seemed counter-intuitive that they couldn't be rearranged.

Looking at the _Commit Details View_ I see what you mean when you say that rearranging would break the current UI. That's unfortunate.

Anyway, thank you for replying and explaining the current situation. I will still keep using this awesome extension, and hope to maybe see this feature added some time in the future.

And to anyone else reading this, I encourage you to leave a like to the OP to show your interest in the feature. Thanks! 😄

**Comment by crcarlo** [comment]
I would love to be able to rearrange the column order.

My ideal order for columns would be this:

- Date (maybe less verbose)
- Author (maybe with an avatar)
- Graph
- Description
- (remove) Commit

One of the reasons, as @duckyb stated, is that the graph is so off from the center.

The main reason is that the content now is so much horizontally splitted that informations on the right are really hard to read and associate with the respective commit.

The commit hash, instead, only takes up space without providing any useful information (if I want to get the commit hash I would do it in some interactive way)

**Comment by mhutchie** [comment]
Hi @crcarlo, Thanks for your thoughts on this!

FYI: Are you aware that if you right click on the column headers you can already hide any of the date, author or commit hash columns?

**Comment by mhutchie** [comment]
This issue has been left open for 3 months for others to express interest in this feature. As only a few Git Graph users have indicated they would like this functionality in this period, it confirms my previous sentiment that the majority of users are happy with the current column ordering.

Although this functionality would definitely be nice to have, for the reasons I previously mentioned, I'll close it for now and move it to the backlog.

Note to users reading this in the future: If you'd like this functionality, please reply to this thread to express your interest. I'd happily re-consider, re-open and add this feature if there was any indication it would be used by a decent number of users.

**Comment by fadi-george** [comment]
I would be interested in this too, would be cool if I can move author column to the left graph column.

**Comment by aztack** [comment]
I prefer columns ordered like  `graph | commit | date | description | author`.
I think this order is more intuitive for me. The commit dot/circle in the graph column should be more associative with its commit SHA1. And most of the time I watch the graph is to reason the branching. The description next to the graph is a little bit noisy for me.

This is an example of my command line git graph:

<img src=https://user-images.githubusercontent.com/782871/150662775-a28f9e56-cec2-4537-812c-54fd91195880.png  width=300 />

Don't know why, it is hard for me to reason branching with the current vscode-git-graph column arrangement.
I usually open a terminal to show a git log like above image and use vscode-git-graph to checkout commit details.
If I can rearrange the columns order, I think I don't need to open that redundant terminal.

**Comment by bravecrayon** [comment]
FWIW, I too would like the commit as the second column. Feels more natural too see the commit first then message for me.
