### ISSUE TITLE
Failed to Install

### ISSUE THREAD

**Issue by aashish108** [mhutchie/vscode-git-graph#265]
Hi! I have been trying to install this but I get this error:

```Failed to install 'mhutchie.git-graph'.```

Not sure where to get detailed debug info?

**Environment**
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
Windows 10 Pro

Thanks!

**Comment by mhutchie** [comment]
Hi,

Git Graph requires Visual Studio Code to be at least version 1.31.0. From the information you’ve provided you only have 1.25.1 installed. Once you upgrade Visual Studio Code to at least version 1.31.0, or ideally the latest version, you will be able to install Git Graph.

Visual Studio Code used to provide a notification to indicate that the Visual Studio Code installation does not meet the requirements of the extension being installed.

Git Graph currently has a minimum Visual Studio Code version requirement (1.31.0), that was released 13 months ago. This requirement is necessary as it provides core capabilities that Git Graph uses in order to provide its rich user interface and integrations.

**Comment by sayauYusen** [comment]
Thank you for your reply. But I’d like to point out that this bug is not due to my Vscode version.
My current Vscode version is 1.36.0, and you mentioned in your email:

‘Git Graph requires Visual Studio Code to be at least version 1.31.0.’
Samuel Yau

**Comment by mhutchie** [comment]
The information you provided in your first comment was:

> **Environment**
Version: **1.25.1**
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: **2018-07-11T15:43:53.668Z**

This clearly indicates it was generated from Visual Studio Code 1.25.1, released in July 2018.

If this information is incorrect (and you are on Visual Studio Code 1.36.0), please provide the corrected set of environment information.

If you are still having an issue installing Git Graph, I believe you should be able to find out log information from one of Visual Studio Code’s Output Channel’s.
