### ISSUE TITLE
Add an option to show both `author date` and `commit date` at the same time

### ISSUE THREAD

**Issue by cateyes99** [mhutchie/vscode-git-graph#269]
@mhutchie Can you please make an option to show both `author date` and `commit date` at the same time? That be lovely, thanks. I have a commit:
```
* commit b3ddb2dc6ccdd338111205f2cee3bb204694ebbf (origin/Release_Branches/20-02-2020)
| Author:     Someone
| AuthorDate: Thu Feb 13 02:09:45 2020 +0000
| Commit:     Sometwo
| CommitDate: Wed Feb 19 13:27:17 2020 +1300
|
|     Merged PR 12850: increased callback limit from 1 to 3
|
|     Increased callback limit from 1 to 3
|
|     As agreed in meeting 31/1/2020
|
|     Related work items: #16897
```
In **Git Graph**, it shows either `author date` as `date` or `commit date` as `date` depending on the date type settings. Below is with the default setting - showing `author date`
![image](https://user-images.githubusercontent.com/19678455/75308260-ddfd2800-58b2-11ea-8824-e1be74c726e7.png)

**Comment by mhutchie** [comment]
This will be available in v1.22.0.

I've modified the Commit Details View such that:
* If the author date and commit date are the same, then just a single "Date: ..." is shown.
* Otherwise when the author date and commit date are different, "Author Date: ..." & "Commit Date: ..." are now shown.

I felt it was best to only show both dates if they are different to save repeating the same long formatted date twice.

If you'd like to use it before the next release, you can download [v1.22.0-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.22.0-beta.3), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
