### ISSUE TITLE
Open Visual Studio Code Diff View in a specific Editor Group

### ISSUE THREAD

**Issue by ackvf** [mhutchie/vscode-git-graph#277]
When quickly reviewing changes introduced in a commit, I would appreciate if the file diff view opened in a different tab group so that I can quickly see the changes of different files in the commit.

I would not mind if it was hardcoded to only support group1 and group2.

![image](https://user-images.githubusercontent.com/2313018/76202768-aae15f80-61f5-11ea-9d0f-e0553fe75ff6.png)

**Comment by mhutchie** [comment]
Hi @ackvf,

Git Graph already has the Extension Setting [Open Diff Tab Location](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#open-diff-tab-location), which when set to “Beside” will open the Visual Studio Code Diff View in a different tab group beside the active pane containing the Git Graph View.

I’ll close this issue as I believe the functionality you’re requesting is already available in Git Graph. Please let me know if I’ve misinterpreted your request and this is not the case, so I can re-open this feature request.

**Comment by ackvf** [comment]
I am sorry, I was mistakenly looking in different extensions settings. I have no idea how I could miss that. Thank you very much.

Anyway, the Beside option now always opens below instead. Can this be configured?

Even though I have two groups beside each other, it will still open third group below the active group.

**Comment by mhutchie** [comment]
The value that is set in the [Open Diff Tab Location](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#open-diff-tab-location) ("Active" or "Beside") is converted by Git Graph to the corresponding [ViewColumn](https://code.visualstudio.com/api/references/vscode-api#ViewColumn), which is provided as part of the [TextDocumentShowOptions](https://code.visualstudio.com/api/references/vscode-api#TextDocumentShowOptions) passed as an argument to the [vscode.diff](https://code.visualstudio.com/api/references/commands) built-in command for opening the Visual Studio Code Diff View.

For me, when I have just a single active editor group open (with the Git Graph View visible), and have "Open Diff Tab Location" set to `Beside`, Visual Studio Code does open the Diff View beside (to the right) of the Git Graph View as expected.

For some reason, Visual Studio Code's logic for handling the "Beside" `ViewColumn` (in your scenario with four editor groups open) must be causing it to open below instead of beside. Unfortunately Git Graph is simply just providing the `Active` or `Beside` `ViewColumn` as an argument to Visual Studio Code's logic for displaying the view (I have no control over what goes on internally in Visual Studio Code after I pass the `ViewColumn` to the `vscode.diff` command).

I'll look into whether if I expand the Git Graph Extension Setting [Open Diff Tab Location](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#open-diff-tab-location) to include the other `ViewColumn` options (`One` through `Nine`), this may give you more control over where the Diff View is opened when you have many editor groups open (as is the case for you). If this does turn out to be useful based on my testing, I'll re-open this feature request and include the additional options in an upcoming release of Git Graph.

**Comment by mhutchie** [comment]
After investigating the other `ViewColumn` options (`One` through `Nine`), I've found they work perfectly for controlling which Editor Group the Visual Studio Code Diff View is opened in from Git Graph. The numbering corresponds to "Group `n`" in the "Explorer" > "Open Editors" View. This should work perfectly for the scenario you provided (when you have four editor groups open).

I'll have this available for you to use by the end of this weekend.

**Comment by mhutchie** [comment]
This will be available in v1.23.0.

If you'd like to use it before the next release, you can download [v1.23.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.23.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by ackvf** [comment]
Amazing! Thank you very much

**Comment by ackvf** [comment]
I think I found a lead

```
  "workbench.editor.openSideBySideDirection": "down",
  "workbench.editor.splitSizing": "split",
```
