### ISSUE TITLE
When a branch is deleted on origin, origin branch persists on Graph

### ISSUE THREAD

**Issue by andpeterson** [mhutchie/vscode-git-graph#278]
**Describe the Bug**
When a a branch is deleted on origin (for example a squash merge) the origin branch remains on the Graph, making it seem as though it still exists.

**Steps to Reproduce**
1. Create a branch off of master
1. Create a commit on the branch
1. Push changes with the default settings (Set Upstream: true, Push Mode: Normal I assume)
1. Create Pull Request on GitHub
1. Squash, merge, and delete branch on GitHub
1. Go back to VSCode Git Graph
1. Fetch changes from Origin
1. Observe as origin label remains on branch 

**Expected Behaviour**
The origin label should be removed from the branch as the branch no longer exists on origin

**Environment**
 - Git Graph Extension Version: [e.g. 1.21.0]
 - Visual Studio Code Version: [e.g. 1.43.0]
 - Operating System: [MacOS 10.15.3]

**Screenshots (optional)**
Screenshot was taken after following steps provided above in branch tmp-test, except branch was just deleted rather than getting merged in
![image](https://user-images.githubusercontent.com/13080580/76663524-7c89ba00-653e-11ea-9b79-c9e917ee36cf.png)

I noticed this is similar to #115, given this was closed with a merged PR I'm opening a new issue.
Upon reading closer the issue above is about deleting local branches that are already deleted on remote.

**Comment by mhutchie** [comment]
Hi @andpeterson,

When you use the "Fetch" button in the Git Graph View, it only does a fetch `git fetch --all` (it doesn't prune any origin branches that no longer exist on the remote.

However, you if your were to enable the [Fetch And Prune](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#fetch-and-prune) Extension Setting, the "Fetch" button becomes a "Fetch & Prune" button. One you have enabled this, in your Step 7 Git Graph will delete the origin branch if it is deleted on origin as you are expecting & requesting. Instead of `git fetch --all`, it will run `git fetch --all --prune`.

I'm closing this issue as I believe you just haven't enabled the [Fetch And Prune](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#fetch-and-prune) Extension Setting, which (I believe) provides exactly what you're wanting. Please let me know if after you've enabled the setting & repeat your steps Git Graph is still not acting as you expect, so I can re-op this issue.
