### ISSUE TITLE
Dark dropdown text in GitHub sharp theme

### ISSUE THREAD

**Issue by Yukaii** [mhutchie/vscode-git-graph#28]
**Describe the bug**

As this screenshot show, the branch dropdown is totally dark in [GitHub sharp theme](https://github.com/joaomoreno/github-sharp-theme).

![Screen Shot 2019-03-12 at 3 46 11 PM](https://user-images.githubusercontent.com/4230968/54183080-2a9ef600-44de-11e9-8b24-26f405080225.png)

**What does the bug relate to**
List the area(s) this issue relates to, for example:
- Graph Rendering

**Expected behaviour**

**Environment**
 - OS: macOS High Sierra
 - Visual Studio Code Version: 1.32.1

**Screenshots (optional)**

![Screen Shot 2019-03-12 at 3 46 11 PM](https://user-images.githubusercontent.com/4230968/54183080-2a9ef600-44de-11e9-8b24-26f405080225.png)

**Comment by mhutchie** [comment]
Thanks for finding this! I found that I was not overriding the editor text colour `--vscode-editor-foreground` with `--vscode-menu-foreground` for the new dropdown menus and dialogs, when those elements use the background colour `--vscode-menu-background`. This is only an issue when `--vscode-editor-foreground` and `--vscode-menu-foreground` differ, which occurs in the GitHub Sharp Theme as menus and the editor have opposite colouring, but is not the case for most common themes.

This is fixed in [v1.4.3-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.3-beta.0), which can be downloaded and installed following the instructions provided on [Downloading & Installing Releases](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
