### ISSUE TITLE
User Experience: Clearer visual marker of "this branch is checked out"

### ISSUE THREAD

**Issue by nicain** [mhutchie/vscode-git-graph#290]
Currently there is an unfilled dot, same as the branch color, in front of the branch name and at the end of the pipe that visually signifies the currently checked out branch (and bold, but the font doesnt pop much).  When switching between repos and tabs, this identification is hard to see! 

Would it be possible to use something more visually salient to mark the current branch? Either a bigger marker, a different font choice that makes bold really stand out, or a thicker pipe?  Or a  bigger dot, instead of an empty dot? Something else?

(BTW fantastic work, this extension is vital to my workflow!  I recommend it to every code I talk to)

**Comment by mhutchie** [comment]
Thanks for raising this improvement request, and your kind feedback on the extension!

I definitely understand the need to make the checked out branch as noticeable / obvious to the user as possible. I’ve already explored this in depth to come up with the current behaviours, and ruled out many alternative options based on extensive testing and user feedback.

Here is a summary of the previous conclusions I’ve made on the four options you proposed:
* A bigger marker: The size of the marker on the graph, and in the Description column next to the checked out branch label, should be the same for consistency. The marker in the graph is already as large as can be (any bigger looked weird in several common branching scenarios based on user feedback I received).
* A different font choice: The current font is based on the Visual Studio Code Theme font, which differs by default on each operating system, and the user can also override it with a theme from the extension marketplace or their own preferred font. This meant finding a font that worked alongside multiple other fonts, that stood out, but also didn’t look too out-of-place, was impossible (I tried heaps of available fonts).
* A thicker pipe: This was previously proposed, and has the same implementation challenges as #270. If #270 is implemented in the future, this could definitely be a possibility (in which case I’d open an improvement request specifically for this change).
* Bigger dot instead of empty: The feedback I received indicated that the increased contrast of using empty dot make it significantly more noticeable than any feasible increase in diameter.

If other users have suggestions, I’d be more than happy to consider / implement them if they reply to this thread. I’m always open to improving the representation of the current branch, or any other feature in Git Graph for that matter.

I’ll close this request for now though as I’ve already put a great deal of thought, work, testing & user feedback into this (and objectively ruled out what I think to be most, if not all, other options for a specific reason).
