### ISSUE TITLE
Create Archive

### ISSUE THREAD

**Issue by ACheshirov** [mhutchie/vscode-git-graph#292]
**Describe the feature that you'd like**
It would be very nice if there is an "extract a commit" functionality.
For example, a new option (called Extract this commit...) in the right-click context of a commit. 
Extracting commit may be a .zip file and it should keeping directory structure.

This would be very useful for people who need to upload the latest changes on an FTP server.

**Additional context (optional)**
![image](https://user-images.githubusercontent.com/25287575/79142950-0094c300-7dc5-11ea-959d-aa28b19e4fc8.png)

**Comment by mhutchie** [comment]
Thanks for raising this feature request!

This is something that I’ve been wanting to implement for some time, but there hadn’t been enough interest from the community to do so until now. This feature will be included in an upcoming release.

**Comment by mhutchie** [comment]
I decided to provide the new "Create Archive" action from any branch or tag context menu for now, instead of the commit context menu. This was due to the following reasons:
* Creating an archive for deployment is semantically quite similar to pushing a branch or tag, so it makes sense that these actions are on the same context menus.
* The feedback I got from a variety of users was that they would most frequently create an archive from a branch or tag anyway (they would rarely create an archive from some commit not referenced by a branch or tag).
* The commit context menu is already getting quite large, and is close to overflowing the available screen height on lower resolution displays (e.g. laptops). The branch and tag menus having far fewer items in them.
* The low percentage of users that have expressed that they would use this feature.

I'll monitor feedback on this new functionality after it is released, and I would be happy to reconsider the "Create Archive" placement on the commit context menu if enough users indicate they would prefer and commonly use it.

This will be available in v1.23.0.

If you'd like to use it before the next release, you can download [v1.23.0-beta.4](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.23.0-beta.4), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
