### ISSUE TITLE
Pull when checking out remote branch 

### ISSUE THREAD

**Issue by luisherranz** [mhutchie/vscode-git-graph#297]
**Describe the improvement that you'd like**
When you checkout a remote branch and there is an existing local branch, GitGraph asks you if you want to "Checkout the existing branch". 

If you want to checkout the existing local branch, you can click on that branch, not on the remote.

So a much more nice behavior for checking out a remote branch would be to change that to "Checkout the existing branch and pull changes".

<img width="381" alt="Screen Shot 2020-04-24 at 08 51 22" src="https://user-images.githubusercontent.com/3305402/80183268-cfa85f80-8608-11ea-883f-df43b461d93d.png">

**Comment by mhutchie** [comment]
Thanks for raising this feature request! This would definitely be a nice improvement, and would streamline this use case.

Typically I've tried to avoid combining different categories of git commands under the same action (that's why checkout and pull are separate actions). However, given this dialog only occurs under a very specific scenario, and if the user was to choose "Check out the existing branch" they would almost certainly want to pull it immediately afterwards, I think it makes sense to make an exception for this improvement.

**Comment by luisherranz** [comment]
Awesome, glad to hear that 🙂

**Comment by mhutchie** [comment]
This will be available in v1.24.0.

If you'd like to use it before the next release, you can download [v1.24.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.24.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
