### ISSUE TITLE
Navigation between commits of a particular branch

### ISSUE THREAD

**Issue by plohoj** [mhutchie/vscode-git-graph#299]
**Describe the feature that you'd like**
It would be nice to be able to navigate between commits of a particular branch. That is, the use of the `up / down` buttons in combination with, for example, `Ctrl`.

**Additional context (optional)**
![image (2)](https://user-images.githubusercontent.com/10156573/80183392-709b1880-8611-11ea-82fd-8a5494a5c3e5.png)

**Comment by mhutchie** [comment]
Thanks for raising this feature request! This would be awesome to have in Git Graph & really useful for many users!

**Comment by mhutchie** [comment]
This will be available in v1.23.0, which will be released in the next day.

**Comment by mhutchie** [comment]
Git Graph v1.23.0 will be released this weekend instead of last weekend as I had previously intended.

If you'd like to use it before the next release, you can download [v1.23.0-beta.5](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.23.0-beta.5), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
