### ISSUE TITLE
Adopt VS Code's 'asWebviewUri' API

### ISSUE THREAD

**Issue by mjbvz** [mhutchie/vscode-git-graph#305]
Hi, I maintain VS Code's Webview API

## Issue
Our telemetry suggests that your extension uses webviews and may be loading resources in these webviews using hardcoded `vscode-resource:` URIs. These URIs have some important limitations and don't work properly when VS Code is run in a browser. We are also making changes in the desktop version of VS Code that may cause these URIs to not work properly in future versions of VS Code.

While we are making our best effort to continue support existing webview extensions that use `vscode-resource:` URIs on desktop versions of VS Code, we will not able to fully support all uses cases.

## Fix
To ensure that your extension continues to work in as many environments as possible—including on web and remotely—please:

- Switch to use the [`Webview.asWebviewUri` function](https://github.com/microsoft/vscode/blob/307cb32f306a527a30a5b1756e8bf548c141192c/src/vs/vscode.d.ts#L6703) for loading resources.

- Switch to use the [`Webview.cspSource` property](https://github.com/microsoft/vscode/blob/307cb32f306a527a30a5b1756e8bf548c141192c/src/vs/vscode.d.ts#L6714) in content security policies.

These APIs shipped around 2 years ago so they should be available in all modern versions of VS Code. You can find additional information about the issue here: https://github.com/microsoft/vscode/issues/97962

Let me know if you have any questions about this change

**Comment by mhutchie** [comment]
Thanks for reaching out about this!

I've been trying to manage when it would be best to increase the minimum version requirement of the extension, and I've been aware of the limitations of `vscode-resource`, and its replacement `asWebviewUri` since it was first released. As indicated by the Visual Studio Code release notes [here](https://code.visualstudio.com/updates/v1_38#_webviewaswebviewuri-and-webviewcspsource), and the `vscode.d.ts` typings, `asWebviewUri` was only introduced in Visual Studio Code 1.38.0 August 2019 (10 months ago), not two years ago as you mentioned.

Up until recently there was minimal benefit to upgrade the minimum version requirement of the extension to support `asWebviewUri`, as the current method still worked, and from the information I've received a relatively small number of users indicate they use Visual Studio Code in a web browser. I held off the upgrade as any users that use an older version of Visual Studio Code would no longer be able to receive updates to Git Graph.

As you've indicated that `vscode-resource` is reaching its EOL, I'll definitely migrate Git Graph to use `asWebviewUri` in the next available release. I intend this to be available in around a months time, as its too late to make Git Graph 1.23.0 which I'm intending to release this weekend.

**Comment by mjbvz** [comment]
Yes I guess it's still 2020  :)

A very high percentage of users are either on the current VS Code release or one version back so you generally don't have to worry very much about breaking users by updating the minimum VS Code version. We on VS Code only support the current release

**Comment by mhutchie** [comment]
Thank you, it’s really useful to know that a high percentage of Visual Studio Code users are using the current release or one version back!

**Comment by mhutchie** [comment]
@mjbvz It looks like the latest vscode insiders build requires `asWebviewUri` to be used, no users of Git Graph can use the extension anymore.

Is there any way for you to revert this change to extend support for the old `vscode-resource:` method (which was only released 10 months ago)?

I can ship a release of Git Graph if it is non-negotiable in the next few days.

**Comment by mjbvz** [comment]
@mhutchie The current insiders build is using the old `vscode-resource` scheme so I don't think this is related. Taking a look now

**Comment by mjbvz** [comment]
Should be fixed by https://github.com/microsoft/vscode/commit/8e45a2f4b58a9b4a38e410c5dee7f2b533b47c07

**Comment by mhutchie** [comment]
Thanks @mjbvz for fixing this so quickly. I'll let the Git Graph users know that it should be fixed in one of the next insiders build.

**Comment by mhutchie** [comment]
This will be available in v1.24.0.

If you'd like to use it before the next release, you can download [v1.24.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.24.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by mhutchie** [comment]
Hi @mjbvz,

After making the changes you mentioned with `asWebviewUri` & `cspSource` in [this commit](https://github.com/mhutchie/vscode-git-graph/commit/faa39deadc5694fc550cf6bd10f32b3d93f577a3#diff-e634215f94d94e43f8af635df5c76e3f), I've been attempting to test the extension in Google Chrome with Visual Studio Code running in a Codespace. After installing [v1.24.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.24.0-beta.2), the first pre-release with these changes, and opening the Git Graph View in a Git repository, I get the following CSP violation errors that prevent the Webview's CSS & JS from loading:

![image](https://user-images.githubusercontent.com/5315753/83966053-584e3700-a8fb-11ea-83ae-ce6d8824b1d6.png)

The rendered CSP element:
```
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src https://*.vscode-webview-test.com/5763d909d5f12fe19f215cbfdd29a91c0fa9208a 'unsafe-inline'; script-src https://*.vscode-webview-test.com/5763d909d5f12fe19f215cbfdd29a91c0fa9208a 'nonce-sjxcEyDFVCIX6xKWNIpZ6PCdEkjjB7Rp'; img-src data:;">
```
blocks the following styles & scripts:
```
<link rel="stylesheet" type="text/css" href="https://cad27183-3a94-4b14-b661-bca38f486a4b.vscode-webview-test.com/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/vscode-resource/file///home/vsonline/.vscode-remote/extensions/mhutchie.git-graph-1.24.0-beta.2/media/out.min.css">
```
```
<script src="https://cad27183-3a94-4b14-b661-bca38f486a4b.vscode-webview-test.com/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/vscode-resource/file///home/vsonline/.vscode-remote/extensions/mhutchie.git-graph-1.24.0-beta.2/media/out.min.js"></script>
```

It seems that because `cspSource` includes a path component in the URI, it is being blocked. 

Another extension that also uses a Webview is having the same issue.

What do I need to do to get this working?

**Comment by mhutchie** [comment]
@mjbvz, I’d appreciate it if you were able to respond to my questions regarding `cspSource`, or let me know when you’ll be able to look into this. _(I’ve edited them based on the findings I’ve made since my initial reply.)_

I’m needing to have browser support (including Microsoft Codespaces) in Git Graph 1.24.0, and this is the last deliverable holding back the release.
