### ISSUE TITLE
File extension specific icons in the Commit Details View

### ISSUE THREAD

**Issue by vigneshwaran-natarajan** [mhutchie/vscode-git-graph#307]
Currently in the detailed commit view, only the files names are visible with a greyed out icons, it would be better if it shows appropriate file icons with respect to the file type.

![image](https://user-images.githubusercontent.com/16484526/82584637-663d5180-9bb2-11ea-9739-d03273b7da6a.png)

(I looked for the options, but didn't find any thing, if there is any settings to enable the file icons please point me out)

**Comment by mhutchie** [comment]
Thanks for raising this improvement request, it would definitely be nice to have icons specific to each files extension!

When I first implemented the file icon in the Commit Details View, I considered file extension specific icons, however at the time I decided against it as there are *so* many files extensions (requiring a large library of icons), and it offers limited value to the user. It also opens up the possibility for many users to raise feature / improvement requests to have an icon added for some niche file extension they use (the possibilities are almost infinite). There wasn’t a good library at the time that I could leverage for the icons, and creating my own library would take too much time for the value it would add.

I’ll have a look to see if there now exists a feasible icon library for achieving this, as I haven’t re-searched for it since I first implemented the current file icon over a year ago.

**Comment by mhutchie** [comment]
I've looked into various icon libraries that could be used for file extension specific icons in the Commit Details View, there now appears to be several viable options. It has also highlighted to me that the only practical approach would be to package an icon library with the extension, as numerous libraries have over 800 file extensions supported (it would be wasted time & effort to create an extension specific library).

The main hesitation I have with proceeding with adding a dependency on an icon library is that:
* It would almost double the packaged size of the extension. This has the side-effect that it would make the Git Graph View slower to open.
* No other Git Graph users have expressed similar interest in this functionality in the 3.5 weeks this improvement request has been open (nor in the 16 months Git Graph has been released). This indicates to me that at the present time, not many users would value this improvement.

For these reasons, I'll close this improvement request for now and move it to the backlog.

Note to users reading this in the future: If you'd like this functionality, please reply to this thread to express your interest. I'd happily reconsider this improvement if there was any indication a decent number of users would value it.
