### ISSUE TITLE
Display submodule commit hash in diff view

### ISSUE THREAD

**Issue by maltejoos** [mhutchie/vscode-git-graph#308]
When comparing two commits containing an update in a submodule, the diff overview shows a link to open this submodule.
However, it would be nice to see the change of the commit hash of this subsystem. Same output as the standard git diff command provides.

As the submodule is displayed in the diff view you can recognize that it was updated, but you have no chance to figure out what the update is.

**Comment by mhutchie** [comment]
Hi @maltejoos, Thanks for raising this improvement request, and I definitely understand the benefits of what you’re proposing!

Originally Git Graph didn’t display a link to the submodule(s) in the Commit Details / Comparison View, and instead displayed the submodule changes (as you’re requesting). I decided to implement the current behaviour instead, as:
* I found numerous inconsistencies in Git’s reporting of submodule changes across all of the Git commands the extension runs (`git diff` is just one of them). Git Graph users would find these inconsistencies confusing, and think it was a bug in Git Graph when it was actually just reporting the output of the underlying Git commands.
* There are numerous complexities and subtleties in the handling of submodule changes (including but not limited to: when Git Graph shows the changes in the Visual Studio Code Diff View, opens the file in the editor, or when viewing a file at a revision). I found that properly handling all these features with submodules changes were either infeasible, borderline impossible, or would significantly increase the codes complexity.

Due to these inconsistencies & complexities, and that I found only a small portion of users even use Git submodules, it became infeasible to fully support submodule changes in the Commit Details / Comparison View. I decided that I would just implement the submodule links instead, as it offered a consistent, simple, and easy to understand experience to users (and it was suggested by a user, and liked by other users who I sought feedback from).

I’ll close this improvement request for now for the above reasoning, and move it to the backlog. If in the future a significant number of users express that they would like this functionality, I’d be happy to reopen this request and re-evaluate implementing the highly complex solution I mentioned above.

**Comment by offirpeer** [comment]
@mhutchie  Any change there was some kind of progress with that issue?

**Comment by tolisaverkios** [comment]
I'd also be interested in this feature! Currently when I click on the link on the commit view, Git Graph takes me to the submodule and points to the commit that I updated the submodule to point to. But it would be good if we could see the git diff.

I don't know what the bug is with git diff, I haven't seen issues when doing git diff to see the submodule revision update.

I know dozens of ppl who use git submodules, and I believe that there are too many who use it but won't visit this github page, or won't create a ticket, because there are already some :) e.g. I saw this ticket (https://github.com/mhutchie/vscode-git-graph/issues/352)

Personally, current Git graph provides everything I need with git submodules. This "git diff" on submodules in the commit view, is the only thing I'd like the extension to support :)

**Comment by isaacn-lab** [comment]
Hello, looking forward to this feature too!

**Comment by dongshimou** [comment]
need this feature.

**Comment by bobatsar** [comment]
Hey @mhutchie I am also looking for this feature as it is currently not possible to show at which commit the submodule is.

Another possible way to implement would be, to jump to the submodule graph but select the commit which is referenced from the parent git.

**Comment by pewscorner** [comment]
@mhutchie I think you may have misunderstood the original feature request. It was simply about getting access to the 2 hashes for the diff'ed submodule - not the full diff for the contents of the submodule (although that would of course be wonderful). Right now the provided submodule link is pretty useless on its own, so I have to manually run git diff on the submodule file to get the 2 hashes (which I can then find and diff inside the submodule in Git Graph).

Providing an option to see the diff of the submodule file (not the submodule contents) should be quite uncomplicated and would be a big help.

**Comment by avery0010** [comment]
Hello, I would like to know if there is a function to know the commit id of the current submodule?

**Comment by GoofyPy** [comment]
I would also really like to have this feature! Git extensions has it and it is just super convenient @mhutchie

**Comment by avery0010** [comment]
已收到。

**Comment by evidals** [comment]
this feature would really helpfull, others have it like sourcetree or gittortoise.
