### ISSUE TITLE
CMD/CTRL+click on filename to open it

### ISSUE THREAD

**Issue by niccolomineo** [mhutchie/vscode-git-graph#315]
The current default behaviour of clicking on a filename is to open a diff view. I think it could be useful to add a CMD/CTRL+click behaviour to actually open that file only. In a way, this behaviour would seem to me more VSCode-y than clicking on the icon.

**Comment by mhutchie** [comment]
Hi @niccolomineo,

I've designed the current file tree / list in the Commit Details View to be exactly consistent with Visual Studio Codes Git Extensions Source Control View, where clicking on the files record views the diff, and extra actions are shown to the right (e.g. opening the file). It is done this way because the conditions for whether or not the user can view the diff of a file are different from the conditions for whether or not the user can open the file. This allows the actions availability to be indicated in the UI (between visibility of the button & type of cursor). If a CTRL/CMD click option was added, there wouldn't be a way to visually indicate whether it is available to the user.

Additionally, the Visual Studio Code Git Extensions Source Control View uses CTRL/CMD click on file records to allow the user to select multiple files, and perform an action on all of these files. It is something that I've been considering implementing for the Git Graph Commit Details View as it would allow a variety of useful new functionality.

For all of these reasons, (although primarily that the current Commit Details View is purposely already exactly consistent with the Visual Studio Code Git Extensions Source Control View), that I'll close this feature request.
