### ISSUE TITLE
Colorblind-friendly Commit Details View

### ISSUE THREAD

**Issue by nsanchob** [mhutchie/vscode-git-graph#319]
The information of what happened with each file (Added, Deleted, Modified, Renamed, ...) is currently color-coded in the Commit Details View. It is also shown on hover over each file.

It would be nice to also have that information in plain sight as an additional column in that view.

I don't mind too much if the column has full words ("Added"), single letters ("A"), or icons ("+"), as long as I can glance that information.

**Comment by mhutchie** [comment]
Hi @nsanchob,

Thanks for raising your concerns for the usability of the Commit Details View for users who are colour-blind! I definitely want Git Graph to be accessible to all users.

I originally considered including letters A/M/D/R/U versus using colour (in addition to the existing tooltips). I figured that because the extension uses the colours defined by the Visual Studio Code Color Theme specified by the user for added / modified / deleted, colour-blind users would simply adjust those colours to any colours they can effectively differentiate. That way added, modified and deleted indicators throughout the Visual Studio Code product would be tailored and identifiable to the user.

The downside of adding an extra indicator like A/M/D/R/U or +/-, is that for most users it is redundant and just overloads the user (as each record in the Commit Details View would have a symbol, text, letter, additions/deletions and buttons).

\*\*\* As you indicate that the current approach is insufficient, I definitely want to address it. Do you think that adding a new Git Graph Extension Setting for “Enhanced Accessibility” would work for you?
* When the setting is enabled, Git Graph could add A/M/D/R/U indicators in the Commit Details View. It could also be extended in the future for other accessibility enhancements, that may be beneficial to anyone that needs them, without impacting the majority of users.

**Comment by nsanchob** [comment]
Hi @mhutchie 

Thank you for your response (that was quick!)

Yes, a setting would work. I don't want to force my requirements to the majority of the users. :)

I, for one, don't usually tune colours in tools except for extreme cases (e.g.: unreadable) because not all tools nor all extensions allow or respect it, and it is quite difficult for me to find a combination that is both distinguishable and meaningful. So I usually end up with the defaults, and relying in other visual clues. Other colorblind people's mileage may vary, so don't take my words as the generality.

It doesn't even have to be an additional column; it can be appended at the end of the filename like the currently existing "(+2 | -1)" indicators. I guess this can be easier to code.

Thanks!!

**Comment by mhutchie** [comment]
Thanks for your response!

I’ll add the setting in the next release, and have a beta release you can use available in the next few hours.

Also thanks for your insight into preferring visual indicators rather than customising colour themes. It’s really useful to know that, and I’ll be mindful of it in the future, not just Git Graph, but all future software I produce.

**Comment by mhutchie** [comment]
This will be available in v1.24.0.

If you'd like to use it before the next release, you can download [v1.24.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.24.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by nsanchob** [comment]
Downloaded and installed! Thank you very much :D !!!
