### ISSUE TITLE
Extension Setting to set the order of repositories in the repository dropdown

### ISSUE THREAD

**Issue by cateyes99** [mhutchie/vscode-git-graph#321]
**Describe the improvement that you'd like**
Git Graph has a nice handy feature that it has a repo list to show multiple repositories in the subfolders. Currently it doesn't show the repositories in the alphabetic order (_seems it shows in the order of the repositories being detected in the subfolders_, see the below screenshot). It'd be useful to have a flag so i can instruct Git Graph to show detected multiple repositories in the alphabetic order instead _**:)**_. It's easy for the user to spot the desired ones when there is a long repository list like in my case, as it's hard to remember the location order of the repository subfolders.

**Additional context (optional)**
Here the **Rating.Api** repo is on the top of the list above the **BT.API.Read** repo, becaues the **Rating.Api** repo is located in the 1st subfolder, & the **BT.API.Read** repo in the 2nd subfolder etc.
![image](https://user-images.githubusercontent.com/19678455/84838163-c9c17e80-b08d-11ea-9f20-45bee770fbe2.png)

**Comment by mhutchie** [comment]
Hi @cateyes99, Thanks for raising this improvement request!

Currently the repositories are sorted alphabetically on their entire path, so they appear in the same order as they appear in the Visual Studio Code Explorer Tree. _(As you thought)_

I can definitely see how in some workspaces, like the one shown in your example, this may not be as easy to use as sorting the repositories alphabetically based on only their name (instead of the entire path).

I'll add an extension setting to allow users to choose their preferred ordering of repositories.

**Comment by mhutchie** [comment]
This will be available in v1.25.0.

If you'd like to use it before the next release, you can download [v1.25.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.25.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
