### ISSUE TITLE
Rebase Remote branch

### ISSUE THREAD

**Issue by firattaskin** [mhutchie/vscode-git-graph#329]
After 1.25.0-beta.0 i can merge remote branches without checkout them. But i cant rebase remote braches without checkout still.

**Comment by mhutchie** [comment]
Hi @firattaskin,

I don’t think it’s appropriate to provide a method of rebasing on remote-tracking branches directly, due to the history rewriting nature of the rebase command. I think it’s best to only provide the capability of rebasing on local branches and commits. After getting feedback from a variety of other Git Graph users, they share a similar opinion.

Note to other users reading this in the future: If you'd like this functionality, please reply to this thread to express your interest. I'd happily re-consider this feature if a decent number of users would regularly use it.
