### ISSUE TITLE
Permission denied on push

### ISSUE THREAD

**Issue by elementalPRESS** [mhutchie/vscode-git-graph#332]
Since a while it is not possible to push data to local git repro. The log writes:

_Please make sure you have the correct access rights
and the repository exists.
> git push origin v3-rc4:v3-rc4
Permission denied, please try again.
Permission denied, please try again.
xxxx@yyyy: Permission denied (publickey,password).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists._

The strange thing is that it works with program like "fork" (MacOS), which is using .gitconfig too. So it is not a wrong config.

The push operation is configured with ssh (HTTPS/HTTP are not allowed on my server).

**Environment**
 - Git Graph Extension Version: 1.24.0
 - Visual Studio Code Version: 1.46.1
 - Operating System: MacOS Catalina 10.15.5

Pls help! Thx!

**Comment by mhutchie** [comment]
Hi @elementalPRESS,

Could you please describe what occurs when you run the same git command in the Visual Studio Code Terminal `git push origin v3-rc4:v3-rc4`? What is the output, are any prompts shown etc.

Likely you will need to accept a key (or similar). After completing the push successfully (via the `git push` command above), please try again using the push branch action in Git Graph and report whether the action ran successfully or the error message in the dialog.

**Comment by elementalPRESS** [comment]
> git push origin v3-rc4:v3-rc4

Hi Michael,

thx for the fast response. When I'm doing `git push origin v3-rc4:v3-rc4` I get a password request and after entering the password the push process starts.

I followed your instructions and did a push in Git Graph after the manual push. Unfortunately, I get the same error "permission denied"

**Comment by mhutchie** [comment]
Hi @elementalPRESS,

Git Graph (like all Node.js applications - including Visual Studio Code itself) has to spawn all `git` commands using the Node.js Child Process Module. As it runs the command as a child process, and not in a terminal, `git` will still try to request the password from the user. For some Git authentication methods (like Askpass), Git Graph can intercept these requests and pass them onto the user, and provide the users response them back to Git. However Git requests the SSH Key Password via another mechanism, such that there is no method available in Node.js that allows this to be intercepted and passed onto to the user. Another user had previously brought this to my attention - at the time there was no known solution I could find, and nor has anyone else provided one since (which I requested in the previous issue if anyone was aware of a work-around). Unfortunately it's still my belief that this is just not possible for Git Graph or Visual Studio Code, as they are both based on Node.js (and there's no other alternative).

You should be able to observe the same error message if you run the "Git: Push" command in the Visual Studio Code Command Palette, as Visual Studio Code's Git Extension also has the same limitations.

There are a variety of other platform specific methods that you can find on Google to avoid Git needing to use the SSH Key Password prompt (e.g. not using a password with the SSH Key, or caching etc.). I'd suggest that you use one of the methods, that way both Visual Studio Code and Git Graph can push branches.

---

Like the previous issue, if you're another user reading this in the future and are aware of a work around, please let me know. I'm definitely keen to fix the current behaviour, however there just doesn't appear to be a feasible solution.

**Comment by elementalPRESS** [comment]
Thx for the complete answer.

**Comment by Diogo-Rossi** [comment]
> Hi @elementalPRESS,
> 
> Git Graph (like all Node.js applications - including Visual Studio Code itself) has to spawn all `git` commands using the Node.js Child Process Module. As it runs the command as a child process, and not in a terminal, `git` will still try to request the password from the user. For some Git authentication methods (like Askpass), Git Graph can intercept these requests and pass them onto the user, and provide the users response them back to Git. However Git requests the SSH Key Password via another mechanism, such that there is no method available in Node.js that allows this to be intercepted and passed onto to the user. Another user had previously brought this to my attention - at the time there was no known solution I could find, and nor has anyone else provided one since (which I requested in the previous issue if anyone was aware of a work-around). Unfortunately it's still my belief that this is just not possible for Git Graph or Visual Studio Code, as they are both based on Node.js (and there's no other alternative).
> 
> You should be able to observe the same error message if you run the "Git: Push" command in the Visual Studio Code Command Palette, as Visual Studio Code's Git Extension also has the same limitations.
> 
> There are a variety of other platform specific methods that you can find on Google to avoid Git needing to use the SSH Key Password prompt (e.g. not using a password with the SSH Key, or caching etc.). I'd suggest that you use one of the methods, that way both Visual Studio Code and Git Graph can push branches.
> 
> Like the previous issue, if you're another user reading this in the future and are aware of a work around, please let me know. I'm definitely keen to fix the current behaviour, however there just doesn't appear to be a feasible solution.

Thanks for the answer. I was looking for this.
