### ISSUE TITLE
sometimes it work, sometimes it doesnt

### ISSUE THREAD

**Issue by ctf0** [mhutchie/vscode-git-graph#334]
**Describe the Bug**
the graph doesn't always work, whether its a small/large public/private project, the graph have a mind of its own.

**Steps to Reproduce**
1. open https://github.com/ctf0/Laravel-Media-Manager in vscode
2. Click on  status bar git graph btn
3. see a white/blank page

**Expected Behavior**
the graph should work consistently

**Environment**
 - Git Graph Extension Version: 1.24.0
 - Visual Studio Code Version: 1.47.0-insider
 - Operating System: OSX 10.14.6

**Comment by mhutchie** [comment]
Microsoft currently has a bug in their recent Visual Studio Code Insiders releases that is causing the Git Graph View to not load. It affects all extensions that use [Webview's](https://code.visualstudio.com/api/extension-guides/webview), which includes the Git Graph View. More information is provided in the existing open issue #317.

Microsoft has also had a similar intermittent bug over the last few months that they recently resolved (aside from it not working at all in the latest Insiders builds).

I've raised this bug with Microsoft in [#101093](https://github.com/microsoft/vscode/issues/101093), and previously in [#100918](https://github.com/microsoft/vscode/issues/100918), and they are working to resolve this. Apologies for the inconvenience, I also hope it is resolved as soon as possible. Please monitor the #317 thread to get notified when this issue is fixed by Microsoft.

FYI: In the meantime you can use the standard Visual Studio Code as it is far more stable at the moment.
