### ISSUE TITLE
Publish on Open VSX

### ISSUE THREAD

**Issue by felipecrs** [mhutchie/vscode-git-graph#335]
So we can use it in Gitpod right away :-). The instructions are very straightforward: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by mhutchie** [comment]
Hi @felipecassiors, Thank you for raising this!

I already intended to do this in around a months time from now.

When I was implementing support for Git Graph in web browser environments (released 13 days ago in Git Graph 1.24.0), I ensured it was compatible with Microsoft's Visual Studio Codespaces (their official web-based platform for Visual Studio Code). This consequently meant the extension was now also compatible with being run the web browsers, including many third-party products.

In doing this, I also tested the extension in some third-party Visual Studio Code compatible products (including Gitpod). Unfortunately I found several bugs in these third-party products that affect some of the rich Visual Studio Code integrations that Git Graph uses. I decided I would give these providers some time to fix these issues while only a relatively small number of users manually install Git Graph. As soon as I publish to Open VSX, the number of Git Graph users on these third-party products will increase rapidly, so I don't want significant volumes of users all facing the same third-party caused bugs.

FYI: It is already a significant effort to both develop Git Graph, and provide support to users on Github (with feature requests, improvements, or issues they are having) - surprisingly it ends up that I split my time almost equally between these two components. While I'm more than happy to publish Git Graph so that it can be used on third-party products, and pleased it will be of value and used by even more users, I don't have much (if any) spare capacity to:
* Deal with an influx of bugs / issues that people would naturally assume to be in Git Graph, when they are in fact caused by the third-party product itself.
* Work with each of these third-parties to fix their products.

**Comment by mhutchie** [comment]
I've re-tested Git Graph with Gitpod, and unfortunately can still observe numerous bugs specific with their implementation of the Visual Studio Code API. These bugs affect some of the rich Visual Studio Code integrations that Git Graph uses.

I'll postpone publishing to Open VSX until either:
* Gitpod resolves these bugs.
* Another user replies to this thread indicating an alternative third-party product they use (which integrates with Open VSX), and I can verify the third-party product doesn't have any significant incompatibilities with the Visual Studio Code API.

**Comment by ruanmed** [comment]
Hi @mhutchie, I am a Git Graph user and I use [VSCodium](https://github.com/VSCodium/vscodium), which [recently migrated the extension gallery to Open VSX](https://github.com/VSCodium/vscodium/pull/404).

I had the extension installed before updating VSCodium to the version where Microsoft Marketplace was replaced by Open VSX, which means I kept using Git Graph without knowing it was not available in Open VSX. Today I had to reinstall some extensions  and Git Graph was one of them, and only now I found it it was not available to be installed quickly through VSCodium marketplace, so I had to manually install it, which is a pretty quick process too just with some extra steps, but that means I won't be getting the extension auto-updates.

So, just letting you know about VSCodium using Open VSX, and thank you for the amazing extension!

**Comment by mhutchie** [comment]
Hi @ruanmed,

It’s quite a coincidence that you commented this tonight!

I also recently noticed that VSCodium uses OpenVSX, so the last few days I’ve been trying to publish Git Graph to OpenVSX. I’ve been in discussion with the OpenVSX team, as when I went to publish Git Graph to OpenVSX, I found that another individual had decided to publish Git Graph to OpenVSX: (1) Without my knowledge,
(2) Ignoring this prominent thread outlining why I was temporarily holding off publishing to OpenVSX - for a well justified reason, (3) I was unable to verify that they hadn’t maliciously altered the extension they claimed was Git Graph 1.24.0, and (4) Breached the licence agreement of Git Graph.

The OpenVSX team has taken down the version that the other individual published, and made adjustments so that I’m now able to officially publish Git Graph to OpenVSX. Tomorrow morning (in around 12 hours time), I’ll be publishing the latest version of Git Graph to OpenVSX. After publishing Git Graph 1.25.0 to OpenVSX tomorrow, I’ll commence publishing each new version of Git Graph to OpenVSX a few days after each version is published to the Visual Studio Code Marketplace (the delay is just a buffer in case I need to address any critical bugs - extremely uncommon but possible).

**Comment by mhutchie** [comment]
I've now published Git Graph 1.25.0 to OpenVSX, and it is available to install.

However, currently because the previous version had to be taken down from OpenVSX (as it was not officially published - read my previous comment for background on this), any users who already had it installed will unfortunately not receive a notification to update the extension, as you normally would when a new version of an extension is published. I'm in contact with the OpenVSX to try to resolve this, so all users that had downloaded the Git Graph 1.24.0 on OpenVSX will automatically get notified that there is an update to Git Graph 1.25.0.

**Comment by mhutchie** [comment]
OpenVSX has now resolved the update notification issue, so all ~620 users who installed the unofficially published Git Graph release (1.24.0) via OpenVSX will get updates to the first official release of Git Graph (1.25.0) on OpenVSX.

However, the consequence of fixing it for the majority of users is that it meant that if you installed Git Graph 1.25.0 from OpenVSX between 11:00 29 Aug 2020 and 17:45 31 Aug 2020 (AEST), less than 40 users, you won't receive auto-updates unless you uninstall & re-install Git Graph. Apologies for the inconvenience if this affected you.
