### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by MSK61** [mhutchie/vscode-git-graph#339]
- Issue Type: `Bug`
- Extension Name: `git-graph`
- Extension Version: `1.24.0`
- OS Version: `Linux x64 5.6.19-300.fc32.x86_64`
- VSCode version: `1.46.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 8836,
		"activateCallTime": 15,
		"activateResolvedTime": 52,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "mhutchie.git-graph",
				"_lower": "mhutchie.git-graph"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by mhutchie** [comment]
Hi @MSK61,

As you’re reporting a bug, please provide enough information so I know what went wrong, when it occurred, and under what circumstances it occurred, so I have the ability to consistently replicate it. I have provided a Bug Issue template on GitHub so for this reason, in the future please use it.

From the small snippet of data you’ve included it appears that the extension was slow to start. Occasionally (extremely rarely - around 5 times in 16 months & over 500,000 users) I get a report that Git Graph was slow to start, however each time it has been a one-off occurrence attributed due to factors external to Git Graph (e.g. their computer was doing something in the background that affected the performance of all software running on it).

Could you please let me know if this was a one-off occurrence, or it regularly occurs for you? If it does occur regularly, is there anything unique about your computer / system setup that could feasibly be affecting the extensions performance (as there haven’t been any recent reports of other users finding Git Graph slow to start).

**Comment by MSK61** [comment]
Hi @mhutchie,
Thanks for your quick response. For gitGraph as a user I didn't notice any slowdown myself; it was VSCode that reported the slowness in a notification and even offered to create an issue on gitHub. I followed the template I was presented so I didn't create the format myself(and of course missed any templates you might have included for this).

That was a one-off occurrence so please feel free to ignore it.

**Comment by mhutchie** [comment]
Hi @MSK61,

Thanks for confirming that this was a one-off occurrence. Unless I get reports of this occurring for other users, I’ll treat this as an isolated occurrence that was likely caused externally to Git Graph.

Visual Studio Code used to generate a CPU profile that they would ask the user to manually attach to the GitHub issue they’re asked to raise. This at least provided extension authors a lot more information to see exactly what the extension was doing. Even though it lacked the context of what the user was doing, it at least allowed me to determine if there was a bug in the extension or not.

I’ll follow up on this with the VSCode team, as the template they’ve now changed to (this issue was the first time I saw the new template), really doesn’t give extension authors enough information to work out the cause, other than knowing that the extension started slowly for one user.
