### ISSUE TITLE
The pasted content doubling what is copied!

### ISSUE THREAD

**Issue by cateyes99** [mhutchie/vscode-git-graph#349]
**Describe the Bug**
I'm using the new **VSCode 1.47.1 x64 _zip portable version_** with **Git Graph 1.24.0** on **Windows 10**. Found the weird bug. Whenever copy some content, say `123`, paste it into the `Find` search box, it becomes `123123`. The pasted result in the `Find` search box always doubles the copied content! See the below screenshot.

Interestingly, when downgrade VSCode to use **VSCode 1.45.1 x64 _zip portable version_** with **Git Graph 1.24.0**, there is no such copy/paste issue 🙄 

**Expected Behaviour**
The pasted result should just be exactly the same as what has been copied, i.e., shouldn't double what has been copied.

**Environment**
 - Git Graph Extension Version: **1.24.0**
 - Visual Studio Code Version: **1.47.1**
 - Operating System: **Windows 10**

**Screenshots**
![image](https://user-images.githubusercontent.com/19678455/87610510-a4da2d00-c759-11ea-9678-1c51fdd595f9.png)

**Comment by mhutchie** [comment]
Hi @cateyes99,

This is a bug introduced in Visual Studio Code 1.47, that affects all extensions that use Webviews (including the Git Graph View).

It has been reported to Microsoft by heaps of users globally since it was first introduced over a week ago, and although they have fixed it, the fix hasn’t been released yet. It was targeted for the recovery release, but it doesn’t look like it has made it in - hopefully the fix will be released soon.

The VSCode bug: https://github.com/microsoft/vscode/issues/101946

**Comment by mhutchie** [comment]
I’m closing this as the fix has now be released in Visual Stdio Code 1.47.2.
