### ISSUE TITLE
Navigation to parent or child commit

### ISSUE THREAD

**Issue by albtam** [mhutchie/vscode-git-graph#350]
**Describe the feature that you'd like**
CLion includes a functionality to quickly navigate to the parent commit or the child commit. This is particularly useful when a long time passed between 2 commits on branch A but meanwhile, there are many commits on branch B. With the current implementation, one has to scroll down a lot before finding the parent commit.

CLion includes a clickable arrow to directly jump to the parent/child commit as well as a keyboard shortcut  

**Additional context (optional)**

Arrow: 
![image](https://user-images.githubusercontent.com/30054037/87720590-74c07780-c7b5-11ea-980d-29b76a1a26de.png)

Shortcut:
![image](https://user-images.githubusercontent.com/30054037/87720440-3b880780-c7b5-11ea-96b9-fd111fcdcf75.png)

**Comment by mhutchie** [comment]
Hi @albtam,

Git Graph currently provides this functionality when the Commit Details View is open on a commit:
* `Up` / `Down`: The Commit Details View will be opened on the commit directly above or below it on the Git Graph View, and the commit will be scrolled into view.
* `CTRL/CMD` + `Up` / `CTRL/CMD` + `Down`: The Commit Details View will be opened on its child or parent commit on the same branch, and the commit will be scrolled into view.

You can also click on the parent hashes in the Commit Details View to navigate to them.

The only time these navigation options are not available is when the commit being navigated to is not within the loaded commits, which would still apply no matter what mechanism the action is surfaced to the user.

Although it would be quite easy to add these actions to the commit context menu, this menu is already reaching its maximum capacity (based on the Visual Studio Code UI element sizing). Considering Git Graph already has a keystroke option for navigating to parents and children, and a button option for navigating to parents, I don’t think it is necessary to further duplicate this functionality and waste valuable space in the commit context menu (I’d much rather add another Git command instead).

The direct arrow used by CLion is quite unique, I’m not aware of any other Git UI that does this. Although I can think of some advantages to rendering the graph in this way, I can also think of equally many disadvantages. Graph rendering algorithms are extremely complex to design and implement, so I hesitate at adding this as an alternative option in Git Graph. When the vast majority of users are happy with the current algorithm I’ve written (that is very similar to the vast majority of Git UI’s), I don’t get the impression the option would be used enough to justify the significant development time it would require.

I’ll close this feature request for now, as I believe the existing methods I’ve already implemented effectively address the underlying functionality being requested. I’m also assuming by your statement _”With the current implementation, one has to scroll down a lot before finding the parent commit.”_ that you might not be aware of the existing methods available in Git Graph.

If you’re another user reading this in the future and would like alternative methods for navigating to the parent and children commits, please like / comment on this thread. I’d be happy to reopen this request and implement additional alternatives if enough users indicate they would use them.

**Comment by albtam** [comment]
@mhutchie 

Thanks for the detailed answer. 

> The only time these navigation options are not available is when the commit being navigated to is not within the loaded commits, which would still apply no matter what mechanism the action is surfaced to the user.

This was indeed the scenario I had.

In this case, I agree that it is probably not worth to spend time on the "arrow feature" for now.

Thanks for the great extension!

**Comment by mhutchie** [comment]
Hi @albtam,

To reduce the likelihood of the parent navigation not being available, you can increase the default values for [Initial Load Commits](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#initial-load-commits) and [Load More Commits](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#load-more-commits), at the cost a Git Graph taking slightly longer to load.

Regardless of the mechanism, even the “arrow feature” faces the same underlying challenge when the parent/child is not in the loaded commits. This is because if the parent/child is not in the loaded commits, Git Graph would have to request additional commits from Git so that it has continuous lines of history to the parent/child before it could be navigated to:
* For parents it’s impossible to know how many more commits need to requested from Git such that the parent commit is guaranteed to be within the loaded commits. The only way around this is to load every commit in the entire repository into memory, which is definitely not something I want to do for large repositories.
* For children, Git only stores the parent relationships, so the children are inferred from the inverse of the parent relationship. If there is no loaded commit whose parent is the selected commit (i.e. their is no child commit loaded), Git Graph doesn’t know whether either: there is actually no children, or there is a child but it was excluded from the view (e.g. not on the filtered branches). The only way to know for certain is again to load every commit in the entire repository into memory.

I found that by providing the two extension settings to control how many commits are loaded, the user can easily trade of the number of loaded commits with the time and memory cost of loading the additional commits.
