### ISSUE TITLE
Go to current commit command

### ISSUE THREAD

**Issue by patrik-turi** [mhutchie/vscode-git-graph#351]
**Describe the feature that you'd like**
In the "Git Graph" view, when I check out an old commit by hash (or an old branch) it is really hard to find manually which commit I am standing on in the graph. I need a command that jumps/scrolls the graph to that specific commit that is checked out at the moment.

**Comment by mhutchie** [comment]
Hi @patrik-turi,

I believe the existing keystroke already provides this functionality, it can be run whenever the Git Graph View is active.
> `CTRL/CMD` + `H`: Scrolls the Git Graph View to be centered on the commit referenced by HEAD

I’m closing this feature request as I believe this functionality is already provided in Git Graph, but please let me know if I’ve misinterpreted your request so I can reopen it if necessary.

**Comment by patrik-turi** [comment]
Thank you!

**Comment by LinFor** [comment]
Hello. I need the same functionality. Trying Ctrl+H with no luck.
Also I don't see "Scroll to" command in the vs shortcuts binding list:
![](https://habrastorage.org/webt/nr/3g/zv/nr3gzvsrywti7y4_7alfnamr2ga.png)

VsCode shows v1.27.0 of git-graph installed

**Comment by LinFor** [comment]
Upd: Ctrl+H working when commit loaded in the view. But when going to some stale branch, git graph Ctrl+H not working.
As exact git commit id target is known - seems git graph must iterate through "load more" action till Ctrl+H can be made.

**Comment by mhutchie** [comment]
Hi @LinFor,

I think you've worked it out now, but here's some more information:

As mentioned in the readme and the Extension Detail page in Visual Studio Code, the various keystrokes, including "Scroll to HEAD", are only available in the Git Graph View (when it is open and has the keyboard focus). 
![image](https://user-images.githubusercontent.com/5315753/98912098-bf5ec000-2519-11eb-9ce7-8b7b36966d4a.png)

The commit referenced by HEAD must be within the loaded commit's in order for the Git Graph View to be able to scroll to it with the keyboard shortcut `CTRL+H`. Although it would definitely be nice for Git Graph to work out where the HEAD commit is in the entire repository, load the Git Graph View to contain the commit referenced by HEAD (\*), and then scroll to it, unfortunately it's extremely complicated to do so because of (\*):
* Although the commit hash referenced by HEAD is known by Git Graph, without loading the entire repository into memory (not feasible in very large repositories), it's not possible to know whether HEAD is an ancestor of the commits that are loaded in the Git Graph View, or on a branch that the user has deliberately filtered out.
    1. In the case it is an ancestor of the loaded commits, there's also not a practical way I'm aware of to know how many commits need to be loaded in order to ensure it is subsequently included in the loaded commits.
    2. In the case it's on a branch the user has deliberately filtered out, Git Graph would have to traverse the commit tree to work out the smallest change to the users filtered branches that would allow HEAD to be included, change the filters the user has specified, and then have the same challenge as (i). This becomes even harder with some of the highly requested advanced filtering capabilities currently being implemented for an upcoming release.

I decided to avoid all of these complexities when implementing this keyboard shortcut, and only commit to "Scrolls the Git Graph View to be centered on the commit referenced by HEAD." (it purposely doesn't claim to load any new commits so HEAD is included, it only claims scroll to it if it already exists). This behaviour is consistent with Find tools in web browsers, when trying to scroll to some text on a web page.

If you're frequently facing the scenario where the HEAD commit is an ancestor of the loaded commits (i.e. you work in a fairly large repository), you can increase the value of [Repository > Commits: Initial Load](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#commits-initial-load) to automatically load more commits. This will enable the "Scroll to HEAD" keyboard shortcut to work as expected, as well as enable other functionality that operates on the loaded commtis.

**Comment by LinFor** [comment]
@mhutchie this is not such a frequent case that the git-graph.repository.commits.initialLoad should be increased only because of it.
Maybe it makes sense to do some kind of shortcut to load a large number of commits at a time?

In my opinion, "Scroll to" is not so necessary to go to a commit within 2-3 screens of the last commits, since you can scan them with your eyes.
It is important in the case, when we look at an unfamiliar / forgotten branch, which is most likely somewhere far in the past and it is not even known how many screens we need to wind to get to it.
Alternatively, it may be easier to load commits into the view until a date is found before the date of the desired commit. Yes, this is also not a complete solution, since, for example, rebases can change the order of commits.

**Comment by alexisfrjp** [comment]
FYI, `Git Lens` has such a feature.
![image](https://user-images.githubusercontent.com/6713988/206141849-6968d6a2-7494-4c0a-b474-c5b34d0fa636.png)
