### ISSUE TITLE
Find should include changed files

### ISSUE THREAD

**Issue by andyj513** [mhutchie/vscode-git-graph#353]
**Describe the feature that you'd like**
I would like the "Find" feature to include files that have changed in a commit.  So if I'm looking for a specific commit that changed a specific file, or all the commits which may have changed it, I could use the Find function, type the file name (or part of it) in the text box, and then use the "next" and "previous" arrow buttons to go to all the commits that included that file.

**Additional context (optional)**
Currently, the matched search terms are highlighted in the list of commits.  And currently, the file names are not displayed there, so there would be nothing to highlight.  Even without this, this feature would be handy, as the next/previous would move the selection to the relevant commits.  But it would be even better if text was typed to "Find" and that text matched a file in a commit, if that file name could be displayed somewhere on the commit list (only the first file, if more than one, perhaps), on the row of that commit, and that text could be highlighted.  This would help the user spot the desired commits quickly, and not need to use next/previous to quickly find them.  This could be a temporary display that is only there when text has been typed to Find, and it matches a file in the commit.

**Comment by mhutchie** [comment]
Hi @andyj513,

Thanks for raising this feature request!

When the Git Graph View loads, it only has access to the data that can be returned by `git log` using the format argument (a list of available data fields is under the `format:<string>` bullet point [here](https://git-scm.com/docs/git-log#_pretty_formats)) - the files that were changed in each commit is not one of the available fields. The Find Widget searches through these returned commits to determine the matches (it doesn't run any Git commands). In order to get the files that were changed in a commit, Git Graph runs the `git diff` command when the Commit Details / Comparison View is loaded. It would be extremely expensive to have to run `git diff` for each of the loaded commits (could be thousands), just to retrieve the files that were changed in every commit. For this reason, it's just not feasible to use the Find Widget for the functionality you're requesting.

However, there is already an existing feature request #70 which will provide the capability to *filter* the displayed commits based on whether the commit made changes to a specified file / directory. This leverages the filtering capability of `git log` to restrict the commits that are returned and rendered, as opposed to returning the files changed in every commit to the Git Graph View (that the Find Widget uses). I believe this existing filtering feature will deliver the core capability you're requesting.

I'll close this feature request, as the only feasible way of implementing it is already being tracked by #70.

**Comment by andyj513** [comment]
Could you use "git log --compact-summary"?

**Comment by mhutchie** [comment]
Hi @andyj513,

From what I can see, `--compact-summary` was only introduced in Git >= 2.16.x (released 2 years ago). Git Graph definitely needs to support older versions of Git than that.

However, `--numstat` can be used to retrieve the equivalent file change information from `git log`, and has been around long enough that it would be possible to be used. The reasons why I haven't already used `--numstat` are:
* Parsing: I use the `--format` argument to make the `git log` output easily and efficiently machine-readable, regardless of what version of Git the user has installed. The content from `--numstat` is appended to every commit's output after the `--format` data, and does appear to be somewhat machine-readable. Because Git's documentation uses the wording "make it more machine friendly", it indicates to me that there may be some issues with it being fully machine-readable. Additionally, the way `--numstat` output is appended to the `--format` data of each commit makes parsing both formats intermixed together in an efficient manner quite challenging (may or may not be feasible).
* Performance: Using `--numstat` would make the Git Graph View load slower and use (potentially) significantly more memory. Although it's unlikely that most users would notice the change, those who work on extremely large repositories (with thousands of commits) would definitely notice it. This performance cost would be incurred all of the time for every user, even though a lot of the time the user won't be using the Find Widget, let alone for file changes. Up until now, I've always tried to make the Git Graph View load as quickly as possible, and offload as much as possible / reasonable to the Commit Details / Comparison Views.
* It heavily overlaps with the functionality being implemented in #70. Because of the above two disadvantages, I'd prefer not to almost exactly duplicate the functionality of #70, especially because it avoids both disadvantages.
