### ISSUE TITLE
Git Graph UI not rendering correctly when on VPN and using WSL 2

### ISSUE THREAD

**Issue by ash0803** [mhutchie/vscode-git-graph#355]
**Describe the Bug**
Git Graph doesn't render at all when using VSCode with WSL 2 over a VPN. Screenshots of the log and view are provided.

**Steps to Reproduce**
1. Connect to VPN
2. Run `wsl --shutdown` to get into a clean state for wsl
3. Open VSCode and hit the git graph button
4. See screenshots

**Expected Behaviour**
Git Graph should show the graph view as usual

**Environment**
 - Git Graph Extension Version: 1.25.0
 - Visual Studio Code Version: 1.47.2
 - Operating System: Windows 10

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/10181421/88594548-45352900-d059-11ea-8510-4e7a71eba2d3.png)
![image](https://user-images.githubusercontent.com/10181421/88594556-4b2b0a00-d059-11ea-8ca9-c50a7358868f.png)

**Additional Context (optional)**
- There is no such issue with VS code 1.46 over the VPN
- Everything works fine without the VPN
- Issue still happens when Windows firewall is disabled

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment]
Hi @ash0803,

The Visual Studio Code team made significant changes to the Webview implementation in Visual Studio Code 1.47, and unfortunately introduced numerous bugs that prevented the Webview’s from loading CSS & JS resources. These bugs affected all extensions that use Webview’s (the Git Graph View uses a Webview, and uses CSS & JS resource to render). The Visual Studio Code team managed to fix most of them during Visual Studio Code Insiders 1.47.0, however there are still multiple bugs that need to be fixed that made it into Visual Studio Code 1.47.x.

Another user reported the same resource-loading bug when using WSL2 [here](https://github.com/microsoft/vscode/issues/101272), which has now been fixed. I’m not sure if it was released in Visual Studio Code 1.47.2, but it should definitely be available in Visual Studio Code Insiders. Please test to see if the resource-loading bug you’re observing has already been fixed in Visual Studio Code Insiders. If not, please raise a new bug in the Visual Studio Code repository (similar to the one I’ve linked) specifically for your scenario with WSL2 & VPN.

**Comment by ash0803** [comment]
Thanks for your quick response. Unfortunately, the issue still exists for me using 1.47.2 and also with insiders edition.

I'll downgrade and wait for a fix from the vscode team then 👍

**Comment by mhutchie** [comment]
Hi @ash0803, 

Thanks for letting me know that there is still an outstanding bug with Webview’s and WSL2 over a VPN in Visual Studio Code 1.47.x. It means that I can let other users know if they’re using the same technologies and have the same issue.

Please make sure you raise this as a bug in the vscode repository, as it’s quite possible they’re unaware of it.
