### ISSUE TITLE
Add ability to show changes in working folder

### ISSUE THREAD

**Issue by morganlombard** [mhutchie/vscode-git-graph#36]
**Describe the feature that you'd like**
When clicking on **Uncommitted changes**, show the **diff** similarly to when clicking on a commit.
Add the context-menu option to diff with working folder.

**Comment by mhutchie** [comment]
I'm not sure what additional value this would add, for the following reasons:
- If the **Uncommited changes** expands to show something similar to the commit details view:
    - There isn't any useful information for the left of the commit details view, so there is no point in showing it.
    - The diff on the right is just like you can see on the Visual Studio Code "Source Control" tab, so it also doesn't add any new functionality from native Visual Studio Code.
- None of the actions of the commit context menu are applicable to **Uncommited changes**, without them being commited first.
- The only action I can think of for the context menu would be to commit the uncommited changes (which is also natively in Visual Studio Code).

To me it seems that making these changes doesn't add any functionality that isn't already available easily in Visual Studio Code, and anything that could be reasonably implemented in Git Graph would only be a subset of what Visual Studio Code already provides. Please let me know your opinion on what you would like to see in Git Graph for **Uncommited changes**, and why it would be better to be implemented in Git Graph instead of what is already natively available.

**Comment by mhutchie** [comment]
Closing for now, as I don't see the value added to Git Graph by making this change.

**Comment by mhutchie** [comment]
I'm reopening this issue, as it was requested in #29 (which implements comparing any two commits) that it be extended to support comparison with the working folder / uncommitted state. This would allow new functionality to be implemented, that is not already available natively in Visual Studio Code so I think it would now make sense to add support for the working folder / uncommitted state.

**Comment by mhutchie** [comment]
This will be available in v1.6.0. I have implemented:
- View uncommitted changes
- Comparing any commit with the uncommitted changes
- Three new Git actions from the new Uncommitted Changes context menu:
    - Reset uncommitted changes to HEAD
    - Clean untracked files
    - Open the Visual Studio Code Source Control View

If you'd like to use it before the next release, you can download [v1.6.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.6.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
