### ISSUE TITLE
Find results are not visible in high contrast themes

### ISSUE THREAD

**Issue by Sesostrismage** [mhutchie/vscode-git-graph#363]
When I use the Git Graph find dialog with e.g. the tomorrow night theme, the find result for "formatting" looks like this and is visible in the graph:
![Find - Tomorrow night theme](https://user-images.githubusercontent.com/24550972/89858763-b91a1a00-db9f-11ea-8869-b230f91422c5.PNG)

When I use the built-in high contrast theme and another high-contrast theme I have installed, the find result is invisible:
![Find - High contrast theme](https://user-images.githubusercontent.com/24550972/89858807-d0f19e00-db9f-11ea-93c1-e9b690b625ce.PNG)

**Comment by mhutchie** [comment]
Hi @Sesostrismage,

Thanks for making me aware of this incompatibility with high contrast themes. From what I can see, unlike light and dark themes, high contrast themes only specify a border colour (no background colour) for find matches.

Git Graph currently consumes the Visual Studio Code CSS Property `--vscode-editor-findMatchHighlightBackground` to style find matches. As this is not defined in high contrast themes, that is why no highlighting is currently shown for find matches.

I'll adjust the styling of find matches to use an outline of the Visual Studio Code CSS Property `--vscode-editor-findMatchHighlightBorder`, so that matches can be seen in high contrast themes.

**Comment by mhutchie** [comment]
This will be available in v1.26.0.

If you'd like to use it before the next release, you can download [v1.26.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.26.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by Sesostrismage** [comment]
Thank you for the fast response, much appreciated. 👍
