### ISSUE TITLE
cannot show current repo but show the parent dir repo

### ISSUE THREAD

**Issue by hqabcxyxz** [mhutchie/vscode-git-graph#370]
**Describe the Bug**
I have a git repo on my Home dir to manage my system config. then I set a dir as my workspace in Home,and create my project git repo in it.  the I notice that,git graph cannot show current repo but alawys show parent repo(on my home dir).
.

My git graph just use default config.

its weird that my other git repo  dosent have this problem...

**Steps to Reproduce**
as above

**Expected Behaviour**
just show the history about current git repo

**Environment**
 - Git Graph Extension Version: 1.25.0
 - Visual Studio Code Version: 1.48.2
 - Operating System: ubuntu 18.04

**Screenshots (optional)**
here is my current repo:
![](https://raw.githubusercontent.com/hqabcxyxz/MarkDownPics/master/image/20200827195355.png)

here is my Home dir repo:
![](https://raw.githubusercontent.com/hqabcxyxz/MarkDownPics/master/image/20200827195521.png)

here is my git graph show:
![](https://raw.githubusercontent.com/hqabcxyxz/MarkDownPics/master/image/20200827195635.png)

**Additional Context (optional)**

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment]
Hi @hqabcxyxz,

When Git Graph is searching the Visual Studio Code workspace for Git repositories, it stops as soon as it finds a folder that is within a directory. I believe in your scenario, it stops at the workspace root because it is in your Home directory repository - it doesn’t recursively search within the Home repository to find the new project Git repository within it.

Have you tried running the Git Graph command “Git Graph: Add Git Repository” from the Visual Studio Code Command Palette to add the desired project repository to Git Graph? This command is designed to allow you to add sub-repositories to Git Graph.

**Comment by mhutchie** [comment]
Hi @hqabcxyxz,

I’ll close this issue for now, as I believe the behaviour you’ve described is completely correct / as expected, and that the “Git Graph: Add Git Repository” command provided in Git Graph will allow you to add the repository you’re want to Git Graph (as I mentioned in my response yesterday).

Even though I’m closing this issue for now, I’ll still receive any future replies you make, and will continue to provide support to resolve this issue if my previous response does not.
