### ISSUE TITLE
Launch git-graph fail by Run Extension

### ISSUE THREAD

**Issue by yuzhidi** [mhutchie/vscode-git-graph#371]
Activating extension 'mhutchie.git-graph' failed: Cannot find module 'd:\study\vscode-git-graph\out\extension.js'
Require stack:
- d:\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- d:\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- d:\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js.
---------------------
I have run 'npm install'

is there any suggestion?

**Comment by mhutchie** [comment]
Did you just install / update the extension from the Visual Studio Code Marketplace? If so, just uninstall it, and reinstall it again (occasionally Visual Studio Code fails to download the extension correctly from the Marketplace).

If not, how are you attempting to run the extension? (so I have a better context of what might have happened)

**Comment by mhutchie** [comment]
I'll close this question, as I believe my previous response with the linked detailed instructions answers your question. *(I've edited it since my first response to hopefully better answer your question.)*

Please reply to let me know how you go, and if you have any other questions or my previous response isn't sufficient.
