### ISSUE TITLE
Shortcut for Fetch

### ISSUE THREAD

**Issue by zero11995** [mhutchie/vscode-git-graph#373]
like title, I love this extension than sourcetree, but it's disappointing that it can not config a shortcut for Fetch action.

**Comment by mhutchie** [comment]
Hi @zero11995,

Could you please explain what you mean by “Shortcut for Fetch”?

Currently there is a Fetch button on the Git Graph Views Control Bar.

Are you referring to adding keyboard shortcut for Fetch? I only have shortcuts in the Git Graph View for actions specific to the view itself (like refresh, scroll to head, etc.). I don’t have shortcuts for general Git Commands, as they should be provided / implemented by Visual Studio Code, so that they can be used anywhere in Visual Studio Code (not just when the Git Graph View is visible and focussed).

**Comment by zero11995** [comment]
Sorry I did not explain precisely, yes, I mean the keyboard shortcut for Git Fetch
I understand you dont want to duplicate the feature, I just want to still see the modal "Fetch from Remote" in Git Graph when I use the fetch keyboard shortcut
I appreciate your reply

**Comment by mhutchie** [comment]
Considering Visual Studio Code already provides a built-in mechanism to have a Keyboard Shortcut that triggers Git to fetch from a repositories remote, would you please let me know what functional benefit would result from duplicating this functionality in Git Graph? (What value would be added for users by including it in Git Graph?)

**Comment by zero11995** [comment]
from my perspective, VSC already provides the command palette and keyboard shortcut for git fetch, and you still put a button next to refresh button, 
clicking your button will show user a modal that can see fetching is in the progress, and the built-in mechanism can not achieve that(silently work in the background). 

so it's just an optional user exp suggestion

**Comment by mhutchie** [comment]
The reason I have a Fetch button in Git Graph is because Visual Studio Code does not provide a Fetch button (they only have a command and keyboard shortcut). Therefore providing a Fetch button provides additional functionality, not already in Visual Studio Code. Whereas, providing a keyboard shortcut for fetch would be duplicating the Visual Studio Code capability. Please see the table below, to see how I only have functionality in Git Graph, that is not already in Visual Studio Code.

| Feature | Provided in Visual Studio Code | Provided in Git Graph |
| --- | --- | --- |
| Fetch Command | Yes | No |
| **Fetch Button** | **No** | **Yes** |
| Fetch Keyboard Shortcut | Yes | No |
| Sync Command | Yes | No |
| Sync Button | Yes | No |
| Sync Keyboard Shortcut | Yes | No |

I can understand that seeing the fetch progress is useful information to know (hence why I have a modal to display it), and that Visual Studio Code's Fetch Command doesn't provide this. As this seems to be the core reason why you're not wanting to use the Visual Studio Code Fetch Command, please raise a feature request in the Visual Studio Code GitHub repository. When Visual Studio Code implements this functionality, it will mean that every Visual Studio Code user (not just those with Git Graph installed & the view opened) can have an improved experience, and see the progress of the Visual Studio Code Fetch Command.
