### ISSUE TITLE
Highlight Find Widget Search Result

### ISSUE THREAD

**Issue by wingliu0** [mhutchie/vscode-git-graph#374]
**Describe the improvement that you'd like**
Can I have the Search Result hightlighted after search?

**Comment by mhutchie** [comment]
Hi @wingliu0,

Would you please clarify what you’re requesting in this improvement? It’s not clear to me what you’re wanting changed.

The current behaviour is:
1. User opens the Find Widget (either by the Find Button, or the `CTRL` + `F` keystroke)
2. User types a string to find in the commit messages / date / author / commit hash / branch name / tag name
3. The first commit that matches is highlighted, with the exact match highlight as well.
4. User can navigate between the commit matches using the Find Widget buttons and their corresponding keystrokes, which are then highlighted accordingly.
5. User closes the Find Widget and all find match highlighting is removed from all commits.

FYI: There is known compatibility issue that was recently brought to my attention with the find match highlighting if you’re using a High Contrast Colour Theme in Visual Studio Code. This is fixed in the latest beta release of the extension which can be downloaded from GitHub.

**Comment by wingliu0** [comment]
Hi @mhutchie ,
I found out the problem, like what you have said, the compatibility issue occurs when Im high contrast/ specific color theme, 
FYI: the one im using this [Plastic](https://marketplace.visualstudio.com/items?itemName=will-stone.plastic)

**Comment by mhutchie** [comment]
Hi @wingliu0,

Thanks for confirming the the beta release has resolved this issue for you.

FYI: Although not in a beta release yet, I’ve also made various other changes to improve compatibility with high contrast themes - which will all be released in the next version of Git Graph.
