### ISSUE TITLE
Visual Studio Code Bug with WSL2 preventing the Git Graph View from loading

### ISSUE THREAD

**Issue by MaurGi** [mhutchie/vscode-git-graph#378]
**Describe the Bug**

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Install VS Code and connect to Ubuntu WSL2 via Remote - for details look here: https://medium.com/@maurogiusti/running-ubuntu-on-windows-10-with-wsl2-part-3-visual-studio-code-and-go-e2c04ae1abd5 - there is a section of Best VSCode Plugins at the end
2. Open a git managed project in Ubuntu
3. Click Git Graph in the status bar
4. See error:
![image](https://user-images.githubusercontent.com/13138584/92648874-0244b300-f29f-11ea-9df4-5ce18c8b20ab.png)

**Expected Behaviour**
Regular Git Tree UI should show up

**Environment**
 - Git Graph Extension Version: 1.13.0:
![image](https://user-images.githubusercontent.com/13138584/92649036-42a43100-f29f-11ea-9905-d36983717090.png)

 - Visual Studio Code Version: 
```
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z (2 wks ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```
 - Operating System: 
![image](https://user-images.githubusercontent.com/13138584/92649066-53ed3d80-f29f-11ea-8e90-8e31f2aa3b4a.png)

With WSL2

Git Graph Output:
```
[2020-09-09 13:14:49.751] Starting Git Graph ...
[2020-09-09 13:14:49.777] Using git (version: 2.17.1)
[2020-09-09 13:14:49.783] > git rev-parse --show-toplevel
[2020-09-09 13:14:49.784] Showing "Git Graph" Status Bar Item
[2020-09-09 13:14:49.784] Started Git Graph - Ready to use!
[2020-09-09 13:14:49.805] Searching workspace for new repos ...
[2020-09-09 13:14:49.806] Completed searching workspace for new repos
[2020-09-09 13:14:54.995] Created Git Graph View
```

**Screenshots (optional)**
See above

**Additional Context (optional)**
New installed PC - worked on the old PC :(

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment]
Hi @MaurGi,

The Visual Studio Code team made significant changes to the Webview implementation in Visual Studio Code 1.47, and unfortunately introduced numerous bugs that prevented the Webview’s from loading CSS & JS resources. These bugs affected all extensions that use Webview’s (the Git Graph View uses a Webview, and uses CSS & JS resource to render). The screenshot you have shown occurs because Visual Studio Code fails to load the CSS & JS resources that the Git Graph View requires to render. If you run the "Developer: Open Webview Developer Tools" command from the Visual Studio Code Command Palette, and switch to the Console Tab, you'll be able to see the errors that Visual Studio Code is having.

Although the Visual Studio Code team managed to fix the vast majority of Webview issues before Visual Studio Code 1.47.x was fully released, numerous bugs still made it through, including several with WSL2 that caused exactly the behaviour you've reported. Unfortunately, this is beyond my control as these Visual Studio Code bugs are in the Webview implementation itself, which is used by many extensions including Git Graph. There is nothing I can do within Git Graph to avoid this issue.

Please raise a bug in the Visual Studio Code GitHub repository, which outlines that: you're using WSL2, Webview resources are failing to load for extensions, and provide as much context as you can about how WSL2 is setup on your computer (as it must be a fairly obscure edge case you're facing). Feel free to mention me in the thread using `@mhutchie`, so I can help provide additional context if required by the Visual Studio Code team.

**Comment by MaurGi** [comment]
File a bug here: https://github.com/microsoft/vscode/issues/106667 - does this only happens in WSL ?

**Comment by mhutchie** [comment]
Hi @MaurGi,

The only reports I’ve still been getting of the JS/CSS still failing to load occur when the user has some slightly unusual WSL configuration.

**Comment by mhutchie** [comment]
Hi @MaurGi,

Would you please:
* Update your issue title in the vscode repo to reflect that “Webview resources are failing to load for extensions with WSL2”, your current issue title is completely misleading users to think that Git Graph is unusable with latest two versions of Visual Studio Code - I’ve gotten numerous people questioning this.
* Change “No this is an issue with a specific extension“ to “No this is an issue with Webview’s that affect multiple extensions“.
* Reply to Matt’s question in the vscode issue regarding whether it is present in Visual Studio Code 1.49.0.

**Comment by mhutchie** [comment]
@MaurGi, could you please respond to my previous reply - it's important that this issue is correctly reported so that it can be addressed and resolved by the Visual Studio Code team.
