### ISSUE TITLE
Git Graph window overlaps some other panel borders

### ISSUE THREAD

**Issue by n-gist** [mhutchie/vscode-git-graph#380]
Hi! Just noticed this (red arrows).
There is 1px padding/margin noticeable also (green arrow).
It spoils the clarity a bit in some color themes.

![ov1](https://user-images.githubusercontent.com/58081918/93033135-c58a0a80-f656-11ea-9e7e-7cd516bfcbba.png)
![ov2](https://user-images.githubusercontent.com/58081918/93033136-c7ec6480-f656-11ea-8208-402a549a1c29.png)

**Comment by mhutchie** [comment]
Hi @n-gist,

The Git Graph View is just a Visual Studio Code [Webview](https://code.visualstudio.com/api/extension-guides/webview) - Git Graph *only* provides the contents to display within the Webview. The positioning of the Webview in the Visual Studio Code UI, and the borders of the Webview, is implemented by Visual Studio Code itself. I can replicate this exact same bug with every extension I'm aware of that uses Visual Studio Code Webview's (it's not just Git Graph that is affected). Please raise this as a bug in the [vscode](https://github.com/microsoft/vscode) repository, so Microsoft can fix it.

I'll close this bug, as it's a Visual Studio Code Bug (not a Git Graph Bug), and can only be fixed by Microsoft. There's also no work-around that I could implement in Git Graph, as extensions can only style the contents of the Webview, not the Webview itself.
