### ISSUE TITLE
Allow commit and tags signing

### ISSUE THREAD

**Issue by AngheloAlf** [mhutchie/vscode-git-graph#399]
**Describe the feature that you'd like**

`git` allows to sign commits and tags¹ using the flags `-S` and `-s` respectively.
It could be great if git-graph could sign¹ every action it is performed in its GUI.

**Additional context (optional)**

vscode already has a setting to enable this:
![image](https://user-images.githubusercontent.com/7416381/96375901-43f43380-1152-11eb-8f58-9524fe7ab35d.png)
With this option enabled, every action done using the built-in GUI is signed. But, git-graph does not support this, so mixing actions between both (like making commits in vscode and merging branches in git-graph) produce a mix of signed and unsigned commits.

I suggest to check if that option is enabled and sign accordingly.

---
¹ if the user has previously configured their keys.

**Comment by mhutchie** [comment]
Hi @AngheloAlf,

Thanks for raising this feature request, I definitely think this capability should be available in Git Graph! I’ll add it in an upcoming release.

**Comment by mhutchie** [comment]
This will be available in v1.28.0.

I created two new extension settings (`git-graph.repository.sign.commits` and `git-graph.repository.sign.tags`) to control commit and tag signing respectively, instead of using the existing Visual Studio Code setting `git.enableCommitSigning`. This is because `git.enableCommitSigning` is specifically for signing commits, so some users may have found it misleading if it also meant Git Graph started signing tags. Although I could have just created a new setting for signing tags, and used `git.enableCommitSigning` for signing commits, this would have meant users would have to enable two completely separated settings in the Visual Studio Code Settings Editor. I think creating two new settings (grouped together) was ultimately the best solution, even though it would have been nice to share the same setting as the Visual Studio Code Git Extension.

If you'd like to use it before the next release, you can download [v1.28.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.28.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
