### ISSUE TITLE
change text of context menu

### ISSUE THREAD

**Issue by zodiake** [mhutchie/vscode-git-graph#40]
**Describe the feature that you'd like**
The text of context menu like "Create Branch from this commit" may be should change to "New Branch..." since their should be other steps to finish the job

By the way.I made some change to the UI.
I saw that when one click a commit the detail will show bellow.
I change this to a split window something just like intellij version control doing.
Do you think it is a good idea?
Thanks

**Comment by mhutchie** [comment]
Thank you for the suggestions!

1. I like the additional detail provided by "Create Branch from this commit", as it explicitly anchors the action (creating a branch) to the object it will be performed on (the commit which was right clicked. If many other users prefer "New Branch..." I'd be happy to change it.
2. I prefer the current method of viewing the commit details (showing below the commit), as it reinforces the context of where the commit details occur. Again though, if many other users prefer "New Branch..." I'd be happy to change it.

For now I'll close this issue as I don't intend to make these changes in upcoming releases. However, I'll monitor this issue so that if other users prefer either of these items I can reopen and implement them.

**Comment by mpekurin** [comment]
+1 to use "New Branch..." or "Create Branch..." and also to change "Add Tag" to "Add Tag...". VS Code itself uses this kind of text for commands that requires other steps. I think it would be nice to maintain something like a common style of commands texts.
![img](https://user-images.githubusercontent.com/22733346/55177647-bb3f2c80-5194-11e9-83b4-bd216296deba.png)

**Comment by mhutchie** [comment]
Thanks @mpekurin for pointing out the VS Code naming conventions. Git Graph should definitely match it. I'll add this in the next release @zodiake.

**Comment by mhutchie** [comment]
This will be available in v1.4.4. I've followed [Microsoft's guidelines](https://docs.microsoft.com/en-us/windows/desktop/uxguide/cmd-menus#using-ellipses) for using ellipses, and removed redundancies in action names to shorten them if possible.

If you'd like to use it before the next release, you can download [v1.4.4-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.4-beta.3), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
