### ISSUE TITLE
Customise Git Graph View keystrokes

### ISSUE THREAD

**Issue by drkvogel** [mhutchie/vscode-git-graph#406]
(btw I can't find anyone on Discord!)

Hi, been using Git Graph for a few weeks and love it, however, I had `ctrl+r` on my Mac mapped to `File: Open recent` (which I think it the default on Mac?), and now when I'm looking at Git Graph I press `ctrl+r` to switch to another window, and it refreshes the graph instead.

I can't find any settings in VS Code for Git Graph other than the ones at [#extension-commands](https://github.com/mhutchie/vscode-git-graph#extension-commands), and searching for `ctrl+r` or `cmd+r` doesn't find anything related to Git Graph, nor can I find anything in the docs.

Could the keyboard shortcuts available in the Git Graph view be made configurable?

**Comment by mhutchie** [comment]
Hi @drkvogel,

All available keyboard shortcuts in the Git Graph View are listed on the extension [readme](https://github.com/mhutchie/vscode-git-graph/blob/develop/README.md), and on the extensions details page in Visual Studio Code under the “Keyboard Shortcuts” bullet point.

These keyboard shortcuts are handled within the Git Graph View itself, not through the configurable Visual Studio Code Keybindings. There are a variety of factors that make this the best solution for keyboard shortcuts specific to the Git Graph View.

I’ll create some new extension settings so that each of these Git Graph View keystrokes can be configured according to the users preference.

**Comment by mhutchie** [comment]
This will be available in v1.28.0.

If you'd like to use it before the next release, you can download [v1.28.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.28.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
