### ISSUE TITLE
Enable "Git Graph: File Encoding" Extension Setting to be Workspace Folder Scoped

### ISSUE THREAD

**Issue by tksmtd** [mhutchie/vscode-git-graph#416]
We have multiple projects. Users and Workspace have similar settings.
Please give the same setting items to the vscode folder setting.
Please for users with multiple encoding.

Git-graph is the easiest change-history tool to use.
Thank you as always.

**Comment by mhutchie** [comment]
Hi @tksmtd,

Thanks for raising this feature request!

There is a fairly significant amount of overhead and work required in order to have *all* extension settings scoped to a folder level, so up until now I’ve avoided it as no user had previously raised a scenario where the workspace scoped settings weren’t enough. In saying that, for many settings it’s easy to enable folder scoped settings (included “Git Graph: File Encoding”), just not all settings. I’ll work through the extension settings and enable as many of them to be folder scoped as possible. It seems this the approach taken by many other Visual Studio Code settings for the same reason.

Would you please provide a list of any other settings you need to have folder scoped, so I can ensure all of these are included in the subset I implement?

**Comment by mhutchie** [comment]
I've implemented this change for the "Git Graph: File Encoding" extension setting, but have left other extension settings with their current scopes for now (after I did an initial review to determine suitability). I'd be happy to enable other extension settings to be Workspace Folder Scoped on a case-by-case basis.

This will be available in v1.28.0.

If you'd like to use it before the next release, you can download [v1.28.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.28.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by tksmtd** [comment]
Thank you so much! Now we can include multiple projects with multiple encodings.
I'm sorry for being busy and late in replying. However, a very quick update. Thank you!
I confirmed the operation earlier by v.1.28.0-beta.2. People who suffer from many encodings will be saved.
I always cheer for you.
