### ISSUE TITLE
Explicitly mention the current branch on Merge, Pull, Rebase & Reset Dialogs

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#419]
**Describe the improvement that you'd like**
Giving the name of the current branch instead of the `current branch...` text or `current branch: [brancheName]`

**Additional context (optional)**
Actually when right clicking to an other branch, it's written `Merge into current branch...`.  
It isn't a problem for myself since it makes complete sense to my why it's written like that.  

But what I could see about new developers is that they seems to not direct understand what they're doing here.  
But they understand pretty fast the concept of `develop` and `master` branch. So it "may" help new comers if they would see a `Merge into master`.  

What do you think?

**Comment by mhutchie** [comment]
Hi @rbalet,

Thanks for raising this improvement request!

I don't think the names of actions should vary depending on which branch is checked-out (e.g. if the user sees `Merge into master...`, they might wonder why they don't have an option to merge into other branches - `Merge into current branch...` is exactly what the action does). The second option you suggested, `Merge into current branch: [branchName]`, loses the trailing ellipsis (indicating the action isn't immediately performed, and has a dialog before proceeding), and makes the action name even longer. Also, adding user-generated dynamic length content (i.e. branch names) is problematic for context menu's, as many users have long branch names that would either make the context menu extremely wide, or have to be abbreviated with an ellipsis.

However, I do agree that there should be some reference to what the "current branch" is during the `Merge into current branch...` action. I think this would be best suited to on the dialog itself, so the text would become "Are you sure you want to merge branch ***develop*** into the current branch ***master***?", instead of the existing text "Are you sure you want to merge branch ***develop*** into the current branch?". I'd also make this change to similar actions (e.g. `Pull into current branch...`).

I'll include this in the next release.

**Comment by mhutchie** [comment]
This will be available in v1.28.0.

If you'd like to use it before the next release, you can download [v1.28.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.28.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
