### ISSUE TITLE
can't authenticate anymore in Github

### ISSUE THREAD

**Issue by fabiomosti** [mhutchie/vscode-git-graph#421]
hello, Git Graph suddenly can't authenticate anymore in Github, even though I provide the correct username and password

there is a way to understand what is the problem, and make this work again?

thank you

**Comment by mhutchie** [comment]
Hi @fabiomosti,

I was affected by this last weekend, for me it affected Visual Studio Code, Git Graph, and running Git commands in the terminal equally. After entering my credentials in all prompts, including one that was minimised by default, I was however able to run Git commands that interacted with a GitHub remote. It was due to a change to how GitHub authentication works, which requires the latest version of Git for Windows to be installed. After installing the latest version of Git for Windows, everything worked first-go and seamlessly.

I got the following email from GitHub which explained the steps to follow:

> We have detected that you recently attempted to authenticate to GitHub using an older version of Git for Windows. GitHub has changed how users authenticate when using Git for Windows, and now requires the use of a web browser to authenticate to GitHub. To be able to login via web browser, users need to update to the latest version of Git for Windows. You can download the latest version at:
> 
> * https://gitforwindows.org/
> 
> If you cannot update Git for Windows to the latest version please see the following link for more information and suggested workarounds:
> 
> * https://aka.ms/gcmcore-githubauthchanges
> 
> If you have any questions about these changes or require any assistance, please reach out to GitHub Support and we’ll be happy to assist further.
> 
> * https://support.github.com/contact
> 
> Thanks,
> The GitHub Team

Even though I’m closing this question (as you should be able to follow these instructions to resolve the GitHub authentication compatibility issue), please reply if you still have any follow up questions - I’ll still receive them and will reply.

**Comment by fabiomosti** [comment]
hello, thank you for your answer but it's weird since I'm using Linux (Ubuntu), anyone had the same issue?

thank you

**Comment by mhutchie** [comment]
Hi @fabiomosti,

Due to the timing of GitHub authentication failing for you being right after GitHub turned off an old authentication mechanism, even though you’re not using Windows I’d be fairly confident the two are connected.

Would you be able to install the latest version of Git to see if that resolves it?

If that doesn’t, would you please:
* Try running the same Git command in a Visual Studio Code terminal, and let me know the behaviour that occurs (it should be the same as Git Graph). You can find out the Git commands the extension is running by looking at the “Git Graph” Visual Studio Code Output Channel.
* Provide some specifics of your system (e.g. OS Version, Git Version etc.) so I can attempt to replicate it if possible.

FYI: I haven’t heard any other users having difficulty with the GitHub authentication change. With the large number of users using the extension, if there was some compatibility issue for GitHub authentication and the extension on Linux, I would have definitely expected to hear others having the same problem by now.

**Comment by fabiomosti** [comment]
hello, thank you for answering, my git version is 2.25.1 on Ubuntu 20.04
![Schermata del 2020-11-23 10-33-04](https://user-images.githubusercontent.com/53529766/99946830-50823200-2d77-11eb-89d2-2aaddab4a7fc.png)

as you can see, no output is given

even more weird, I tried the same thing from my laptop (Ubuntu 18.04) and unexpectedly it worked

so maybe it's something about Ubuntu 20.04???

**Comment by mhutchie** [comment]
1. Try updating to Git 2.29.x, and see if the same error message occurs.
2. Try running the same Git command in a Visual Studio Code terminal, and let me know the behaviour that occurs (the error logged to the terminal should be the same as what is shown in the Git Graph dialog). You can find out the Git commands the extension is running by looking at the “Git Graph” Visual Studio Code Output Channel.
3. Compare the values of `git config credential.helper` on Ubuntu 20.04 & Ubuntu 18.04 to see if anything has changed.

**Comment by fabiomosti** [comment]
hello, I think I found a solution, but I am still not sure about what the problem actually is... I simply deleted the github remote and adding it back again the problem was solved:

`fabio@istrice-18:/var/www/html$ git remote remove origin
fabio@istrice-18:/var/www/html$ git remote add origin git@github.com:Istricesrl/glisweb.git
fabio@istrice-18:/var/www/html$ git push --set-upstream origin develop`

the strange, strange fact about this is that other commands (push, pull, fetch) on this remote worked perfectly, even through VS Code graphic interface; the only extension affected by this error was Git Graph

hope this can help someone!
