### ISSUE TITLE
Add "Below" option to Open New Tab Editor Group setting

### ISSUE THREAD

**Issue by BradL-Msft** [mhutchie/vscode-git-graph#432]
**Describe the feature that you'd like**
Currently Open New Tab Editor Group makes it easy to view diffs of a large number of files by opening the file tab elsewhere.  The current "Besides" option is good for this because it doesn't care how many groups might already be open - the new tab is always next to the graph view.  For some monitor layouts it would be nice to have the same behavior, only split the new document horizontally rather than vertically.  

If possible, please consider a "below" setting that works like "besides" but splits the window horizontally rather than vertically.

**Comment by mhutchie** [comment]
Hi @BradL-Msft,

I've definitely wanted to include a "Below" option for the "Open New Tab Editor Group" extension setting, however unfortunately this is simply not possible (due to the Visual Studio Code API - which all extensions must use to interface with Visual Studio Code).

When the extension calls the `vscode.diff` command to open the Visual Studio Code Diff View, it accepts a `vscode.TextDocumentShowOptions` argument (according to [this page](https://code.visualstudio.com/api/references/commands) & the codebase). `vscode.TextDocumentShowOptions` has [this interface](https://code.visualstudio.com/api/references/vscode-api#TextDocumentShowOptions), which only lets you specify a `ViewColumn` as defined [here](https://code.visualstudio.com/api/references/vscode-api#ViewColumn). I currently allow all of the possible options of `ViewColumn` to be chosen via the "Open New Tab Editor Group" extension setting. Visual Studio Code does not allow the Visual Studio Code Diff View to be loaded below the Git Graph View, and a feature request for the implementation of this was closed by Microsoft as not enough interest was expressed at the time (https://github.com/microsoft/vscode/issues/84113).

In [this comment](https://github.com/mhutchie/vscode-git-graph/issues/206#issuecomment-550472339) I previously outlined a potential work around that would achieve the desired behaviour (not using `vscode.TextDocumentShowOptions`). However, unfortunately this work-around had an issue that I noted at the time, that was so annoying to users that ultimately I couldn't proceed to use it.

If in the future Microsoft does decide to extend the Visual Studio Code API to allow a "Below" option, I'll definitely re-open this request and implement it.

**Comment by BradL-Msft** [comment]
Thanks for the quick and detailed reply!
