### ISSUE TITLE
Git Graph prevent open "command palette" since the second time I press cmd + shift + p

### ISSUE THREAD

**Issue by bahung1221** [mhutchie/vscode-git-graph#434]
**Describe the Bug**
When Git Graph is opened, I only can open `VSCode command palette` the first time, since the second time I press `cmd + shift + p`, nothing happened.

**Steps to Reproduce**
1. Open Git Graph
2. Press `cmd + shift + p` (macOs)
3. Press `esc`
4. Press `cmd + shift + p` again (nothing appeared here)

**Expected Behaviour**
The command palette appear after press `cmd + shift + p`

**Environment**
 - Git Graph Extension Version: [e.g. 1.28.0]
 - Visual Studio Code Version: [e.g. 1.52.0]
 - Operating System: macOs Big Sur

**Screenshots (optional)**
![Screen-Recording-2020-12-14-at-1](https://user-images.githubusercontent.com/27690861/102061130-a8b3cd80-3e25-11eb-8e43-ce6e79c7bbe6.gif)

**Comment by mhutchie** [comment]
Hi @bahung1221,

After following the steps you provided, I can replicate this behaviour, and have found that it only appears to occur on some operating systems (Mac's, but not Windows), and it occurs any time an extension-contributed [Visual Studio Code Webview](https://code.visualstudio.com/api/extension-guides/webview) is active. For me it seemed to occur after one or more keystrokes, not necessarily the second. The Git Graph View uses a Webview to render it's content, along with many other extensions. I was able to replicate this bug when the Webview's of multiple other extensions were also active - i.e. this is not a bug with Git Graph, it's a bug with Visual Studio Code, that affects many extensions.

I expect this bug was introduced in Visual Studio Code 1.52.0, which was only released a few days ago. Please raise this as a bug in the [Visual Studio Code](https://github.com/microsoft/vscode) GitHub repository, so Microsoft can fix it in one of the next patch releases. Please title the bug as "Keyboard shortcut's fire intermittently when Webview's are active", describe the behaviour you observed (highlighting that it affects all extensions that use Webview's, not just Git Graph), link to this issue, and mention my GitHub handle. I can help provide additional information if necessary.

There have been numerous Visual Studio Code keyboard shortcut bugs extremely similar to this over the last two years.

**Comment by bahung1221** [comment]
Ops, sorry and thanks for your quick response, 🚀 

I understood, I will create a new issue in VSCode repository for this problem. 😄
