### ISSUE TITLE
Friendly dates

### ISSUE THREAD

**Issue by yzhang-gh** [mhutchie/vscode-git-graph#44]
### Describe the feature that you'd like

Hi, I noticed that we got some customization on the date format recently. Then it occurred to me why not having the "friendly dates" feature.

### Additional context

It is something like this (_notice the "Date modified" column_)

![demo](https://user-images.githubusercontent.com/7588612/55353969-75e46d00-54bc-11e9-9ea5-7fb7f99117bb.png)

<sup>https://blogs.windows.com/windowsexperience/2018/12/19/announcing-windows-10-insider-preview-build-18305/</sup>

I am not sure but I think there are already some modules we can make use of.

**Comment by mhutchie** [comment]
This seems to be similar to what I have called “Relative” in the setting `git-graph.dateFormat`, although “friendly dates” appears to have additional rules for showing “just now”, weekdays & times, and full dates.

I haven’t used friendly dates before in Windows, so I was wondering how much better you find them, instead of what is already available as “Relative” dates in Git Graph.

**Comment by yzhang-gh** [comment]
Oh, didn't notice we have this `relative` option and I feel it is better. Many thanks.

**Comment by mhutchie** [comment]
I’ll create documentation on the wiki of what settings are available in Git Graph, and provide examples of each. Currently there is only a list of the settings and short descriptions in README, which is definitely insufficient and hard to discover.

**Comment by yzhang-gh** [comment]
And also there is a `enumDescriptions` property you can make use of. VSCode will show the description in the settings GUI.

![enumDescriptions](https://user-images.githubusercontent.com/7588612/55362630-7556d100-54d2-11e9-9503-6c0f02c312a4.gif)

**Comment by mhutchie** [comment]
Thanks @yzhang-gh! I hadn't worked out how to add those descriptions. I'll add them as well.
