### ISSUE TITLE
Allow to position branch and tag labels to the right of the commit message

### ISSUE THREAD

**Issue by rherrmann** [mhutchie/vscode-git-graph#441]
There is a setting in _Git-graph_ > _Reference Labels_ > _Alignment_ to customize the position of branch and tag labels in the _Description_ column. 

Allow to position branch and tag labels to the right of the commit message like this:

| Graph | Description | Date | ...
| --- | --- | --- | ---
| o | Some other commit message [some-other-branch] [some-other-tag] | 2020-12-...
| o | Some commit message [some-branch] [some-tag] | 2020-12-...

...so that the beginning of commit messages would align vertically.

Rather than the existing choice _Normal_ there could be a choice for _Branches & Tags on the Left_ and _Branches and Tags on the Right_ instead. Would that make sense?

**Comment by mhutchie** [comment]
Hi @rherrmann,

Thanks for raising this improvement request!

When I implemented this extension setting, I did initially include this as another option while testing it. However, I found this made the graph extremely hard to use as the branch labels became so distanced from the graph, that it was really hard to see which labels aligned to which commit dots in the graph (quite important to accurately know). After getting feedback from other users, they felt similarly and we ultimately decided that it shouldn't be included as an option so I removed it before it was released. We felt that the majority of users would feel the same way, and would likely switch back to one of the three current options after using it.

We did make sure that the "Branches (aligned to the graph) & Tags (on the right)" was included, so that users who wanted commit messages to align vertically would have an option to achieve this. By aligning the branch labels to the graph instead, and moving tags to the right, it maintained the ease-of-use of seeing branch labels close to commit dots in the "Graph" column, while also still allowing commit messages to be aligned vertically.

I'll close this request for now, as although in theory it makes sense to have, in practice it was found to be quite hard to use. If there was significant interest in the option, it would be easy to include, however there would have to be a really good justification for including it given the usability issues it was observed to introduce.
