### ISSUE TITLE
UI is distorted

### ISSUE THREAD

**Issue by ginomempin** [mhutchie/vscode-git-graph#442]
**Describe the Bug**

When opening the Git Graph tab, the UI is distorted.

![Screen Shot 2020-12-21 at 8 59 46](https://user-images.githubusercontent.com/6091865/102727764-1f435480-436b-11eb-897b-fc7580cd81de.png)

I'm not sure if this is exactly related to Git Graph, but **no other tabs/panels are showing this problem**.

The Git Graph logs in the Output tab does not show anything wrong:

```
[2020-12-21 08:59:12.535] Starting Git Graph ...
[2020-12-21 08:59:12.571] Using /usr/local/bin/git (version: 2.29.2)
[2020-12-21 08:59:12.579] > git rev-parse --show-toplevel
[2020-12-21 08:59:12.579] Showing "Git Graph" Status Bar Item
[2020-12-21 08:59:12.580] Started Git Graph - Ready to use!
[2020-12-21 08:59:12.598] Searching workspace for new repos ...
[2020-12-21 08:59:12.598] Completed searching workspace for new repos
[2020-12-21 08:59:17.103] Created Git Graph View
[2020-12-21 08:59:17.319] > git branch -a --no-color
[2020-12-21 08:59:17.322] > git remote
[2020-12-21 08:59:17.325] > git reflog --format=... refs/stash --
[2020-12-21 08:59:17.332] Started watching repo: /path/to/my-test-repo
[2020-12-21 08:59:17.342] > git log --max-count=301 --format=... --date-order --branches --tags --remotes HEAD --
[2020-12-21 08:59:17.345] > git show-ref -d --head
[2020-12-21 08:59:17.355] > git status --untracked-files=all --porcelain
```

**Steps to Reproduce**

I'm not really sure how to reproduce this.. sorry :(
This is from a fresh bootup of my machine and after just opening VS Code. (No new system updates or installations.)  
It's a Monday as I'm posting this, and the last time I used Git Graph was on a Friday, and it was all working well.

1. Open VS Code
2. Open the Git Graph tab

**Environment**

 - macOS Catalina 10.15.7
 - Git Graph Extension Version: 1.28.0
 - VS Code Version: 1.52.1
     - Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
     - Date: 2020-12-16T16:30:02.420Z
     - Electron: 9.3.5
     - Chrome: 83.0.4103.122
     - Node.js: 12.14.1
     - V8: 8.3.110.13-electron.0
     - OS: Darwin x64 19.6.0
 - Color Theme: [Dracula Official](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula)

**Comment by mhutchie** [comment]
Hi @ginomempin,

I've had another user report a similar distortion a week ago in #433.

After inspecting some of the coloured artefacts in the screenshot you provided, I've spotted many features that make it impossible for this to be caused by CSS styles, or anything from within the extension's control. Therefore, I'm confident it's not caused by Git Graph. The other Git Graph user who reported the distortion raised it just after Visual Studio Code 1.52.0 was released, and you've reported this after Visual Studio Code 1.52.1 was released (which was last Friday). Considering the timing matches up with a Visual Studio Code release, it seems highly likely to me that it's some hardware compatibility bug introduced in a recent Visual Studio Code release.

After having a quick look at the Visual Studio Code GitHub repository, other users are reporting similar distortions with very similar blue artefacts in this issue https://github.com/microsoft/vscode/issues/69665#issuecomment-740928211. In the screenshot in the linked comment, the artefacts are shown over other parts of the Visual Studio Code interface, ruling out that this has anything to do with Git Graph. Reading some of the other comments in the linked Visual Studio Code issue, there are some suggested Visual Studio configuration changes that may help you to resolve this issue.

**Comment by ginomempin** [comment]
Sorry for not checking for existing issues.

I got it (magically) fixed now, by just doing a clean shutdown and boot-up (not from suspend mode).  

1. Close all VS Code workspaces and windows
2. Quit VS Code (as in CMD+Q quit)
3. Shutdown
4. Boot-up
5. Reopen VS Code and reopen workspace
