### ISSUE TITLE
Empty diff file list after Win7 update

### ISSUE THREAD

**Issue by ntrf** [mhutchie/vscode-git-graph#445]
Git graph extension stopped showing file lists for commits for me for no apparent reason. After a bit of debugging i figured out that git-diff always return empty list, except the initial commit and the working directory. Looks like `^` symbols are ignored in command line. This behaviour was either caused by a recent critical security update for Window 7 (yes, MS still publishes them even though support was officially ended) or by some change in Node.js runtime, which broke arguments quoting. I've tried different versions of Git so that's out of the question. No such problem on Win10 laptop. The commands are:

```
> git diff --name-status --find-renames --diff-filter=AMDR -z 960ed7eb8e0de1c7b7c2b2a4499d54a8d036e4e5^ 960ed7eb8e0de1c7b7c2b2a4499d54a8d036e4e5
> git diff --numstat --find-renames --diff-filter=AMDR -z 960ed7eb8e0de1c7b7c2b2a4499d54a8d036e4e5^ 960ed7eb8e0de1c7b7c2b2a4499d54a8d036e4e5
```

I've figured out a few workarounds:

* quoting the commit number as `"960ed7eb8e0de1c7b7c2b2a4499d54a8d036e4e5^"` or
* replacing `^` with `~1` as `960ed7eb8e0de1c7b7c2b2a4499d54a8d036e4e5~1`.

**Comment by mhutchie** [comment]
Hi @ntrf, This is quite unusual!

When Git Graph runs Git commands, it spawns them in a child process (bypassing the shell). This means the extension doesn't need to handle quoting arguments, or preventing arbitrary code execution, as spawned child processes naturally handles it as it bypasses the shell. This means that from the extensions perspective, it just pass an array of strings as the arguments to the child process.

> Looks like `^` symbols are ignored in command line.

This is true even when using the Command Prompt on Windows 10. When using the Command Prompt, quoting is required - unlike spawning child processes (which bypasses the Command Prompt and doesn't require quoting).

> quoting the commit number as `"960ed7eb8e0de1c7b7c2b2a4499d54a8d036e4e5^"`

I've tried putting quotes around the contents of this array element (argument) that is passed to the spawned Git child process, and because `spawn` bypasses the shell, the quotes are passed through to Git. Git then throws an exception as the quotes cause it to become an "unknown revision" (as expected). Unfortunately this is not something I can leverage in the extension.

> replacing `^` with `~1` as `960ed7eb8e0de1c7b7c2b2a4499d54a8d036e4e5~1`.

These symbols have a different meaning when considering other parents that aren't the first. `<commit-hash>^n` means the nth parent, whereas `<commit-hash>~n` looks back through the commit's ancestry `n` commits via first parents (i.e. `<commit-hash>~2` would return a grandparent of the commit, not the second parent). Although the extension currently only uses `^` to refer to the first parent (and doesn't need to reference nth parent), a feature scheduled for the next release will all users to switch the Commit Details View to show the difference to any parent (not just the first). Both of these factors also makes this not something I can leverage in the extension.

The best I can recommend is that you update Visual Studio Code to at least 1.49 (to ensure you're using the latest Node.js runtime), and update Git to the latest version.

I'll close this issue for now, as unfortunately I don't think there's anything I'm going to be able to do in the extension to resolve this - as accessing the nth parent of a commit via `<commit-hash>^n` is a fundament Git capability that's pretty unavoidable. You'll face this same issue in other Git extensions in Visual Studio Code, and likely other Git UI's, that leverage this capability.

However, please let me know if making the updates I suggested had any impact. I'm happy to help in any way I can to resolve / work-around this compatibility issue, if you have any other ideas based on the additional information I provided in this response.

**Comment by ntrf** [comment]
Ok, i've figured it out. The root of the problem was in the way git was installed on my PC. Back in 2008, when i first installed git on my machine, it was only usable in bash, so one had to generate file `git.bat` to make it visible in regular console through PATH variable. Over all these years i've never updated that file. As it turned out `.bat` scripts do process caret symbols as escapes for their arguments.

I've changed vscode setting `git.path` to use `git.exe` directly and that solved the problem. I strongly doubt there will be anyone else with such setup.

> <commit-hash>^n means the nth parent, whereas <commit-hash>~n looks back through the commit's ancestry n commits via first parents

I'm not suggesting replacing all of them. In that particular instance (https://github.com/mhutchie/vscode-git-graph/blob/develop/src/dataSource.ts#L345) you're only using `^` without number, which does take the first parent and should be an equivalent of `~1`. As i've said -- it's a workaround.

> I've tried putting quotes around the contents of this array element (argument) that is passed to the spawned Git child process, and because spawn bypasses the shell, the quotes are passed through to Git.

I've tested that with a simple C++ program, that called git through `CreateProcess` call and i've had no issues. I should have checked it with js. I'm going to guess node does something with quotes internally.

There is still no explanation why this problem was only surfaced recently, but it might has to do with "application compatibility service", which i've recently disabled on my system due to high occasional CPU load generated by that service. 

Anyway, i think we're done here.

**Comment by mhutchie** [comment]
Hi @ntrf,

I'm glad you were able to resolve this! Thanks for letting me know your findings, it's really useful for me to know if anyone else faces similar issues!

> I've tested that with a simple C++ program, that called git through CreateProcess call and i've had no issues. I should have checked it with js. I'm going to guess node does something with quotes internally.

I've come across several differences with the Node.js Child Process library compared to other languages I've worked with in the past (when invoking other processes). This would definitely explain why your C++ program behaved differently (correctly) compared to its Node.js equivalent.
