### ISSUE TITLE
The graph is wrong

### ISSUE THREAD

**Issue by gbreeze** [mhutchie/vscode-git-graph#447]
**Describe the Bug**
The branch is merged to the "head", but the graph does not show that. 

**Expected Behaviour**
![image](https://user-images.githubusercontent.com/1906169/103526829-c226c300-4e81-11eb-8537-3d34d6ea12ab.png)

**Environment**
- latest

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/1906169/103526694-960b4200-4e81-11eb-96e5-dedef95cfadf.png)

**Comment by mhutchie** [comment]
Hi @gbreeze,

Lines in the graph can only be drawn between commits that are loaded in the Git Graph View. The commit "Merge branch 'CAS-283-Console-errors' into ..." doesn't appear in the screenshot you've provided, so naturally no line can be drawn to it. There are two highly likely reasons that the merge commit may be not included in the commits loaded in the Git Graph View:
* You've inadvertently filtered out the line of history that contains the merge commit (e.g. in the "Branches" dropdown, the checkboxes in the Repository Settings Widget, or one of the filtering extension settings).
* In large repositories, the order of commits could affect which commits are loaded in the Git Graph View. You can set your preferred order using the extension setting `git-graph.repository.commits.order`, or on the right-click context menu on the Column Headers.

If this is not the case, please provide a screenshot that shows both the "Merge branch 'CAS-283-Console-errors' into ..." commit, and the commit referenced by the "CAS-283-Console-errors" branch, so I can see that there is no line drawn between the two commit dots in the graph, and have some means to recreate your scenario. If the repository is public, it would be great if you can include a link to it, or create a simple example repository that replicates the behaviour you're observing.

I'll close this bug report for now, as although it's possible that the graph rendering algorithm contains a bug, in over 900,000 users and almost two years of the extensions existence, no other users have ever reported any such bugs (if it were a bug, it's extremely unlikely that no-one has reported such a fundamental bug). The graph is extremely well tested both pre-release & in the real-world in millions of repositories globally, and the logic hasn't changed since the first release. Of course though, if you can provide the requested screenshot to confirm that a line is missing between two dots in the graph, I'll promptly re-open this bug and work to fix it asap.

**Comment by gbreeze** [comment]
Hi Michael, thanks for your help! I understand the issue now.

The information "This commit is **not** included in HEAD" is still a little bit misleading to me. 
![image](https://user-images.githubusercontent.com/1906169/103535168-93641900-4e90-11eb-8364-b998a6937cb4.png)

If I disable "Only follow the first parent of commits" I have the correct information. 
Thanks!

**Comment by mhutchie** [comment]
Hi @gbreeze,

Thanks for letting me know that you’ve been able to understand what’s occurring!

The tooltips in the graph can only be based on topologically traversing the loaded commits and their parents (and children inferences), as the extension is only aware of the loaded commits. The “Only follow the first parent of commits” filter is the only filter that has the potential to make the tooltip information about a commit’s inclusion / exclusion in the HEAD misleading, as by enabling this filter you’re deliberately instructing Git (and the extension) not to load some commits. By excluding these commits, it inhibits the ability for topological analysis of the commits by the extension.

I’ll have a think about what I can do to make this clearer (and implement it), so hopefully no other users will face similar confusion in the future.
