### ISSUE TITLE
Refresh the UI even when a post-checkout hook failed

### ISSUE THREAD

**Issue by JanVoracek** [mhutchie/vscode-git-graph#449]
**Describe the Bug**
The UI doesn't refresh when a Git post-checkout hook fails. Also, the dialog says that it was "Unable to Checkout Branch".

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Create a post-checkout hook (`.git/hooks/post-checkout`), e.g.
```sh
#!/usr/bin/env sh

echo "Some error message from the post-checkout hook"
exit 1

```
2. Checkout some branch
3. See a dialog saying "Unable to Checkout Branch"
4. Dismiss the dialog
5. See that the UI didn't refresh

**Expected Behaviour**
Actually, the branch was checked out. Git Graph should just display the output of the hook.

The [Git documentation](https://git-scm.com/docs/githooks#_post_checkout) says:
> This hook cannot affect the outcome of git switch or git checkout, other than that the hook’s exit status becomes the exit status of these two commands.

**Environment**
 - Git Graph Extension Version: 1.28.0
 - Visual Studio Code Version: 1.52.1
 - Operating System: macOS 11.1

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/703215/104316415-b8820880-54dc-11eb-9c22-e9c5a7d9afac.png)

**Comment by mhutchie** [comment]
Hi @JanVoracek,

When the extension runs a Git command for any of the available actions, it checks the returned status code to determine if it was successful, or if an error occurred. If the Git command was successful, it will refresh the view, otherwise (when error occurs) it will display the error message in a dialog (however it won't refresh the view). This is fine for the vast majority of errors, because if the Git command failed, nothing has actually changed in the repository so there is no need to refresh the view. However, this is definitely not ideal when `post-<action>` hooks fail. There are numerous reasons why in the general case, the view shouldn't refresh when a Git command fails.

Unfortunately, Git's output does not distinguish between when the Git command failed, and when a hook failed, as the Git command exits with the failure status code of the hook. Therefore the best the extension can do is to clearly communicate what occurred, so the user can take the appropriate action (and refresh the view if necessary). In the example you provided, the following dialog is shown, which clearly outlines what has occurred.
![image](https://user-images.githubusercontent.com/5315753/104319031-62d94a80-5534-11eb-8b57-6a7cad67b85f.png)

Additionally, the name of all error dialogs is "Error: Unable to `<name of the action the user requested>`" (e.g. "Error: Unable to Checkout Branch"). In this case, Git returned a status code indicating the branch couldn't be checked out, so the extension was unable to perform the "Checkout Branch" action. I definitely understand that in this specific case the standard naming is somewhat confusing.

The extension runs over 50 different Git commands, and each can fail in many different ways, so it's simply not feasible to provide the perfect response to every single Git error, even though I would definitely like to. The standardised approach the extension has taken (outlined in my first paragraph) was chosen as it works almost perfectly for almost all Git errors.

Although it would definitely be nice to improve the handling in this specific case, it's just not feasible to achieve this, as I would have to support all of the possible Git hooks across many Git commands (not just post-checkout). This would: require a significant amount of work to implement, still not be a perfect solution, and only benefit a relatively small portion of users. At the moment it's beyond the scope of the extension, however possibly in the future it will be implemented in some form, so I'll close this improvement request for now and move it to the backlog.
