### ISSUE TITLE
Ctrl+Tab away from git graph prevents copying of code problem message

### ISSUE THREAD

**Issue by MetRonnie** [mhutchie/vscode-git-graph#453]
**Describe the Bug**
This is a subtle one.

If I <kbd>Ctrl</kbd>+<kbd>Tab</kbd> from the extension tab to an editor tab which has "problems" identified by a linter/language server, I can't copy the problem message from the hover/peek problem dialog. I can only copy the message if I click on the editor tab instead of using <kbd>Ctrl</kbd>+<kbd>Tab</kbd>.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Have a repo or workspace with an editor tab (i.e. a code file open) and the git graph tab open. 
2. Make a "problem" in the code, e.g. unused variable or undefined variable that gets picked up as a warning/error by a linter/language server and underlined with a squigly line.
3. Go to the git graph tab.
4. Use <kbd>Ctrl</kbd>+<kbd>Tab</kbd> to switch to the code file again.
5. Hover over the squigly line and when the hover dialog appears with the linter problem, try to select and <kbd>Ctrl</kbd>+<kbd>C</kbd> the message (or click on "peek problem" and try the same).

**Expected Behaviour**
The text you select should be copied to the clipboard.

**Actual Behaviour**
Nothing gets copied to the clipboard.

**Environment**
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 3.10.0-1160.11.1.el7.x86_64
```

**Screenshots (optional)**

Here's what I mean by selecting text from the problem message:

![image](https://user-images.githubusercontent.com/61982285/105343425-8574fe80-5bd9-11eb-9a1a-4ce7cddb0f38.png)

**Additional Context (optional)**
- If I explicitly click on the editor tab instead of using <kbd>Ctrl</kbd>+<kbd>Tab</kbd>, then I get the expected behaviour.
- I have tried <kbd>Ctrl</kbd>+<kbd>Tab</kbd>ing from other editor tabs to the one with the problem, and I get the expected behaviour - the bug only seems to occur for tabbing away from git graph
- Could this be a keyboard focus issue?

**Comment by mhutchie** [comment]
Hi @MetRonnie,

After following the steps you provided, I can replicate this behaviour, and it occurs any time the user `Ctrl` + `Tab`'s away from any extension-contributed [Visual Studio Code Webview](https://code.visualstudio.com/api/extension-guides/webview). The Git Graph View uses a Webview to render it's content, along with many other extensions. I was able to replicate this bug with the Webview's of multiple other extensions - i.e. this is not a bug with Git Graph, it's a bug with Visual Studio Code, that affects many extensions.

I expect this bug was introduced in a recent Visual Studio Code release. Please raise this as a bug in the [Visual Studio Code](https://github.com/microsoft/vscode) GitHub repository, so Microsoft can fix it in one of the next releases. Please title the bug as "Unable to copy code problem message after Ctrl+Tab from an active Webview", describe the behaviour you observed (highlighting that it affects all extensions that use Webview's, not just Git Graph), link to this issue, and mention my GitHub handle. I can help provide additional information if necessary.

There have been numerous Visual Studio Code keyboard shortcut bugs extremely similar to this over the last two years.
