### ISSUE TITLE
Chromium zoom issue causing graph nodes to become misaligned with commits

### ISSUE THREAD

**Issue by ShoshinNikita** [mhutchie/vscode-git-graph#46]
**Describe the bug**

The graph shifts with non-zero `window.zoomLevel`

**What does the bug relate to**

- Graph Rendering

**To reproduce**

1. Change `window.zoomLevel` with `Ctlr+=` or `Ctrl+-`

**Screenshots**

`"window.zoomLevel": 0`

![zoom_0](https://user-images.githubusercontent.com/30220965/55430854-c4b30500-5597-11e9-9356-85de81b6226a.png)

`"window.zoomLevel": 1`

![zoom_1](https://user-images.githubusercontent.com/30220965/55430892-dc8a8900-5597-11e9-9762-93b65aba10c1.png)

**Environment**
 - OS: Windows 10
 - Visual Studio Code Version: 1.32.3

**Note**

I don't think it is a problem of **vscode-git-graph**. Rather it is a problem of Electron and Chromium.

**Comment by mhutchie** [comment]
This is a bug caused by Chromium zooming, even though each row in the table has a height set to 24px, when the page is zoomed each row in the table increases/decreases in height by a small amount (e.g. 24.31px), which accumulates over many rows in the table. The graph currently assumes table rows are 24px in height, which should be the case. I'll need to work out the best way to relax this assumption when rendering the graph in order to correct this.

**Comment by mhutchie** [comment]
This will be available in v1.4.5.

If you'd like to use it before the next release, you can download [v1.4.5-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.4.5-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
