### ISSUE TITLE
git graph cannot search commit msg after double LF line feed/next-line

### ISSUE THREAD

**Issue by elliotching** [mhutchie/vscode-git-graph#468]
**Describe the Bug**
For example I have a git commit that is following commit message:
```
update breadcrumb

init sha256
init forgot component
```

When I search the keyword 'init' , 'sha' and so on..., git graph cannot found my commit.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Simply make a git commit with message that contained double (enter)/(carriage-return)/(line-feed)/CRLF/LF
2. Try search a keyword that is only occur after double LF (No result found) 

**Expected Behaviour**
Git graph should point highlight cursor to the commit that I searched, but "No result found instead"

**Environment**
 - Git Graph Extension Version: [e.g. 1.13.0]
 - Visual Studio Code Version: [e.g. 1.37.1]
 - Operating System: [e.g. Windows 10]

**Comment by elliotching** [comment]
screenshot
![Screenshot 2021-02-26 192405](https://user-images.githubusercontent.com/20972678/109294533-45540c00-7868-11eb-9e68-a34893fad527.png)

**Comment by mhutchie** [comment]
Hi @elliotching,

This is actually the expected behaviour for several reasons, however I can definitely understand the confusion (and a solution may potentially be implemented in the future).

---

Git has the notion of `subject` and `body` in commit messages. Git obtains each of these field from the commit message, such that the `subject` is all the text until the first double new line, and the `body` is everything after the first double new line.

In your example:
```
update breadcrumb

init sha256
init forgot component
```

Subject: `update breadcrumb`

Body:
```
init sha256
init forgot component
```

In the Git Graph View, when it runs the Git command to fetch the commit information to display for all commit table rows, it only fetches the subject of the commit (not the body). You can see this in your screenshot for f08f689b, as only the subject "update breadcrumb" is shown in the description column of the Git Graph View (not the body). It's only when you click on a commit to view the Commit Details View that more details for the specific commit are fetched from Git, including the full commit message (subject + body), which is displayed on the left hand side of the Commit Details View. This behaviour is consistent with the vast majority of Git UI's, and there are numerous reasons why this behaviour is used.

The Git Graph View's Find Widget searches through all data already fetched and displayed in the commit table rows. This means it only has access to the subject of each commit, so the Find Widget will only produce matches where the criteria (e.g. "forgot") is in the subject of the commit (because it doesn't know what the body of each commit is as it hasn't been fetched from Git).

---

However, I definitely understand that it would be useful to be able to search the full commit message (subject + body), and there are numerous use cases where it would be the preferred behaviour. Although at the moment the current behaviour is all that can be made available, there is currently a big initiative that I'm working on to expand the filtering and find capabilities of Git Graph. This feature could quite possibly be feasible after the majority of this initiative is implemented. I'll change this to a feature request, and move it to the backlog for now - however once the filtering and find initiative is nearing completion, I'll reassess this feature to see if it is feasible to implement.
