### ISSUE TITLE
Add a menu to view diff for one file using external diff tool

### ISSUE THREAD

**Issue by zhanghnet9** [mhutchie/vscode-git-graph#469]
Can add a menu to view diff for one file using the difftool settings in git config (e.g. view diff in Beyond Compare)?
I saw this extension has support "Open External Directory Diff"

![image](https://user-images.githubusercontent.com/44537377/109502459-fca08b00-7ad3-11eb-9dd2-6991a6cebb82.png)

**Comment by mhutchie** [comment]
Hi @zhanghnet9,

Thanks for raising this feature request!

I added "Open External Directory Diff" in the latest Git Graph release, as it:
* Offers a completely new capability (from the diff tool) that is not closely available in Visual Studio Code or Git Graph.
* It is a single step that some users have as part of their workflow.

As Git Graph is an extension for Visual Studio Code, if a capability exists in Visual Studio Code I typically always use it instead of implementing it myself, or directing users to an alternative way of doing it (outside of Visual Studio Code). The only time I've made exceptions to this in the past have been if the Visual Studio Code offering is unlikely to ever support a certain capability that Git Graph users deem to be critical. If users don't like some portion of the Visual Studio Code offering, I typically get them to instead raise it as a feature request in https://github.com/microsoft/vscode, so all Visual Studio Code users benefit from it (not just those that use Git Graph).

Would you please let me know what functional value is added by giving users the option to use an external diff tool to view a file, instead of Visual Studio Code's? (i.e. why is the Visual Studio Code diff tool insufficient)

If this was to be added, would you ever have a need to use the "View Diff" action (the Visual Studio Code equivalent)? (i.e. should "View Diff" be replaced with the action you've proposed in this feature request, or would you still want to see both)

**Comment by zhanghnet9** [comment]
Hi @mhutchie ,

Supposing the new menu is "View Diff using DiffTool", I want see both "View Diff" and "View Diff using DiffTool". Currently the "View Diff" menu is very quick and convenient. But the Visual Studio Code diff is not very clear if many codes are changed in one file. Then I will use "View Diff using DiffTool" to use other tool (e.g. Beyond Compare) to see the changes.

After reading your explanation, I agree this requirement is a low priority. You can close this issue. This can be added if there are many similar requirements in future.

Anyway, thank you for this awesome extension.

**Comment by mhutchie** [comment]
Thank you for your responses!

I'll close this feature request for now and move it to the backlog (for the reasons in my previous comment).

Note to other users reading this in the future: If you'd like this functionality, please reply to this thread to express your interest. I'd happily re-open and implement this feature if there is enough of an indication that it would be used & valued by a decent number of users.

**Comment by TheGag96** [comment]
> Note to other users reading this in the future: If you'd like this functionality, please reply to this thread to express your interest. I'd happily re-open and implement this feature if there is enough of an indication that it would be used & valued by a decent number of users.

I'm interested in such a feature.
