### ISSUE TITLE
Github trusted extension support?

### ISSUE THREAD

**Issue by davidlin409** [mhutchie/vscode-git-graph#477]
**Describe the feature that you'd like**
A clear and concise description of what you'd like to be included in Git Graph.

In newer version of Visual Studio Code, there is an ability for Visual Studio Code APP to connect to Github directly. After that, all Git related operation are authenticated by Visual Studio Code. An extension called "[GitLen](https://gitlens.amod.io/)" uses this feature, such that password-less Git operation on Github remote is possible.

Is there a chance that this extension also join Github trusted extension in Visual Studio Code?

**Additional context (optional)**

**Comment by mhutchie** [comment]
Hi @davidlin409,

Thanks for raising this feature request!

As a Visual Studio Code extension developer, I always closely monitor all new capabilities made available in Visual Studio Code and for extensions. Whenever Visual Studio Code releases new capabilities in their API, there is a delay before extensions can feasibly use it, as extensions must set the minimum version of Visual Studio Code they require to operate - and can only use what's available in the minimum version. By upgrading the minimum Visual Studio Code version requirement of an extension too soon, it prevents all extension users who use older versions of Visual Studio Code from installing or receiving updates to the extension. I have to carefully consider whether the value added by utilising a new capability out-ways the complete write-off of value for all users with older versions of Visual Studio Code.

Authentication Providers (including GitHub) were only made available for extensions in Visual Studio Code 1.48.0 (July 2020). Unfortunately at the current time, there is still a significant portion of Git Graph users who use Visual Studio Code < 1.48.0, who would stop receiving all future updates to Git Graph if I were to upgrade the minimum Visual Studio Code version requirement. Additionally, at the current time there is not enough value added by Authentication Providers to outweigh losing so many users.

I'll close this feature request and move it to the backlog for now. In the future, I'm sure this will be re-opened and implemented in Git Graph, but now isn't the right time to do so.

FYI: Some extensions chose to only support the very recent Visual Studio Code releases in order to leverage the latest Visual Studio Code capabilities. This has several merits, however I ultimately have decided to try to balance this trade-off to provide the most net value to all users.

**Comment by mill1000** [comment]
I would like to see this get more priority, especially with GitHub's move to disallow password based authentication in favor of PATs. I find myself in situations where the integrated SCM commands are authenticated, git commands in the integrated terminal are also authenticated (via VScode) but Git Graph is not.

This always seems to happen when I want to "quickly" fix something so going to generate a PAT is not ideal.
