### ISSUE TITLE
Add integration with GitLab Workflow extension

### ISSUE THREAD

**Issue by Igorgro** [mhutchie/vscode-git-graph#481]
**Describe the feature that you'd like**
When pushing to remote GitLab repository on bare Visual Studio Code on Linux using https protocol, it asks for credentials. If the Gitlab Workflow is installed it performs some actions (most probably it uses access token), so if I push using regular vscode push command (Source control -> three dots menu -> Push), there is no need to enter credentials. But if I push using Git Graph extension, it still ask for credentials. I think it it is possible to reimplement git push command so that it works similar to the one in regular vscode. It is hard to say is it a bug or unimplemented feature.

**Comment by mhutchie** [comment]
Hi @Igorgro,

I've investigated how "GitLab Workflow" is providing credentials for the built-in Visual Studio Code Git Extension. The built-in Git extension has an API that exposes a `registerCredentialsProvider(provider: CredentialsProvider): Disposable;` method, which allows other extensions to provide credentials for it to use. In your case, "GitLab Workflow" is registering a credential provider, that provides the built-in Git extension with your GitLab credentials. Unfortunately, the built-in Git extension does not expose the credentials provider's that have been registered with it (so Git Graph can't retrieve the registered credentials & use them). Additionally, from what I can see "GitLab Workflow" only exposes the credentials in this way, so there isn't a way to fetch them from the extension directly.

Visual Studio Code has been making some great progress with Authentication Providers, which allow extensions to register themselves as an authentication provider. This allows all other extensions to utilise the authentication provider. This is completely different to how "GitLab Workflow" is doing it. I'm hopeful that the Visual Studio Code Authentication Provider API will be expanded in the future, and become common place in Visual Studio Code - and ultimately solve the friction you're currently having.

---

The credential prompts that you receive when interacting with a GitLab remote come from Git Graph's integration with Git Askpass (which is Git's way to request credentials from a user that it doesn't already know).

Unlike Windows & Mac, Linux doesn't appear to have a widely used long-term credential helper. On Windows & Mac, these credential helpers store the username & password so that the user doesn't need to keep entering them.

Although I don't personally do any development work on Linux that requires interacting with remote repositories, I'm aware of the following options (there may be others if you Google it):
* Use the built-in caching credential helper `git config --global credential.helper 'cache --timeout=3600'`, where you can set the number of seconds the credentials should be cached (this doesn't persist across computer restarts). By setting a long timeout, this could potentially reduce the number of credential prompts you get.
* Use an SSH key to authenticate with GitLab. You should first run a Git command in a terminal that interacts with the remote, to ensure the SSH Key is working correctly, and respond to any one-time SSH prompts. Afterwards, Git will automatically use the SSH key to authenticate with GitLab (no username / password required) - including when Git commands are run by Git Graph. I think I remember some users having difficulty configuring SSH key's with passphrases - so if you don't need to use a passphrase (set when creating the SSH key), that would likely simplify the configuration process for you.

---

I'll close this feature request and move it to the backlog for now, as at the current time there isn't a way for any other extensions (aside from the built-in Git extension) from consuming & using the credentials from "GitLab Workflow". However, once credential & authentication providers are further developer and become widespread in the Visual Studio Code ecosystem, and it does become possible to use credentials from "GitLab Workflow", I definitely intend to re-open and implement this feature request.
