### ISSUE TITLE
Add "Unassigned" option for Keyboard Shortcuts

### ISSUE THREAD

**Issue by aNickzz** [mhutchie/vscode-git-graph#486]
**Describe the improvement that you'd like**
To be able to configure this extension's keyboard shortcuts with the rest of the shortcuts in vscode.

**Additional context (optional)**
I've rebound `ctrl + r` to "open recent" for as long (as I can remember as it seems more useful to me than "reload window"). However, this keybinding doesn't work if the Git Graph tab has focus. The same goes for `ctrl + k, ctrl + s` which gets picked up by Git Graph to highlight the stash. 

This work seems related to, and could probably be done alongside #484.

**Comment by mhutchie** [comment]
Hi @aNickzz,

All keyboard shortcuts available in the Git Graph View can be customised with the [Keyboard Shortcuts](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#keyboard-shortcuts) extension settings, so you can chose alternatives that don’t clash with any Visual Studio Code Keybindings you have.

Due to the nature of how keyboard shortcuts are implemented with Visual Studio Code Webview’s (which is used for the Git Graph View), it’s unfortunately not feasible to centrally manage the Git Graph View’s keyboard shortcuts in the Visual Studio Code Keyboard Shortcut View.

I’ll close this improvement request as I believe the functionality you’re requesting is already available via the extension settings.

**Comment by aNickzz** [comment]
Thanks for the info. In that case, would it be possible to add an option to unbind a shortcut?
At the moment if I don't choose one of the ctrl+letter bindings (eg. setting the binding to `""`) I get a warning saying the setting is invalid and the binding reverts to default. For now, I've set the binding to ctrl+z which I'm unlikely to press when the graph is open.

**Comment by mhutchie** [comment]
I'll add an "Unassigned" option for each of these Keyboard Shortcut extension settings, so you can chose not to have a keybinding.

I'll implement this tonight, so it will be included in the next release.

**Comment by mhutchie** [comment]
This will be available in v1.30.0.

If you'd like to use it before the next release, you can download [v1.30.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.30.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
