### ISSUE TITLE
Pull Request Creation incorrect URL

### ISSUE THREAD

**Issue by RAYDENFilipp** [mhutchie/vscode-git-graph#487]
When I use the setting-menu for creating GitLab pull requests, I get a weird URL.
Consider the following setting
![image](https://user-images.githubusercontent.com/24476415/111500217-69f72180-874c-11eb-8534-22774f1e7494.png)
![image](https://user-images.githubusercontent.com/24476415/111500240-6f546c00-874c-11eb-946c-cb9bc2d4867e.png)
I get the following URL
`https://git.sami.int.thomsonreuters.com/collab-eikonmessenger/messenger-ui/-/merge_requests/new?merge_request%5Bsource_branch%5D=feature/CLP-286/limit-number-of-blasts&merge_request%5Btarget_branch%5D=develop`

Specifically, the `.../messenger-ui/-/merge_requests/...` - dash breaks the URL leading to Gitlab's 404 response. Without it Pull request is created fine.

I couldn't find the exact setting that is affecting the URL. Seems like a bug.

Git-graph version v1.29.0
VSCode version 
![image](https://user-images.githubusercontent.com/24476415/111500670-e984f080-874c-11eb-8745-2a1c539f0fcb.png)

**Comment by mhutchie** [comment]
Hi @RAYDENFilipp,

Different versions of Bitbucket, GitHub and GitLab sometimes use slightly different URL’s for creating pull requests. As mentioned in the information tooltip to the right of the Provider field in your first screenshot “In addition to the built-in publicly hosted Pull Request providers, custom providers can be configured using the Extension Setting "git-graph.customPullRequestProviders" (e.g. for use with privately hosted Pull Request providers).”

The built-in GitLab provider (with the hyphen in the URL) is correct for the publicly hosted GitLab (I just double-checked it). It appears that on the version of GitLab hosted on the domain you specified, it doesn’t not use the same URL. In your situation, you just need to configure a Custom Pull Request Provider - I’ve produced [this wiki](https://github.com/mhutchie/vscode-git-graph/wiki/Configuring-a-custom-Pull-Request-Provider), to explain the relatively simple steps you need to do.

---

In case other users read this in the future to troubleshoot a similar problem, there is another possible cause that can result in the GitLab 404 Error Page. If you’re not logged into GitLab, and you directly access the URL to create a new pull request, you will get a 404 page, instead of being redirected to log in.

**Comment by RAYDENFilipp** [comment]
@mhutchie thank you very much!
