### ISSUE TITLE
Date doesn't account for timezone

### ISSUE THREAD

**Issue by dan1994** [mhutchie/vscode-git-graph#495]
**Describe the Bug**

From what I've seen, only the commit's timestamp is used to render the date (both in the table, and details view). This causes dates and times to be offset by the difference in timezones between the user and the commit's author.

**Steps to Reproduce**
1. Open any repo with a commit from a different timezone.
2. The commit's date should appear as if it was committed in the same hour but in your timezone.

**Expected Behaviour**
The timezone should be taken into account when formatting the date.

**Environment**
 - Git Graph Extension Version: 1.30
 - Visual Studio Code Version: 1.55.0
 - Operating System: Windows 10

**Comment by dan1994** [comment]
My bad, it appears the timezone is only needed if you want the hour at the original timezone.

**Comment by mhutchie** [comment]
The extension setting `git-graph.date.type` controls whether the date in the "Date" column is the author or committer date.

Currently the extension displays all times after conversion into the user's timezone, not the timezone of the author or committer. This is done so that at a glance all the dates make sense & appear in order, and the user doesn't have to deal with converting timezones in their head to work out the true relationships between different commits. When I first implemented this, it seemed this was the approach taken by the majority of Git UI's, and it was also much easier to implement.

**Comment by dan1994** [comment]
I agree with your approach, but had the impression that the conversation to the user's time zone was wrong, which was my mistake.
