### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by MatthewS2077** [mhutchie/vscode-git-graph#501]
GitGraph is great! Thanks for this extension! 👍

I use the _Customize UI_ & _Monkey Patch_ extensions to change the font for the VSCode UI in my settings.json as follows:-

```
"customizeUI.font.regular": "Roboto Light",
"customizeUI.font.monospace": "Roboto Mono Light",
```

However, GitGraph doesn't use this font, it still uses the default "Segoe" font.

Is it possible to make GitGraph use the same font as the rest of the VSCode UI, or even just use the editor font? 

Maybe an option?  🙏

**Comment by mhutchie** [comment]
Hi @MatthewS2077,

The Git Graph View uses the Visual Studio Code CSS variables defined in [Webview's](https://code.visualstudio.com/api/extension-guides/webview) to be themed consistently with Visual Studio Code. See [Theming Webview Content](https://code.visualstudio.com/api/extension-guides/webview#theming-webview-content) for more information.

There are only two font family CSS variables that are made available:
* `--vscode-font-family`: Is the font family used for anything that isn't code in Visual Studio Code.
* `--vscode-editor-font-family`: Is the font family used for the editors in Visual Studio Code (i.e. code files).

The Git Graph View is a user interface (not code), so it uses `--vscode-font-family` for all text (the only reasonable choice). This is the default / built-in behaviour for all Visual Studio Code Webview's.

If you do want to use the font defined with *Customize UI & Monkey Patch* in Webview's, it would be best to raise an improvement with them to integrate with these CSS variables. That way all Webview's (contributed by any extension) would automatically be styled with the custom defined font. (Otherwise every extension using Webview's would have to make the same style changes to be compatible with the non-standard way *Customize UI & Monkey Patch* are operating).

I'll close this improvement request for all the above reasons.
