### ISSUE TITLE
Find-function should scan non-loaded commit SHAs

### ISSUE THREAD

**Issue by HarveyKBrown** [mhutchie/vscode-git-graph#505]
**Describe the improvement that you'd like**
When using find, the utility should scan commit SHAs for unloaded commits (ones that are not currently in the range of loaded commits in the list)

**Additional context (optional)**
I need to find specific SHAs for reviews of specific code changes that introduce issues to the codebase I work on. These will often be commits well over a year old. When I use the find utility to look for a specific SHA I have to scroll back sometimes thousands of commits even on a specific branch to find what I need - its not feasable for me to use this app for this fairly significant part of my job without this function.

**Comment by mhutchie** [comment]
Hi @Validifyed,

This feature request is a duplicate of #245 & #358, please read my previous comments [here](https://github.com/mhutchie/vscode-git-graph/issues/245#issuecomment-572892126) and [here](https://github.com/mhutchie/vscode-git-graph/issues/358#issuecomment-670479464) respectively for more information on the current behaviour, why this capability isn't currently available in Git Graph, and a work-around you can do in the meantime.

Where I mention the potential option to "allow the user to specify a commit id instead of a branch in the Branches dropdown" - this is definitely coming soon, and seems to be the best solution (it avoids making the extension slower to load).

I'll close this improvement as it is a duplicate.
