### ISSUE TITLE
icon broken in source control

### ISSUE THREAD

**Issue by cusionline** [mhutchie/vscode-git-graph#506]
Issue Type: <b>Bug</b>

git graph icon is very very smaller than usual

Extension version: 1.30.0
VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 7, 5|
|Memory (System)|32.00GB (0.57GB free)|
|Process Argv|--crash-reporter-id 0898baf3-807b-473a-9d0d-da4a7b835e3a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30294352

```

</details>

**Comment by mhutchie** [comment]
Hi @cusionline, @iPherian and @skilkis

Please read [my response](https://github.com/mhutchie/vscode-git-graph/issues/502#issuecomment-833400201) to the open issue #502 (currently at the top of the open issues) - it is exactly the same as this, and clearly marked as a Visual Studio Code Bug (introduced in Visual Studio Code 1.56.0 yesterday).

@cusionline:
Even though it is a Visual Studio Code Bug, I left #502 open specifically so other Git Graph users who may be affected can see it, read it, know what’s going on, and track it getting fixed in the Visual Studio Code issue (https://github.com/microsoft/vscode/issues/123036). Please check the open issues before raising a duplicate, as it can mislead other users who don't see the response I already wrote (because your duplicate issue is newer than it). It also affects me: I'm writing this response at 5am, having to repeat exactly what I said yesterday. Please be mindful that any time there is a bug in Visual Studio Code, extension authors inevitably have to deal with a bombardment of messages from affected users, even though it's a bug that's in Visual Studio Code, and not their extension - it means instead of being able to work on our extensions, we have to spend all our time explaining Visual Studio Code's bug to our users.

**Comment by mhutchie** [comment]
Visual Studio Code 1.56.2 has been released, which includes the fix for this bug.

```
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041
```
