### ISSUE TITLE
Double click on a commit will checkout without a warning to commit staged changes 

### ISSUE THREAD

**Issue by elementalTIMING** [mhutchie/vscode-git-graph#510]
Today I've lost staged changes of more than 100 files. What happened?

1. stage changes
2. double click on a previous commit
3. the previous commit was checked out WITHOUT any warning that staged changes have not been committed yet

The effect is that the staged changes are gone lost and I need to the work again.

I'm using the latest version of VSCode and your extension.

**Comment by mhutchie** [comment]
Hi @elementalPRESS,

There is no double click action on commits themselves. The only double click action is on branch labels, which will check out the branch. However, if there are any local changes that would be lost, the underlying `git checkout` command throws an error, and this is then displayed to the user:
![image](https://user-images.githubusercontent.com/5315753/118193715-892fd800-b48b-11eb-9fe1-f4acdd4d7ba1.png)

Can you please try and replicate what you observed, and provide additional details? There definitely shouldn't be any way to lose local changes without a warning / error - that's why I specifically ensured & tested that Git throws an error, and Git Graph displays the error (seen in the above screenshot).

**Comment by mhutchie** [comment]
Additionally, every Git command that I'm aware of that has the ability to impact local changes (e.g. `git merge`), has these checks built into them, and throws an exception before proceeding. All Git exceptions triggered by actions are displayed to the Git Graph user via an error dialog. As Git intelligently does these checks on the impact to local changes, they're transitively built into  anything that uses them (e.g. directly via the command line, or software products) - this means that Git Graph doesn't need to do it's own checks on uncommitted files.

The only way I can get `git checkout` to discard local changes without throwing the error, shown in my previous screenshot, is to provide the `-f` force argument (but the extension definitely doesn't do this - [see here](https://github.com/mhutchie/vscode-git-graph/blob/77cdae7614747ce69ff5cbe2ab079817c4017d70/src/dataSource.ts#L847-L853)).

In addition to the question in my previous comment, what version of Git is Git Graph using on your computer? (You can check this by running the `Git Graph: Get Version Information` command in the Visual Studio Code Command Palette)

**Comment by mhutchie** [comment]
As the requested information hasn’t been provided, I’ve been unable to replicate it because it just doesn’t seem possible (for the reasons mentioned in my previous responses), and none of the other ~1.25 million users have ever reported it in over two years, I’ll close this issue for now. Based on everything I can see, there just doesn’t seem to be any mechanism in Git Graph that could have caused this.

I’m sorry you lost your uncommitted work.

If you’re able to provide a set of detailed steps that can be used to consistently replicate the behaviour you describe, please let me know, as I’d definitely want re-open this issue and fix it as soon as possible.
