### ISSUE TITLE
Add a link to the "remote path" in the node summary. 

### ISSUE THREAD

**Issue by danocharron** [mhutchie/vscode-git-graph#513]
Currently when you click a node (bubble) it brings up a summary. This summary does not include the "RemotePath".
It would be nice if it did. This way you can copy the node info and send it to another person (i.e. tester) and they have EVERYTHING they need to clone and test this code. 

RemotePath: http://somewhere/repos/someproject.git          <---- Please add this !!!
Commit: 5680790c9c222975fd009c70911e07ad795cf991
Parents: fa237f5852dbcd68808cde6a556b19ce7e73a0ba
Author: Joe.Schmo@mail.com
Committer: 

Additional Coolness:
Having a way to not show the Parent link would also be nice.

**Comment by mhutchie** [comment]
Hi @danocharron,

Git Graph has to display a large volume of information to users in a portion of the user's screen in Visual Studio Code (unlike other dedicated Git UI applications). This means that it's a conscious effort of mine to not show redundant and/or duplicate information. All of the information currently displayed in the Commit Details View is unique to that specific commit (i.e. all the information is at a commit level). In contrast, the "Remote Path" you're requesting will be identical every time the user opens the Commit Details View for any commit in a repository (almost always), as this information is at a repository level, rather than a commit level. Every other Git UI I've checked, or even `git log`, consistently only shows commit level information in their equivalent to the Commit Details View.

If you do want to copy the remote path of a repository in the Git Graph View, you can currently do it by the following steps:
1. Open the Repository Settings Widget (by clicking the "cog" icon in the top control bar)
2. Identify the desired remote under the "Remote Configuration" section
3. Click the "pencil" icon to edit the remote, and then you can copy either the Fetch URL or Push URL.

Although including the "Remote Path" might be useful in some situations, I don't think it will add enough value for enough users that it outweighs the reasons I mentioned above. Therefore I'll close this feature request for now. If in the future there is significant user interest in this request, I'll happily re-open and implement it.

---

> Having a way to not show the Parent link would also be nice.

Is there a functional reason why you're not wanting parent links to be displayed? If there is, please let me know as I'd much rather address it (improving the experience for all users), instead of adding an extension setting to turn them off completely (which only some users will ever find). If so, please raise it as a separate feature request, as for tracking & delivery purposes, one feature request = one feature.
