### ISSUE TITLE
Context menu always on top

### ISSUE THREAD

**Issue by ghost** [mhutchie/vscode-git-graph#515]
Is it possible to have the context menu always on top?
That would be useful in a scenario like displayed below.  

![capture_20210517_181146_003](https://user-images.githubusercontent.com/68994013/118521715-970b8480-b73b-11eb-9067-4e43f989cf95.png)

**Comment by mhutchie** [comment]
Hi @kt-unzner,

The current behaviour in this scenario is definitely less than ideal, however unfortunately I was unable to implement a better solution (see the reasons below). It is one of the reasons why docking the Commit Details View to the bottom is not the default behaviour.

For conciseness, scrollable frame refers to the scrollable element containing the graph & commits.

When the Commit Details View is docked to the bottom and open, the bottom boundary of the scrollable frame is at the top boundary of the Commit Details View. The context menus for commits and reference labels are anchored relative to the Git object the user right clicked on, so that even if the user scrolls the scrollable frame, the context menu always stays pointing to the Git object it was triggered on (anything else is misleading if the user scrolls).

In the current approach (overall the simplest), the context menu is inserted into the scrollable frame. This means the context menu only needs to be positioned once at the time it is opened, and desired behaviour (mentioned in the previous paragraph) during scrolling is automatic. The disadvantage of this approach is that the context menu can only be displayed within the boundary of the scrollable frame. In the screenshot you’ve provided, the context menu is not behind the Commit Details View, it’s actually cut-off at the top boundary of it.

There are several alternative ways to implement context menus, that would allow the context menu to extend across the boundary with the docked Commit Details View. These approaches require the context menu to be inserted outside of the scrollable frame, and the extension to reposition the context menu every time the user scrolls. While this would allow the context menu to be displayed on top of the docked Commit Details View, if the user scrolls the view so that the Git object that it was triggered on is behind the Commit Details View, then the context menu visually appears to have been triggered on the Commit Details View (which is misleading and looks wrong).

I’ve already put a significant amount of time and thought into experimenting with a variety of implementation options, and ultimately the current behaviour was the best net value for users and balanced all trade-offs. (I’ve tried out many more options than what I’ve explicitly mentioned in this response)

If anyone has an alternative approach that I haven’t thought of & already tested, and can let me know, I’d be happy to try it out. I’ll close this improvement request in the meantime, and move it to the backlog

**Comment by ghost** [comment]
Okay, thanks for your explanation.
