### ISSUE TITLE
[Code Server] Could not work in other browser except chrome

### ISSUE THREAD

**Issue by DukeHouse** [mhutchie/vscode-git-graph#527]
when i update the latest code server, 

git graph could not see the history in other browser except chrome

this is a firefox ,it is the same as on my safari
![Screenshot from 2021-06-16 10-10-58](https://user-images.githubusercontent.com/52644701/122147710-ffa96680-ce8b-11eb-959e-9338efebddff.png)

**Comment by DukeHouse** [comment]
MacOS version 11.3
Ubuntu 16.04
latest coder server and git graph

**Comment by mhutchie** [comment]
Hi @DukeHouse,

You mentioned that it occurs "when i update the latest code server". Does this mean that it was working correctly in prior Code Server releases?

I've just tested Git Graph 1.30.0 via Microsoft's officially supported Codespaces on GitHub on multiple web browsers, and the extension is working correctly in Google Chrome, Firefox, Safari & Microsoft Edge. Therefore this issue is almost certainly a bug specific to the [Webview](https://code.visualstudio.com/api/extension-guides/webview) implementation used by Code Server, please raise this as a bug with them, as this issue likely affects all extensions that use Webviews (not just Git Graph).

---

FYI: I already have to test every release of the extension with the official Visual Studio Code release on Window's, Mac, Linux, Remote Development (WSL & SSH) for desktop, and Google Chrome on multiple platforms (which is the web browser that Microsoft official supports). It's simply not feasible for me to also test & officially support it for third-party services that are "compatible" with Visual Studio Code extensions, as they often have a variety of their own bugs from my past experiences with them.

**Comment by DukeHouse** [comment]
thans for your reply，i has commit issue to them. -------- 原始邮件 --------发件人： Michael Hutchison ***@***.***>日期： 2021年6月16日周三 中午12:05收件人： mhutchie/vscode-git-graph ***@***.***>抄送： DukeHouse ***@***.***>, Mention ***@***.***>主    题： Re: [mhutchie/vscode-git-graph] [Code Server] Could not work in other browser except chrome (#527)
Hi @DukeHouse,
You mentioned that it occurs "when i update the latest code server". Does this mean that it was working correctly in prior Code Server releases?
I've just tested Git Graph 1.30.0 via Microsoft's officially supported Codespaces on GitHub on multiple web browsers, and the extension is working correctly in Google Chrome, Firefox, Safari & Microsoft Edge. Therefore this issue is almost certainly a bug specific to the Webview implementation used by Code Server, please raise this as a bug with them, as this issue likely affects all extensions that use Webviews (not just Git Graph).

FYI: I already have to test every release of the extension with the official Visual Studio Code release on Window's, Mac, Linux, Remote Development (WSL & SSH) for desktop, and Google Chrome on multiple platforms (which is the web browser that Microsoft official supports). It's simply not feasible for me to also test & officially support it for third-party services that are "compatible" with Visual Studio Code extensions, as they often have a variety of their own bugs from my past experiences with them.
