### ISSUE TITLE
Click to open Diff does not work

### ISSUE THREAD

**Issue by Omcsesz** [mhutchie/vscode-git-graph#541]
Hello, Team!

When I click on a file in the Git Graph view to open diff, the diff view does not open, the file gets opened instead (see attachment). Can you fix this?
[ClickToOpenDiffDoesNotWork](https://user-images.githubusercontent.com/1839739/126618623-2a7dc9ee-6054-4bfc-b5e6-21a47546af18.gif)

System info:

Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04

**Comment by mhutchie** [comment]
Hi @Omcsesz,

The current behaviour is occurring because you are clicking on an untracked file. As it is an untracked file, it isn't tracked, so there is no prior version of the file to show in the Visual Studio Code Diff View. Therefore, Git Graph just opens the file in this specific case, instead of opening the diff (which is impossible).
