### ISSUE TITLE
Keep Sync vsCode and gitGraph in workspace

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#546]
**Describe the feature that you'd like**
I would find useful to sync Git Graph with vsCode when we do work in a workspace.

Here, when I do change the repo **(1.)** this doesn't change it in vsCode **(2.)**
![image](https://user-images.githubusercontent.com/44493964/127807457-dd6a68da-e8b2-4636-9365-2998c99ef78c.png)

**Comment by mhutchie** [comment]
Hi @rbalet,

In order to achieve this, there needs to be a method for extensions to "focus" a specific repository in Visual Studio Code (which selects it in the SCM view, updates the SCM Status Bar Item, etc.)

After reviewing the Visual Studio Code & Git Extension API's, it does not appear that Microsoft allows extensions to focus a specific repository in Visual Studio Code, and therefore this feature is not possible at the present time.

I'll move this request to the backlog for now, and keep monitoring Visual Studio Code releases for it's inclusion. Once the underlying Visual Studio Code capability is exposed for extensions, I'd be happy to reopen and implement it.
