### ISSUE TITLE
make branch-name/tag more obvious that they have forth-menu

### ISSUE THREAD

**Issue by heartacker** [mhutchie/vscode-git-graph#552]
**Describe the improvement that you'd like**
A clear and concise description of what you'd like to be improved in Git Graph.
after year ago, finally I notice that the branch/tag have right click menu for forth operation.

now, I believe that we should make the more obvious that there are menus for further operations.
eg: lighter when hover, or add some identification to tell user that there is menu.
**Additional context (optional)**
* when hover 
![image](https://user-images.githubusercontent.com/1876302/129222549-736a1369-8382-4036-ae96-baee3c1054ed.png)
* finally i know
![image](https://user-images.githubusercontent.com/1876302/129222445-73f4947c-3f72-4fc7-8e88-1e412ce7655b.png)

**Comment by mhutchie** [comment]
Hi @heartacker,

I'll close this request for now, as no other users have expressed similar concerns. The various context menus are mentioned on the extensions details, and thoroughly documented on the [GitHub Wiki](https://github.com/mhutchie/vscode-git-graph/wiki/Context-Menus) and [official documentation](https://docs.mhutchie.com/vscode-git-graph/general/context-menus).

The branch and tag labels do change to be lighter / darker when hovered, although not much. This amount of this variation is limited due to the extension having to operate with a wide range of Visual Studio Code Color Themes.

**Comment by heartacker** [comment]
thanks a lot,
maybe someday there is tooltip when  long  hover， There will be make sense and do not bother any others.
