### ISSUE TITLE
reflogs result always include remote branches

### ISSUE THREAD

**Issue by haigeno1** [mhutchie/vscode-git-graph#555]
**Describe the Bug**
when i select Include commits only mentioned by reflogs, the Show Remote Branches option is invalid.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Branches: Show All
2. select the checkbox Include commits only mentioned by reflogs
3. select or unselect the checkbox Show Remote Branches
4.error: always display the results which include the remote branches

**Expected Behaviour**
display the reflog results which exclude the remote branches

**Environment**
 - Git Graph Extension Version: [1.30.0]
 - Visual Studio Code Version: 
    Version: 1.59.0
    Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
    Date: 2021-08-04T23:14:40.191Z (2 wks ago)
    Electron: 13.1.7
    Chrome: 91.0.4472.124
    Node.js: 14.16.0
    V8: 9.1.269.36-electron.0
    OS: Darwin x64 20.4.0
 - Operating System: 
   macbookpro  macOS Big Sur 11.3.1 (20E241)

**Screenshots (optional)**
<img width="1021" alt="gitgraph-bug-desc" src="https://user-images.githubusercontent.com/34672833/130019777-3c93fd0a-5892-4fa0-9b00-4e95f8dd087f.png">

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment]
Hi @haigeno1,

These settings all directly translate to arguments passed to [`git log`](https://git-scm.com/docs/git-log). If the setting is enabled in Git Graph, then argument is provided to git, otherwise the setting is disabled, and the argument is not provided. This gives the user complete control, and is exactly consistent with [`git log`](https://git-scm.com/docs/git-log).
* Show Remote Branches: `--remotes`
* Show Tags: `--tags`
* Include commits only mentioned by reflogs: `--reflog`

In your scenario:
* Enabling "Include commits only mentioned by reflogs" means that the `--reflog` argument is provided, and the commits returned by Git are displayed.
* If you have "Show Remote Branches" disabled, and "Include commits only mentioned by reflogs" enabled, then:
    * Remote branches won't be included in the Branches dropdown
    * Remote branches won't be labelled on the commits
    * Git itself will still include the commits on the remote branches, as they are mentioned by reflogs.

The behaviour you're observing is the behaviour of the Git itself.
