### ISSUE TITLE
Ignoring VS Code Push setting when cherry-picking

### ISSUE THREAD

**Issue by andyj513** [mhutchie/vscode-git-graph#561]
This is not working as I expected, so I am calling it a bug.  If you think it is working as expected, please consider this a Feature Request.

In VS Code, I have the setting "Git: Post Commit Command" set to "push".  When I use the (built-in?) Git view, and Commit changes, they are automatically Pushed for me, so I have learned to forget there are two steps.

When I cherry-pick from Git Graph, I have the default set to not commit.  But when I am prompted, I can unselect the "No Commit" box, and Git Graph will then (correctly) do the Commit.  However, it doesn't also do the Push, and I usually don't realize my job is not done.  When I remember, I can use the Git view to do the Push (and if I look, it shows that there are changes to be Pushed).

If it is not possible for Git Graph to read and honor the "Git: Post Commit Command", then it would be nice to have Git Graph's own setting to automatically Push after a Commit.

**Comment by mhutchie** [comment]
Hi @andyj513,

The current behaviour is the expected behaviour.

Git Graph doesn’t consume any settings from Visual Studio Code’s built-in Git extension. I make all options that are available in Git Graph available in the corresponding dialog, and the extension never does anything other than exactly what the user instructed via the dialog. This is to ensure no users are ever misled while performing an operation on their repository. For the same reason, all the extension settings grouped under `git-graph.dialog.*` are used to set the default values for an option on the corresponding dialog (i.e. they never alter the behaviour in a way that’s not visible to the user). If the extension was to consume the value of one of the built-in Git extension’s settings, users would expect all of the Git extension’s settings to be consumed by the extension - which is simply not feasible, practical or in the best interest of users. Only implementing some of the Git extension’s settings is an inevitable source of confusion, and the possibility of misleading users.

I’ve decided (based on substantial user feedback) that I don’t want to group together multiple Git actions on a single dialog for numerous reasons. Ultimately, by providing each action independent of each other provides users with the most flexibility, without over complicating individual dialogs or the possibility of misleading them. While I understand that some users would like to combine some actions, which undoubtedly improves their productivity, I’ve had to carefully trade-off multiple factors based on user feedback.
