### ISSUE TITLE
On click, highlight the selected line

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#569]
**Describe the improvement that you'd like**
When clicking on a line, it would be nice if it would be getting highlighted. Like with an rgba( 255, 255, 255, 0.1) background color or so something.

![image](https://user-images.githubusercontent.com/44493964/134634542-31467a4c-7453-457b-ab16-bfb29f8a8a2a.png)

**Additional context (optional)**
I looking for an error in the commit, I know what to look for, but not which of them have the error. So I click on every line to give a look at it. But it's hard to know where I'm actually.

**Comment by mhutchie** [comment]
Hi @rbalet,

This seems to be a good use case of the existing "Code Review" feature of the extension.

![image](https://user-images.githubusercontent.com/5315753/134636370-d9b7f954-d51c-4942-b32a-3008415361dd.png)

Once a code review is started, all the files are bolded to indicate they haven't been reviewed. As you view each file, they are un-bolded to reflect this. The last viewed file (e.g. `./src/types.ts` in the above screenshot) is indicated by the "eye" symbol at the end of the line.

Please let me know if I've misunderstood your request, as I think the existing "Code Review" feature of the extension should solve the underlying use case you have.

FYI: The reason I use the "eye" symbol to indicate the last viewed file, instead of a background colour, is that the file name and modification information already uses three colours (that can be customised with the user's Visual Studio Code Color Theme), so it's not possible to pick a colour that won't clash with the text.

**Comment by rbalet** [comment]
@mhutchie That's, well... way more than expected. Thx a lot didn't known that feature :)   
Would it still make sense to make the selected list bold when clicking on it?  

I'm closing this issue.

**Comment by mhutchie** [comment]
@rbalet,

The "eye" symbol is used to indicate the last viewed / selected file.

In contrast, the bold / unbold emphasis is used to indicate whether each file has been reviewed or not, and takes affect as soon as the user performs the action. (this current behaviour was chosen to be consistent with various other tools)

The Code Review capability has been available for just over two years, and no other users so far have indicated they have a preference for an alternative method. As always, if in the future enough users express similar interest in an alternative method, I'd happily implement it at that time.
