### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by michaelslavev** [mhutchie/vscode-git-graph#582]
- Issue Type: `Performance`
- Extension Name: `git-graph`
- Extension Version: `1.30.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.61.2`

:warning: Make sure to **attach** this file from your *home*-directory:
[mhutchie.git-graph-unresponsive.cpuprofile.txt](https://github.com/mhutchie/vscode-git-graph/files/7418883/mhutchie.git-graph-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mhutchie** [comment]
Hi @michaelslavev,

I've reviewed the CPU Profile you attached, and have identified that the cause of this load was due to a Git command that took 8 seconds to run. The specific Git command is normally very quick, so based on the provided information I'll classify this as a one-off occurrence caused by Git (not the extension).
