### ISSUE TITLE
does not work with VSCode 1.69.0

### ISSUE THREAD

**Issue by BuZZ-dEE** [mhutchie/vscode-git-graph#669]
`Error loading webview: Error: Could not register service workers: TypeError: Failed to register a ServiceWorker for scope ('vscode-webview://1tvdvrkgslg5k8qc4ir5gq8rpskp2ng8aa18bj3e39crvo6t7gji/') with script ('vscode-webview://1tvdvrkgslg5k8qc4ir5gq8rpskp2ng8aa18bj3e39crvo6t7gji/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&remoteAuthority='): An unknown error occurred when fetching the script..`

**Comment by mhutchie** [comment]
Hi @BuZZ-dEE,

I've confirmed on multiple devices that Git Graph is working with Visual Studio Code 1.69.0. Additionally, no other users have reported an similar issues after updating to Visual Studio Code 1.69.0. This indicates the error you received is either intermittent, or limited to a subset of devices.

The error message you received is specific to [Visual Studio Code Webviews](https://code.visualstudio.com/api/extension-guides/webview), and would affect any extension that makes use of Webviews to render their user interface (i.e. this is not extension specific). For years Visual Studio Code has regularly introduced bugs with it's Webview implementation, impacting all extensions that rely on them. Numerous previous Visual Studio Code Webview bugs are related to Service Workers.

If you continue to encounter this error, please raise it as a bug via the Visual Studio Code GitHub repository. I've found that it's best to keep the bug title & description about the Webview error, and then use Git Graph as an example of an extension that is impacted. This way users from all extensions that are impacted can all provide examples of the error in the same thread. Otherwise the Visual Studio Code GitHub repository has duplicates of the same bug for each extension.

**Comment by BuZZ-dEE** [comment]
@mhutchie thx for your replay. it seems after the vscode something was broken with the electron version. after installing electron18 everything works again.
