### ISSUE TITLE
Activation Button on Activity Sidebar

### ISSUE THREAD

**Issue by Kira-Lappo** [mhutchie/vscode-git-graph#75]
Is that possible to add activation button on the Activity Bar, which is on the left side of VS Code window? So it could be easily found with other system buttons (Explorer, Search, Source Control etc).

**Comment by mhutchie** [comment]
Thanks for this suggestion, I'll check to see if this is possible.

**Comment by mhutchie** [comment]
After looking into this and doing some tests, it appears that in order to add a button/icon to the Activity Bar, the extension must contribute a view container with at least one view to the VS Code Sidebar, as described [here](https://code.visualstudio.com/api/references/contribution-points#contributes.viewsContainers). The Activity Bar buttons/icons cannot be used to trigger an arbitary extension command (like [StatusBarItem](https://code.visualstudio.com/api/references/vscode-api#StatusBarItem)'s can). 

Creating a Side Bar view is not something I intend to do with this extension in the near future, as I haven't found any functionality that can't be incorporated best, intuitively & visually in the [Webview](https://code.visualstudio.com/api/references/vscode-api#Webview) (not a sidebar view) that Git Graph uses.

I'll keep an eye out for if the VS Code API allows this in the future, in which case I can add it then, or if new Git Graph functionality is requested that would be best suited to a new Side Bar view.

**Comment by mhutchie** [comment]
FYI: #76 will be available in the next release, and adds a Git Graph icon to each Source Code Provider title in the built-in SCP Sidebar View, which when clicked opens Git Graph to the corresponding repository. There is a screenshot of my working POC of this [here](https://github.com/mhutchie/vscode-git-graph/issues/76#issuecomment-493007257).

**Comment by mindplay-dk** [comment]
For the record, I never would have found this without poking through docs and finally finding this issue with the POC screenshot. :relaxed: 

What do you think about maybe (optionally) docking Git Graph in a panel *below* the tabs, rather than in an actual tab? This is where it's traditionally located in many other IDEs.

Perhaps then, it "contributes" to the UI and is permitted an entry in the activity bar, where I would have expected to find it?

(The Git graph is a primary feature in my world and definitely belongs in a prominent spot - it's definitely not a secondary feature that should be relegated to a tiny corner somewhere...)

**Comment by mhutchie** [comment]
Hi @mindplay-dk,

Unfortunately Visual Studio Code currently only allows extensions to display a [Webview](https://code.visualstudio.com/api/extension-guides/webview) in the Git Graph View’s currently location. If / when Visual Studio Code supports Webviews in a panel below the tabs, I definitely want to integrate with it as an option.

As mentioned in one of my previous comments in this thread, Visual Studio Code only allows extensions to add an icon to the Activity Bar if they contribute a View Container to the Sidebar (where the Explorer and built-in VSCode Git Extension View is, not in a below the tabs as you’re requesting). Hence a Git Graph entry can’t currently be in the Activity Bar.

FYI: I’m continually monitoring the new integrations Visual Studio Code provide to extensions, especially ones that make Git Graph more discoverable and make it a more flexible tool for users.

**Comment by Kira-Lappo** [comment]
@mhutchie  love ya, one more thanks for the extension

**Comment by mindplay-dk** [comment]
> As mentioned in one of my previous comments in this thread, Visual Studio Code only allows extensions to add an icon to the Activity Bar if they contribute a View Container to the Sidebar (where the Explorer and built-in VSCode Git Extension View is, not in a below the tabs as you’re requesting).

Ah, right - I understand now. The buttons on the left are essentially vertical "tab headers" for a bunch of "tabs" in the area next to them - it's like a sideways tab-view.

I've only recently started making VS code my full-time workbench, so I'm still getting used to the UI.

Hmm, what about the bottom panel? (Output, Console, Problems, Terminal) ... is there any way to (optionally) dock the panel there? That's where it's located in e.g. Jetbrains IDEs.

**Comment by mhutchie** [comment]
Hi @mindplay-dk, Visual Studio Code currently **only allows** extensions to display a Webview in the Git Graph View’s current location, **nowhere else**.

**Comment by mindplay-dk** [comment]
They're tracking a (somewhat obscure) feature request here:

https://github.com/microsoft/vscode/issues/41686

**Comment by mindplay-dk** [comment]
@mhutchie contributing to the bottom panel [should now be possible](https://github.com/microsoft/vscode/issues/41686) - will you reopen this issue? 🙂

**Comment by mhutchie** [comment]
Hi @mindplay-dk,

That’s great news if this functionality will now be available in Visual Studio Code! I’ll start experimenting with the new functionality to see how it works, and what possible integrations it will enable. I’m really looking forward to releasing these changes!

I won’t re-open this feature request just yet, as it is not a point that it’s releasable in Git Graph. This is because I can’t just use the latest features of Visual Studio Code as soon as it becomes available, as it would require me to upgrade the minimum Visual Studio Code version requirement of Git Graph. Every time I do this, it prevents all of the Git Graph users that haven’t upgraded Visual Studio Code to the required version from receiving any new updates to Git Graph (and all the new features they include). Once the percentage of Git Graph users on compatible versions of Visual Studio Code for this feature increases to a suitable level, I’ll then re-open and implement this feature.

**Comment by AnthonyLenglet** [comment]
randomly remembered this issue 2 years later, is there a way to display the graph in a panel with the features available today ? I would love the ability to open in in a small panel in the git tab 😄
