### ISSUE TITLE
Allow to select needed branches for history graph

### ISSUE THREAD

**Issue by weynhamz** [mhutchie/vscode-git-graph#77]
**Describe the feature that you'd like**
Currently, it seems we only see either all the branches or a specific branch, but for a repository with lots of branches, sometimes you just want to see the history graph of several interested branches. 

If there is a checkbox prepend to the branch names, then we can just check the branches we want to see would be really great.

**Additional context (optional)**
N/A.

**Comment by mhutchie** [comment]
Thanks for this suggestion, I definitely also want to support selecting a subset of branches from the branch dropdown (by a checkbox or similar mechanism)!

The existing feature request #49 will focus on a delivering a mechanism to filter branches from view. Although the original request suggested the use of glob patterns, @paradoXp also suggested the use of checkboxes as a comment on that feature request. At the time I suggested both be left in the same feature request, but since you've raised one, it will mean both components of this task can be tracked with better granularity.

Both are scheduled to be implemented in an upcoming release (should be available in the next week or two).

**Comment by mhutchie** [comment]
This will be available in v1.6.0.

If you'd like to use it before the next release, you can download [v1.6.0-beta.3](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.6.0-beta.3), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by weynhamz** [comment]
Just installed the beta version, NICE!!! Thanks!!!

Though, there is one thing is kind of annoying, which is after each selection there is reloading, the reloading is fine, but, after the reloading, the scrollbar of the selection dropdown list will return to its initial position. 

It would be better if the scroll position could be restored after each reloading.

**Comment by mhutchie** [comment]
Apologies, I should have picked up on that. The behaviour is now fixed in [v1.6.0-beta.4](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.6.0-beta.4).
