### ISSUE TITLE
Combine remote and local branch labels

### ISSUE THREAD

**Issue by Kira-Lappo** [mhutchie/vscode-git-graph#78]
Branch name could be long enough so it would be awesome to combine labels of remote and local branches into the same lable.

Here is example of how it could look.
Text `origin & /f/feat1` means that there is such branch on local and remote
![Screenshot from 2019-05-16 14-57-26](https://user-images.githubusercontent.com/11411852/57852678-71fe7700-77ec-11e9-8642-809c66b35e63.png)

JetBrains do such thing in git log history
![Screenshot from 2019-05-16 15-10-39](https://user-images.githubusercontent.com/11411852/57852939-28625c00-77ed-11e9-854c-0ab3306ab453.png)

**Comment by mhutchie** [comment]
Thanks for this suggestion. I had thought about this before, however didn’t pursue it at the time because the local and remote branches both have different supported actions from their respective right click context menus. This means that simply combining the text would result in only one label with one right click context menu.

I’ll work out a way to combine local and remote branch labels, to reduce the overall label width, while still maintaining the separate right click context menus on the local and remote branches.

**Comment by iMarc92** [comment]
Its fine how it is, i use this @ work and we have lot of branches but if you have long names... i think, there is something else wrong but not in this Plugin ;)
Only my opinion, sorry

**Comment by Kira-Lappo** [comment]
> Its fine how it is, i use this @ work and we have lot of branches but if you have long names... i think, there is something else wrong but not in this Plugin ;)
> Only my opinion, sorry

well, for ex I have `feature/add-super-feature`, my co-workers have `fix/bug-12313-incorrect-value`, `feature/#123123-make-bright-future` and etc. Double these values and you will see the length of just to labels(remote and local). It's just our naming convention, which makes us create such names

**Comment by mhutchie** [comment]
This will be available in v1.6.0.

If you'd like to use it before the next release, you can download [v1.6.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.6.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by Kira-Lappo** [comment]
@mhutchie awesome! gonna test it today
