### ISSUE TITLE
Add command to manually register additional repos in a workspace (e.g. subrepos)

### ISSUE THREAD

**Issue by SirIntruder** [mhutchie/vscode-git-graph#90]
Seems that, whenever I try to open git graph for a file in subrepo which has a space in the path, things get boggled and request gets ignored (the bad repo is not added to the Repos dropdown, last opened repo gets opened instead of the real one)

Same repos had random bugs in GitExtensions software as well, GitExtensions devs said the issue is they forgot to add quotes around path in a couple of places, this fixed the issues.

**Comment by mhutchie** [comment]
Hi, Thanks for raising this issue!

I've tested repos with spaces in multiple positions within repo names (both in my release testing and again before writing this comment) and have not observed any issues with detecting, or viewing them in Git Graph.

Could you please provide the following information so I can replicate your situation to test it specifically to see what is not working for you:
- Your OS
- A small example folder tree indicating where spaces are causing issues. Please indicate:
    - Which folder in the example is opened / added to the workspace in VS Code.
    - Which folder(s) are repositories
- The value you have set `git-graph.maxDepthOfRepoSearch`

**Comment by SirIntruder** [comment]
Hey @mhutchie! The bug report is a fluke, seems that repo dropdown is populated only by clicking on git graph icon in "Source Control Providers" tab, and so it happened that I never clicked that for a pair of repos which had spaces in paths. From what I can tell all repos behave consistently no matter the number of spaces, so good job on that :D

I have "git-graph.maxDepthOfRepoSearch" set to 5, and I expected these repos to be found: 

"Assets/Standard Assets/unityutil/"

Worthy to note that there is no "Assets/Standard Assets/unityutil/git/" folder, but "Assets/Standard Assets/unityutil/.git" file with content:

"gitdir: ../../../.git/modules/Assets/Standard Assets/UnityUtil"

**Comment by mhutchie** [comment]
The current behaviour is that although Git Graph does search subdirectories for repos, it will stop as soon as a repo is found (and will not find repos within repos). This is because it adds a significant performance cost to scan all sub folders, compared to stopping as soon as a repo is found.

However, Git Graph will detect additional repos (irrespective of there position within the workspaces folders) if they are created while Git Graph is opened, or if linked from the SCP tab (like you observed) as it is easy to confirm if a path is in a new repo. (It’s just slow to search all subdirectories for them)

I hope that this explains the behaviour you observed.

I’m hesitant to expand the search to include subrepos as it has such a significant performance overhead for a fairly uncommon project structure, however I think it would be good to add a new command to the VSCode command palette allowing users to manually add in additional repos in their workspace for these situations.

If this has explained the behaviour you’ve observed, please let me know, and I’ll change this bug to a feature request, and add the command mentioned above in the next beta release (eta in the next day).

**Comment by SirIntruder** [comment]
Yup, everything work just as yout described. Guess it would be ideal if you could read the list of SourceContentProviders that vscode shows, and populate repos dropdown with that. After adding all repos in project to the dropdown. GitGraph button in status bar always opens LRU repo, while I expected repo that tracks the active document - is that something that also belongs on a "nice to have" backlog?

Thank you for your hard work, this extension is a blast 😄

**Comment by mhutchie** [comment]
I couldn’t find a way of getting a list of the registered SCM providers via the VSCode API so I wasn’t able to pursue that further. I’ll add a setting that when enabled will open Git Graph to the active document (thanks for the suggestion, it’s a great idea).

**Comment by mhutchie** [comment]
This will be available in v1.8.0.

If you'd like to use it before the next release, you can download [v1.8.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.8.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
