### ISSUE TITLE
Pull action on remote branches

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#98]
Follow the same idea as [this issues](https://github.com/mhutchie/vscode-git-graph/issues/95)
It would be nice to have a "sync with upstream" button into the configs list.

I don't know if it's make sense, but when you forking a git repo sometime you have to sync your repo with the upstream project. This utilities could help people to do that.

It will do an:
- git checkout master
- get remte add upstream (url given by the user)
- git fetch upstream
- git pull upstream master

**Comment by mhutchie** [comment]
Thanks for this suggestion!

Although it's useful if you have to do this quite specific case of four steps, I don't think it's a frequent end-to-end process for most people that it warrants its own command. I'd prefer to break it down into two components, each more commonly used, so that they could be of more frequently used by more people:
1. I already intend that [configuration of remote repositories](https://github.com/mhutchie/vscode-git-graph/issues/95) would allow remotes, including an upstream, to be added (implementing `command 2`), edited and deleted from the proposed configuration menu. This is more than what you originally suggested in the FR (allowing existing remote urls to be changed). This was why I changed the FR's name, as I though it would be best to implement add/edit/delete together as a starting point for the new config menu.
2. From the remote branch context menu, a new `Pull...` action could be added (implementing `command 4`). This has the additional benefit that it can be used for any branch on any remote.

Let me know if you agree with my suggestion. If so, this FR can be re-purposed to add the `Pull...` action on the remote branch context menu, as part one is already underway in the other FR.

Note:
- Both `command 1` and `command 4` are already provided in Git Graph.
- The sequence of four commands you provided assumes the name of the remote `upstream` (and that it doesn't already exist), and that a `master` branch exists (and it is the branch the user wants sync). Following your original suggestion, a dialog would have to be shown allowing the user to select at least one of these variables (depending on how it's implemented), in addition to desired url.

**Comment by mhutchie** [comment]
I made a typo in notes of my previous comment, I've corrected it from _"Both command 1 and command 4 are already provided in Git Graph."_ to _"Both command 1 and command 3 are already provided in Git Graph."_

As you agree with my suggestion of splitting this FR into two components, and the first is already being implemented in [configuration of remote repositories](https://github.com/mhutchie/vscode-git-graph/issues/95), I'll repurpose this FR to implement the second component (the `Pull...` action).

**Comment by mhutchie** [comment]
This will be available in v1.9.0, which will be released in the next day.
